version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ppos-mongo
    environment:
      MONGO_INITDB_DATABASE: control_plane
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
