export const de = {
  appName: 'PDF-Preflight-Prüfung',
  dragDropPrompt: 'Ziehen Sie Ihre PDF-Datei hierher oder klicken Sie zur Auswahl',
  invalidFileType: 'Ungültiger Dateityp. Bitte laden Sie eine PDF-Datei hoch.',
  loadingFile: 'PDF-Datei wird geladen...',
  preparingFileForAnalysis: 'Datei wird für die Vorstufenprüfung vorbereitet.',
  analyzingPDF: 'PDF wird analysiert...',
  thisMayTakeAMoment: 'Dies kann einen Moment dauern.',
  runPreflight: 'Preflight ausführen',
  or: 'oder',
  of: 'von',
  browseYourComputer: 'Computer durchsuchen',
  pdfMaxHint: 'PDF · max. ~50 MB',
  selectedLabel: 'Ausgewählte PDF',
  changeLabel: 'Ändern',
  uploadTipLargePdf: 'Hinweis: Große PDF-Dateien können etwas mehr Zeit in Anspruch nehmen.',
  uploadYourPdf: 'PDF hochladen',
  uploadDescription: 'Wählen Sie eine PDF-Datei für die Druckdatenprüfung',
  analyzingYourPdf: 'Ihre PDF wird analysiert...',
  analysisComplete: 'Analyse abgeschlossen',
  fixIssuesTitle: 'Fehler beheben',
  fixIssuesDescription: 'Prüfen und korrigieren Sie die {{count}} gefundenen Abweichungen',
  fixIssuesRemaing: '{{count}} Abweichung(en) verbleibend',
  reviewAndDownload: 'Prüfen & Herunterladen',
  pdfProcessedReady: 'Ihre druckfertige PDF-Datei ist bereit! Jetzt prüfen und herunterladen.',
  reviewAndApplyCorrections: 'Dokument prüfen und bei Bedarf Korrekturen anwenden.',
  back: '← Zurück',
  next: 'Weiter →',
  igniteEngine: 'Ignite V2 Engine',
  fixIssues: 'Fehler beheben →',
  continueToReview: 'Weiter zur Prüfung →',
  startOver: 'Neu beginnen',
  analysisWaitMessage: 'Bitte warten Sie, während wir Ihr Dokument auf Druckfähigkeit prüfen',
  issuesFoundMessage: 'Bitte prüfen Sie die nachfolgenden Punkte vor der Freigabe',
  pdfLooksGood: 'Ausgezeichnet! Ihre PDF ist druckfertig',
  checkingDetails: 'Schriften, Farbräume, Auflösung und Geometrie werden geprüft...',
  perfectNoIssues: 'Perfekt! Keine Abweichungen festgestellt',
  readyForPrinting: 'Ihre PDF ist bereit für die Druckproduktion',
  readyForPrint: 'Druckfertig!',
  reviewRequired: 'Prüfung erforderlich',
  readyForProduction: 'Bereit für die Fertigung',
  actionRequired: 'Aktion erforderlich',
  availableReports: 'Verfügbare Berichte',
  complianceCertified: 'Druckkonformität zertifiziert',
  txtSummary: 'TXT-Zusammenfassung',
  productionTools: 'Produktionswerkzeuge',
  aiMagicApplied: 'KI-Optimierung angewendet!',
  aiMagicDescription: 'Der KI-Assistent hat Farben, Auflösung und Beschnitt automatisch für den Druck optimiert.',
  processedSuccessfully: 'Dokument erfolgreich aufbereitet{{count, plural, =0 {} other { ({{count}} Korrektur(en) durchgeführt)}}}',
  issuesSummary: 'Abweichungsübersicht',
  overallScore: 'Gesamtbewertung',
  issueCategories: 'Kategorien',
  fileLabel: 'Datei',
  downloadReport: 'Prüfbericht herunterladen',
  downloadOriginal: 'Originaldatei herunterladen',
  reanalyzePdf: '🔄 PDF erneut analysieren',
  pdfViewer: 'PDF-Vorschau',
  pageNavigation: 'Seitennavigation',
  prevPage: 'Vorherige Seite',
  nextPage: 'Nächste Seite',
  goToPage: 'Gehe zu Seite',
  typePageNumber: 'Seitennummer eingeben',
  heatmap: 'Farbauftrag-Heatmap',
  aiVisualCheck: 'Visuelle KI-Prüfung',
  toggleTacHeatmap: 'Gesamtfarbauftrag (TAC) umschalten',
  aiVisualQualityCheck: 'Visuelle Qualitätskontrolle',
  analyzingInk: 'Farbauftrag wird ermittelt...',
  tacLessThan280: '< 280%',
  tac280to300: '280 – 300%',
  tacMoreThan300: '> 300%',
  severity: 'Schweregrad',
  page: 'Seite',
  documentWide: 'Gesamtes Dokument',
  message: 'Meldung',
  details: 'Details',
  close: 'Schließen',
  error: 'Fehler',
  noPdfLoaded: 'Keine PDF geladen. Bitte laden Sie eine Datei hoch.',
  noIssuesToDisplay: 'Keine Abweichungen anzuzeigen.',
  noIssuesFound: 'Keine Fehler gefunden. Ihre PDF ist einwandfrei!',
  noIssues: 'Keine Beanstandungen',
  noIssuesPdf: 'Keine Fehler in Ihrer PDF-Datei gefunden',
  totalIssues: 'Fehler insgesamt',
  issuesFoundApplyOrDownload: '{{count}} Abweichung(en) gefunden – Korrektur anwenden oder Original herunterladen',
  issuesFound: 'Gefundene Abweichungen',
  issues: 'Abweichungen',
  errors: 'Kritische Fehler',
  warnings: 'Warnungen',
  info: 'Hinweise',
  errAbbr: 'Fehl.',
  warnAbbr: 'Warn.',
  infoAbbr: 'Info',
  selectAnIssue: 'Wählen Sie eine Abweichung aus, um Details und Korrekturvorschläge anzuzeigen.',
  selectedIssueDetails: 'Details zur ausgewählten Abweichung',
  currentIssue: 'Aktuelle Abweichung',
  categoryImages: 'Bilder & Grafiken',
  categoryColor: 'Farbräume & Profile',
  categoryFonts: 'Schriften & Schrifteinbettung',
  categoryMetadata: 'Metadaten',
  categoryTransparency: 'Transparenzen',
  categoryBleedMargins: 'Beschnitt & Ränder',
  categoryResolution: 'Bildauflösung (DPI)',
  categoryCompliance: 'PDF/X-Konformität',
  categoryPageSetup: 'Seitenformat & Geometrie',
  categoryAnnotations: 'Anmerkungen & Kommentare',
  categoryFormFields: 'Formularfelder',
  categoryMultimedia: 'Multimedia-Elemente',
  categoryLayers: 'Ebenen (OCG)',
  categoryOther: 'Sonstiges',
  quickFixes: 'Schnellkorrekturen',
  aiAssistance: 'KI-Unterstützung',
  add3mmBleed: '🔧 3 mm Beschnittzugabe anfügen',
  convertToCMYK: '🎨 In CMYK konvertieren',
  convertToGrayscaleBtn: '⚫ In Graustufen umwandeln',
  rebuildHighRes300dpi: '🛠️ Hochauflösend neu berechnen (300 DPI)',
  converting: 'Wird konvertiert...',
  fixing: 'Wird korrigiert...',
  cmykProfile: 'CMYK-Ausgabeprofil:',
  genericCMYK: 'Standard-CMYK',
  coatedFogra39: 'ISO Coated v2 (FOGRA39)',
  coatedFogra51: 'ISO Coated v3 (FOGRA51)',
  uncoatedFogra52: 'PSO Uncoated v3 (FOGRA52)',
  gracol2006: 'GRACoL 2006 (Coated #1)',
  swop2006: 'SWOP 2006 (Coated #3)',
  uncoatedFogra29: 'PSO Uncoated ISO12647 (FOGRA29)',
  bleedSafe: 'Sicher (Box-Geometrie / Rahmen)',
  bleedAggressive: 'Skalierend (Randfüllend)',
  bleedMode: 'Beschnitt-Modus:',
  bleedSafeHint: 'Sicherer Modus ergänzt Ränder ohne Dehnen. Hinweis: Interaktive Elemente bleiben evtl. nicht erhalten.',
  optionalTools: 'Optionale Werkzeuge',
  additionalProcessingOptions: 'Zusätzliche Verarbeitungsoptionen',
  convertToGrayscale: 'In Graustufen konvertieren',
  convertColorsToCMYK: 'Farben in CMYK umwandeln',
  rebuildPdfHighRes: 'PDF hochauflösend neu erstellen',
  createBooklet: 'Broschüre ausschießen',
  downloadProcessedPdf: 'Verarbeitete PDF herunterladen',
  stepNumber: 'Schritt {{number}}',
  uploadPdf: 'PDF hochladen',
  analysis: 'Vorstufenanalyse',
  review: 'Freigabe',
  explainSuggestFix: 'Erklären & Beheben (KI-Audit)',
  explainAndSuggestFix: 'Erklären & Beheben (KI-Audit)',
  getEfficiencyTips: 'Effizienz-Tipps abrufen (KI-Audit)',
  aiAuditTitle: 'KI-Audit: Erklärung & Korrekturvorschläge',
  efficiencyAuditTitle: 'KI-Audit: Effizienzempfehlungen',
  fetchingAIResponse: 'KI-Analyse wird abgerufen...',
  aiResponse: 'KI-Antwort',
  aiError: 'Fehler beim Abrufen der KI-Antwort. Bitte prüfen Sie Ihre Verbindung.',
  geminiKeyMissingError: 'KI-Schlüssel fehlt oder ist ungültig. KI-Funktionen sind deaktiviert.',
  billingDocLink: 'Abrechnungsdokumentation ansehen',
  visualMode: 'Visueller Modus',
  fastestFix: 'Schnellste Behebung',
  bestFix: 'Beste Qualität',
  timeImpact: 'Zeitauswirkung',
  costImpact: 'Kostenauswirkung',
  aiDescriptionExplain: 'Detaillierte Ursachenanalyse und schrittweise Anleitung zur Behebung in InDesign, Acrobat oder Illustrator.',
  aiDescriptionEfficiency: 'Vergleich zwischen schnellster Korrektur und optimaler Druckqualität inklusive Rüstzeit-Auswirkungen.',
  pageLabel: 'Seite {{page}}',
  suggestedFix: 'Empfohlene Behebung',
  issueSummary: 'Zusammenfassung',
  engineHint: 'Prüfhinweis der Engine',
  drawerActions: 'Aktionen',
  actions: 'Aktionen',
  severityError: 'Fehler',
  severityWarning: 'Warnung',
  severityInfo: 'Hinweis',
  issue: 'Abweichung',
  aiHintInDrawer: 'Nutzen Sie die KI-Schaltflächen für detaillierte Erklärungen oder Rüstzeit-Tipps.',
  aiMagicFix: 'Automatische KI-Korrektur',
  aiMagicFixDesc: 'Ein Klick. Farbräume, Auflösung und Beschnitt werden vollautomatisch korrigiert.',
  manualMode: 'Manuelle Prüfung',
  manualModeDesc: 'Für Vorstufenprofis, die Abweichungen einzeln prüfen und steuern möchten.',
  recommended: 'Empfohlen',
  bestWithAi: 'Optimal mit KI-Korrektur',
  readyForAnalysis: 'Bereit zur Vorstufenanalyse',
  browseFiles: 'Dateien durchsuchen',
  processingTime: 'Bearbeitungsdauer',
  processingTimeVal: '~10–60 Sekunden',
  pdfLimit: 'PDF bis zu 50 MB',
  magicWait: 'Verarbeitung läuft...',
  dragAndDropModern: 'Ziehen Sie Ihre PDF-Datei hierher',
  changeFile: 'Andere Datei auswählen',
  safeProcessing: 'Sichere, DSGVO-konforme Verarbeitung',
  continue: 'Fortfahren',
  headerUploadTitle: 'Druckdaten hochladen',
  headerUploadSubset: 'Wählen Sie KI-Korrektur (empfohlen) oder Manuelle Vorstufe.',
  chooseWorkflow: 'Workflow auswählen',
  recommendMagicHint: 'Wir empfehlen die automatische Korrektur für die schnellste Freigabe.',
  uploadToContinue: 'Laden Sie eine PDF hoch, um fortzufahren.',
  magicPoint1: 'Behebt typische Druckprobleme (RGB, fehlender Beschnitt, Schrifteinbettung)',
  magicPoint2: 'Erstellt eine verbindliche PDF/X-Druckdatei',
  magicPoint3: 'Keine vertieften Vorstufenkenntnisse erforderlich',
  tempProcessNote: 'Dateien werden temporär verarbeitet und nach der Sitzung gelöscht.',
  manualControlTip: 'VOLLSTÄNDIGE KONTROLLE ÜBER EINZELKORREKTUREN UND FARBPROFILE.',
  serverUnavailable: 'SERVERVERBINDUNG ERFORDERLICH',
  serverUnavailableDesc: 'Farbkonvertierung (CMYK/Graustufen) steht derzeit nicht zur Verfügung.',
  retry: 'Wiederholen / Neu laden',
  profileLabel: 'Profil:',
  outputIntentLabel: 'Ausgabebedingung:',
  bleedLabel: 'Beschnitt:',
  standardDpiLabel: 'Soll-Auflösung:',
  verified: 'Geprüft ✅',
  embedded: 'Eingebettet',
  real3mmBox: 'Echte 3 mm (BleedBox)',
  highEndPrint: '300 DPI (Qualitätsdruck)',
  technicalNoteTitle: 'Vorstufen-Prüfprotokoll',
  technicalNoteDesc: 'Dieses Dokument wurde nach industriellen Vorstufenstandards optimiert.',
  outputIntentExplain: 'Ein gültiger PDF/X OutputIntent (GTS_PDFX) wurde eingebettet, um farbverbindliche Ausgabe im RIP zu sichern.',
  bypassExplain: 'Konforme Farbfelder wurden unverändert übernommen, um Farbverschiebungen zu vermeiden.',
  rewriteExplain: 'Strukturelle Bereinigung zur Sicherstellung von Schrifteinbettung und XRef-Integrität.',
  negativeStatement: 'Nach Festlegung der Ausgabebedingung erfolgten keine weiteren Farbtransformationen.',
  closeNote: 'Hinweis schließen',
  complianceSummaryTitle: 'Preflight-Konformitätsübersicht',
  labelCertificateId: 'Zertifikats-ID:',
  labelEngineVersion: 'Engine-Version:',
  labelRiskLevel: 'Risikostufe:',
  labelOutputIntent: 'Output-Intent:',
  labelStructure: 'Dokumentstruktur:',
  labelConversion: 'CMYK-Transformation:',
  labelProcessing: 'Verarbeitung:',
  labelTransparency: 'Transparenzen:',
  labelBleed: 'Beschnittzugabe:',
  statusVerified: 'Verifiziert (GTS_PDFX)',
  statusSkipped: 'Übersprungen (bereits konform)',
  statusStabilized: 'Stabilisiert via Rewrite',
  statusPreserved: 'Unverändert erhalten',
  statusApplied: 'Erfolgreich angewendet',
  riskGreen: 'GRÜN (Freigabe für Druck)',
  riskAttention: 'ACHTUNG (Prüfung erforderlich)',
  riskBlocking: 'SPERRE (Im Preflight abgewiesen)',
  labelInkCoverage: 'Farbauftrag (TAC):',
  labelMaxTac: 'Max. Ink Density:',
  labelWorstPage: 'Kritischste Seite:',
  labelTacLimit: 'Maximalgrenze:',
  tacWarningDrying: 'Hoher Farbauftrag kann zu Trocknungsverzögerungen oder Ablegen führen.',
  tacVerified: 'Innerhalb der Grenzwerte',
  labelOverprint: 'Schwarz-Überdrucken:',
  statusOverprintOk: 'Geprüft ✅',
  statusOverprintRisk: 'Aussparungs-Risiko',
  overprintWarningKnockout: 'Schwarzer Text spart Hintergrundfarben aus (Passerungenauigkeit möglich).',
  overprintWarningRegistration: 'Passer-Farbe (100% CMYK) im Layout erkannt; unzulässig im Druckbild.',
  overprintWarningRichBlack: 'Tiefschwarz bei Feinschriften erkannt; K-Only für Randschärfe empfohlen.',
  spotTitle: 'Sonderfarben-Richtlinie',
  spotLabelDetected: 'Sonderfarben:',
  spotLabelPolicy: 'Richtlinie:',
  spotStatusNone: 'KEINE',
  spotPolicyStrict: 'Strikter CMYK-Skalendruck (Offset)',
  spotPolicyConvert: 'In Prozessfarben umwandeln (Digital)',
  spotRiskGreen: 'GRÜN',
  spotRiskAttention: 'ACHTUNG',
  spotRiskBlocking: 'SPERRE',
  spotWarnWhitelistOnly: 'Ausschließlich technische Sonderfarben (Stanzen/Lacke) erkannt.',
  spotWarnNonWhitelist: 'Nicht freigegebene Sonderfarben im Dokument gefunden.',
  spotNoteTacIncluded: 'Sonderfarben sind in der TAC-Berechnung berücksichtigt.',
  spotNoteRegistration: 'Passmarken-Farbe (/Registration) im Druckbereich erkannt.',
  spotNoteSpotsInText: 'Sonderfarben in Fließtext erkannt; Umwandlung kann Kantenschärfe beeinflussen.',
  bleedMethod: 'Beschnitt-Methode:',
  bleedMethodScale: 'Centered Scaling (V3)',
  bleedMethodBox: 'Box-Anpassung (Reale Ränder)',
  bleedScaleWarning: 'Starke Skalierung erkannt (>4%). Sicherheitsabstände verringert.',
  'admin.title': 'Leitstand & Systemstatus',
  'admin.subtitle': 'SRE-COCKPIT & PLATTFORMINTEGRITÄT',
  'admin.range.24h': 'Letzte 24 Stunden',
  'admin.range.7d': 'Letzte 7 Tage',
  'admin.range.30d': 'Letzte 30 Tage',
  'admin.refresh.off': 'Manuelle Aktualisierung',
  'admin.tabs.overview': 'Übersicht',
  'admin.tabs.tenants': 'Mandanten',
  'admin.tenants.tenant': 'Mandanten-Identität',
  'admin.tenants.total': 'Auftragsvolumen',
  'admin.tenants.success': 'Zuverlässigkeit',
  'admin.tenants.latency': 'Synchronisationslatenz',
  'admin.tenants.last': 'Letzter Impuls',
  'admin.tabs.jobs': 'Aufträge',
  'admin.tabs.errors': 'Fehlerprotokoll',
  'admin.tabs.audit': 'Audit-Trail',
  'admin.tabs.controls': 'Notfall-Schalter ⚠️',
  'admin.kpi.totalJobs': 'Gesamtaufträge',
  'admin.kpi.successRate': 'Erfolgsquote',
  'admin.kpi.avgLatency': 'Durchschn. Latenz',
  'admin.kpi.deltaRate': 'Leistungsänderung',
  'admin.kpi.costProxy': 'Kostenindikator',
  'admin.kpi.p95Latency': 'P95 Latenz',
  'admin.kpi.queueBacklog': 'Warteschlangenbestand',
  'admin.kpi.oldestAge': 'Ältester Auftrag',
  'admin.queue.title': 'Warteschlangen-Matrix',
  'admin.jobs.filterTenant': 'Nach Mandanten-ID filtern...',
  'admin.jobs.filterType': 'Nach Prozesstyp filtern...',
  'admin.jobs.all': 'Alle Status',
  'admin.jobs.empty': 'Keine Vorgänge gefunden',
  'admin.audit.filterTenant': 'Audit-Protokolle durchsuchen...',
  'admin.audit.empty': 'Keine Audit-Ereignisse protokolliert',
  'admin.errors.code': 'Fehlercode',
  'admin.errors.count': 'Häufigkeit',
  'admin.errors.lastSeen': 'Zuletzt aufgetreten',
  'common.loading': 'Wird geladen...',
  'common.na': 'k. A.',
  partialCalculationTitle: 'Teilberechnung: Unvollständige Tarife',
  governedQuoteIncompleteRatesNotice: 'Diese Simulation stellt keinen verbindlichen Preis dar, da Tarife auf dem Knoten fehlen oder unkalibriert sind:',
  reviewCardIncompleteRatesNotice: 'Dieses Angebot ist nicht verbindlich, da Fertigungssätze fehlen oder unvollständig sind:',
  realQuotationOutcome: 'Reales Angebotsergebnis',
  diagnosticOutcome: 'Diagnostisches Ergebnis',
  customerPriceBeforeTax: 'Kundenpreis (Netto)',
  partialDiagnosticSubtotalTitle: 'Diagnostische Zwischensumme (Unvollständige Tarife)',
  partialDiagnosticSubtotalBadge: 'Diagnostische Zwischensumme',
  perCopyNet: '€ {{price}} / Exemplar (Netto)',
  chatInputPlaceholder: 'Beschreiben Sie Ihr Buch oder hängen Sie ein Angebots-PDF an…',
  attachPdfTooltip: 'PDF-Angebot anhängen',
  pdfOnlyError: 'Es werden ausschließlich PDF-Dokumente unterstützt.',
  uploadingQuote: 'Angebots-PDF wird hochgeladen…',
  selectThisVariant: 'Diese Variante auswählen',
  analyzingPdfDocument: 'PDF-Dokument wird analysiert…',
  pdfDetectedLanguage: 'Dokumentensprache erkannt: {{language}}',
  pdfExtractionComplete: 'Extraktion abgeschlossen. Angebot bereit zur Prüfung.',
  pdfUploadErrorMessage: 'Fehler bei der Verarbeitung des Angebots-PDFs.',
  pdfUploadedUserMsg: '[Hochgeladenes PDF]: {{filename}}',
  'onboarding.title': 'Druckerei-Einrichtung',
  'onboarding.subtitle': 'Konfigurieren Sie Werke, Maschinenpark, Papiere und Kalkulation mit intelligenter Führung.',
  'onboarding.sections': 'Einrichtungsabschnitte',
  'onboarding.findSettingOrHelp': 'Einstellung suchen oder Hilfe erhalten...',
  'onboarding.guideMe': 'Führe mich durch',
  'onboarding.continueSetup': 'Einrichtung fortsetzen',
  'onboarding.setupOverview': 'Übersicht & Bereitschaft',
  'onboarding.activeModule': 'Aktives Modul',
  'onboarding.nextAction': 'Empfohlene nächste Aktion',
  'onboarding.saveChanges': 'Änderungen speichern',
  'onboarding.unsavedChangesWarning': 'Sie haben ungespeicherte Änderungen. Beim Verlassen gehen diese verloren. Möchten Sie fortfahren?',
  'onboarding.collapseSidebar': 'Seitenleiste einklappen',
  'onboarding.expandSidebar': 'Seitenleiste ausklappen',
  'onboarding.reviewDetails': 'Details überprüfen',
  'onboarding.quickSpecs': 'Produktspezifikationen',
  'onboarding.mode.assistant': 'KI-Assistent',
  'onboarding.mode.manual': 'Manuelle Tariftabellen',
  'onboarding.mode.descAssistant': 'Beschreiben Sie einen Auftrag oder laden Sie ein PDF-Angebot hoch. Der Assistent extrahiert Spezifikationen.',
  'onboarding.mode.descManual': 'Direkte Bearbeitung der industriellen Rüstkosten, Klickpreise, Papier- und Bindekosten.',
  'onboarding.startOption.upload': 'Angebots- oder Auftragstaschen-PDF hochladen',
  'onboarding.startOption.uploadDesc': 'Laden Sie ein PDF hoch, um Buchformate, Papiere und Staffelpreise automatisch zu erfassen.',
  'onboarding.startOption.describe': 'Produkt in Freitext beschreiben',
  'onboarding.startOption.describeDesc': 'Beschreiben Sie ein zuvor gefertigtes Buch in natürlicher Fachsprache.',
  'onboarding.startOption.manual': 'Spezifikationen manuell erfassen',
  'onboarding.startOption.manualDesc': 'Öffnen Sie den Tabelleneditor, um Rüstzeiten und Maschinenstundensätze direkt einzutragen.',
  'onboarding.tutorial.stepOf': 'Schritt {{current}} von {{total}}',
  'onboarding.tutorial.next': 'Weiter',
  'onboarding.tutorial.back': 'Zurück',
  'onboarding.tutorial.exit': 'Tutorial beenden',
  'onboarding.tutorial.doThisNow': 'Jetzt ausführen',
  'onboarding.help.searchPlaceholder': 'Einstellungen, Begriffe durchsuchen (z. B. Munken, Klebebindung, USt, Fracht)...',
  'onboarding.help.noResults': 'Keine passenden Einstellungen oder Hilfethemen gefunden.',
  'onboarding.help.tip': 'Esc zum Schließen, ↑↓ zum Navigieren, Enter zum Auswählen.',
  'pricing.assistant.title': 'Preiskalkulations-Assistent',
  'pricing.assistant.header': 'Mehrsprachiger Kalkulations-Assistent',
  'pricing.assistant.subtitle': 'Beschreiben Sie ein gefertigtes Werk oder laden Sie ein PDF-Angebot hoch.',
  'pricing.assistant.headerTag': 'Mehrsprachiger PDF-Import & Kalibrierung',
  'pricing.assistant.inspectEvidence': 'Belegdaten prüfen',
  'pricing.assistant.busyTitle': 'KI-Assistent ist ausgelastet',
  'pricing.assistant.busyDesc': 'Ihre Eingaben sind gesichert. Sie können es erneut versuchen oder Daten manuell eintragen.',
  'pricing.assistant.orExample': 'Oder Beispiel auswählen:',
  'pricing.assistant.analyzing': 'Spezifikationen werden analysiert...',
  'pricing.assistant.proposedTitle': 'Vorgeschlagene Buchdaten bereit',
  'pricing.assistant.requiresConfirmation': 'Bestätigung erforderlich',
  'pricing.assistant.proposedDesc': 'Der Assistent hat Spezifikationen erkannt. Prüfen Sie die Übersicht rechts und bestätigen Sie die Übernahme.',
  'pricing.assistant.applyBtn': 'Extrahierte Daten übernehmen',
  'pricing.assistant.sendBtn': 'Senden',
  'pricing.assistant.retryBtn': 'Wiederholen',
  'pricing.assistant.drawerTitle': 'Angebotsbeleg & Variantendetails',
  'pricing.assistant.drawerSubtitle': 'Detaillierte Aufschlüsselung des Belegdokuments und der gewählten Staffel',
  'pricing.assistant.activeExtractedDoc': 'Aktives Belegdokument',
  'pricing.assistant.fileLabel': 'Datei:',
  'pricing.assistant.evidenceIdLabel': 'Beleg-ID:',
  'pricing.assistant.languageLabel': 'Sprache:',
  'pricing.assistant.pageCountLabel': 'PDF-Seitenzahl:',
  'pricing.assistant.printhouseLabel': 'Druckerei:',
  'pricing.assistant.selectedOfferTitle': 'Ausgewählte Staffel',
  'pricing.assistant.quantityLabel': 'Auflage:',
  'pricing.assistant.manufacturingLabel': 'Fertigungskosten:',
  'pricing.assistant.transportLabel': 'Fracht / Logistik:',
  'pricing.assistant.quotedTotalLabel': 'Angebotener Gesamtpreis:',
  'pricing.assistant.quotedUnitLabel': 'Angebotener Stückpreis:',
  'pricing.assistant.validationLabel': 'Plausibilität:',
  'pricing.assistant.sourceTextLabel': 'Originaltext:',
  'pricing.assistant.noOfferSelected': 'Noch keine Staffelvariante ausgewählt.',
  'pricing.assistant.noEvidenceAttached': 'Derzeit ist kein Belegdokument angehängt.',
  'pricing.assistant.physicalSpecs': 'Extrahierte Produktspezifikationen',
  'pricing.assistant.formatLabel': 'Format:',
  'pricing.assistant.bindingLabel': 'Bindung:',
  'pricing.assistant.finishingLabel': 'Veredelung:',
  'pricing.assistant.interiorPagesLabel': 'Inhaltsseiten:',
  'quoteReview.pagesExtracted': '{{count}} Seite(n) analysiert',
  'quoteReview.optionLabel': 'Option {{idx}}: € {{price}} (Fertigung)',
  'quoteReview.unitsLabel': '{{count}} Exemplare',
  'quoteReview.consistent': '✓ Plausibel',
  'quoteReview.inconsistent': '⚠ Unstimmigkeit festgestellt',
  'quoteReview.readyForCalibration': 'Bereit für Kalibrierungsprüfung',
  'quoteReview.productTitle': 'Produktbezeichnung',
  'quoteReview.formatAndBinding': 'Format & Bindung',
  'quoteReview.variantsForCopies': 'Extrahierte Varianten für {{copies}} Exemplare ({{count}} Optionen)',
  'quoteReview.quantitiesAndPrices': 'Extrahierte Auflagen & Preise ({{count}})',
  'quoteReview.mfgOffered': 'Angebotener Fertigungspreis:',
  'quoteReview.transportSep': 'Gesonderte Frachtkosten:',
  'quoteReview.notSpecified': 'Nicht angegeben',
  'quoteReview.totalOffered': 'Gesamtbetrag laut Angebot:',
  'quoteReview.unitOffered': 'Angebotener Stückpreis:',
  'quoteReview.vendorDisclaimer': 'Vom Anbieter genannt • Interne Stückkosten werden bei Kalibrierung berechnet',
  'quoteReview.selectVariantBtn': 'Variante wählen (€ {{price}})',
  'quoteReview.unitPriceDiffWarning': 'Ausgewiesener Stückpreis (€ {{quoted}}) weicht vom Quotienten Gesamtpreis / Auflage (€ {{computed}}) ab.',
  'quoteReview.showOriginalText': 'Originaltext & normalisierte Fachbegriffe anzeigen',
  'quoteReview.hideDetails': 'Details verbergen',
  'quoteReview.normalizedTerms': 'Normalisierte Begriffe:',
  'quoteReview.rawExtractedText': 'Extrahierter Rohauszug:',
  'quoteReview.noneDetected': 'Keine erkannt',
  'quoteReview.editInterpretation': 'Interpretation bearbeiten',
  'quoteReview.saveCorrections': 'Korrekturen speichern',
  'quoteReview.saving': 'Speichern...',
  'quoteReview.ignoreDocument': 'Dokument ignorieren',
  'quoteReview.markValidOffersReady': 'Gültige Angebote für Kalibrierung freigeben',
  'quoteReview.docIgnored': 'Dokument {{filename}} verworfen.',
  'pricing.mode.assistant': 'KI-Assistent',
  'pricing.mode.manual': 'Manuelle Tariftabellen',
  'pricing.mode.priceBooks': 'Preislisten',
  'pricing.mode.node': 'Knoten:',
  'pricing.mode.manualHeading': 'Industrielle Fertigungskosten & Stundensätze',
  'setup.summary.account': '1. Stammdaten & Werke',
  'setup.summary.production': '2. Betriebsbereitschaft',
  'setup.summary.pricing': '3. Industrielle Tarife',
  'setup.summary.coreStatus': 'Einrichtungsstatus',
  'setup.summary.status': 'Status:',
  'setup.summary.configured': 'Konfiguriert',
  'setup.summary.inProgress': 'In Bearbeitung',
  'setup.summary.notStarted': 'Nicht begonnen',
  'setup.summary.complete': 'EINRICHTUNG VOLLSTÄNDIG',
  'setup.summary.incomplete': 'EINRICHTUNG UNVOLLSTÄNDIG',
  'setup.summary.readyDesc': 'Bereit für Leitstand und Marktplatz-Freigabe',
  'setup.summary.incompleteDesc': 'Bitte vervollständigen Sie die 8 Module unten',
  'setup.tabs.overview': 'Übersicht der Einrichtung',
  'setup.tabs.company': 'Firmenprofil',
  'setup.tabs.sites': 'Produktionsstandorte',
  'setup.tabs.machines': 'Maschinenpark',
  'setup.tabs.capabilities': 'Fertigungskapazitäten',
  'setup.tabs.materials': 'Materialien & Papier',
  'setup.tabs.capacity': 'Produktionskapazität',
  'setup.tabs.leadTimes': 'Lieferzeiten & SLAs',
  'setup.tabs.pricing': 'Industrielle Tarife',
  'setup.tabs.shipping': 'Versand & Logistik',
  'setup.tabs.integrations': 'Integrationen & Webhooks',
  'setup.tabs.marketplace': 'Marktplatzprüfung',
  'setup.tabs.completeBadge': 'Vollständig',
  'tutorial.step1.title': 'Modulnavigation der Druckerei-Einrichtung',
  'tutorial.step1.desc': 'Wechseln Sie schnell zwischen allen 8 Modulen (Firmenprofil, Maschinenpark, Materialien, Tarife) oder prüfen Sie den Fortschritt.',
  'tutorial.step1.action': 'Modulmenü öffnen',
  'tutorial.step2.title': 'KI-Assistent für Preiskalibrierung',
  'tutorial.step2.desc': 'Unsere Kernkomponente für Angebote. Beschreiben Sie einen Auftrag oder laden Sie ein PDF hoch – Hawkeye berechnet die Tarife.',
  'tutorial.step2.action': 'Kalkulationsassistent öffnen',
  'tutorial.step3.title': 'Direkter Wechsel in den manuellen Modus',
  'tutorial.step3.desc': 'Bevorzugen Sie tabellarische Rüst- und Stundensätze? Wechseln Sie jederzeit mit einem Klick in den manuellen Modus.',
  'tutorial.step3.action': 'Modus-Umschalter prüfen',
  'tutorial.step4.title': 'Einstellungen suchen und Hilfe aufrufen',
  'tutorial.step4.desc': 'Suchen Sie gezielt nach Papiersorten, Druckbegriffen oder Parametern, ohne Menüs durchsuchen zu müssen.',
  'tutorial.step4.action': 'Suchmaske öffnen',
  'setup.overview.modulesHeading': 'Operative Module (8 Schritte)',
  'setup.overview.module1.title': '1. Firmenprofil',
  'setup.overview.module1.desc': 'Rechtsträger, Sitzland, USt-IdNr./Steuernummer und kaufmännischer Ansprechpartner.',
  'setup.overview.module2.title': '2. Produktionsstandorte',
  'setup.overview.module2.desc': 'Physische Druckereistandorte, Werksadressen und Zeitzonen.',
  'setup.overview.module3.title': '3. Maschinenpark',
  'setup.overview.module3.desc': 'Bogenoffset, Digitaldrucksysteme, Schneidemaschinen und Weiterverarbeitung.',
  'setup.overview.module4.title': '4. Fertigungskapazitäten',
  'setup.overview.module4.desc': 'Farbmanagement (CMYK, Sonderfarben, Dispersionslack), Bogenformate und PDF/X-Normen.',
  'setup.overview.module5.title': '5. Materialien & Papiere',
  'setup.overview.module5.desc': 'Substratkatalog, Papiergrammaturen, Bogenformate und Veredelungskompatibilität.',
  'setup.overview.module6.title': '6. Kapazitätsplanung',
  'setup.overview.module6.desc': 'Tagesdurchsatz, Schichtmodelle, Betriebskalender und Auslastung.',
  'setup.overview.module7.title': '7. Lieferzeiten & SLAs',
  'setup.overview.module7.desc': 'Tägliche Annahmeschlusszeiten (Cut-off), Zeitzonen, Durchlaufzeiten und Fertigstellung.',
  'setup.overview.module8.title': '8. Industrielle Tarife',
  'setup.overview.module8.desc': 'Grundpreise, Rüstkosten, Klickpreise, kg-Preise für Papier, Weiterverarbeitung und Fracht.',
  'setup.module.cta.review': 'Prüfen / Bearbeiten',
  'setup.module.cta.continue': 'Einrichtung fortsetzen',
  'setup.module.cta.start': 'Einrichtung starten',
  'setup.module.missingRequirements': 'Fehlende Voraussetzungen:',
  'setup.module.requiresSites': 'Erfordert mindestens 1 Produktionsstandort',
  'setup.module.requiresMachines': 'Erfordert mindestens 1 Maschine im Park',
  'setup.nextStep.company': 'Stammdaten und USt-IdNr. für Rechnungsstellung erforderlich',
  'setup.nextStep.sites': 'Mindestens ein Standort wird für Maschinenkonfiguration benötigt',
  'setup.nextStep.machines': 'Druckmaschinen und Weiterverarbeitung für Leistungsprüfung nötig',
  'setup.nextStep.capabilities': 'Definiert unterstützte Formate, Farbräume und Bindetechniken',
  'setup.nextStep.materials': 'Papierkatalog und Grammaturen erforderlich',
  'setup.nextStep.pricing': 'Fertigungstarife kalibrieren, um Angebote zu kalkulieren',
  'setup.nextStep.marketplace': 'Alle operativen Voraussetzungen erfüllt. Marktplatzbereitschaft abschließen.',
  'setup.error.retryLoading': 'Laden wiederholen',
  'settings.title': 'Globale Einstellungen',
  'settings.subtitle': 'Plattformkonfiguration, Mandantenprofil und Benutzereinstellungen.',
  'settings.nav.general': 'Allgemein',
  'settings.nav.notifications': 'Benachrichtigungen',
  'settings.nav.security': 'Sicherheit',
  'settings.nav.integrations': 'Integrationen',
  'settings.nav.appearance': 'Erscheinungsbild',
  'settings.general.title': 'Allgemeine Einstellungen',
  'settings.general.desc': 'Persönliche Präferenzen und Unternehmensparameter des Mandanten.',
  'settings.general.personalSection': 'Persönliche & Regionale Einstellungen',
  'settings.general.tenantSection': 'Druckerei-Mandantenprofil',
  'settings.general.language': 'Benutzeroberflächensprache',
  'settings.general.timezone': 'Zeitzone',
  'settings.general.region': 'Cloud-Infrastrukturregion',
  'settings.general.regionNotice': 'Primärer EU-Souveräner Cloud-Knoten (Verwaltet)',
  'settings.general.companyName': 'Firmenname (Rechtsträger)',
  'settings.general.taxId': 'USt-IdNr. / Steuernummer',
  'settings.general.country': 'Betriebsland',
  'settings.general.address': 'Hauptsitz-Adresse',
  'settings.general.currency': 'Kaufmännische Berechnungswährung',
  'settings.appearance.title': 'Erscheinungsbild & Anzeige',
  'settings.appearance.desc': 'Farbschema, Layoutdichte und Animationseinstellungen.',
  'settings.appearance.theme': 'Farbschema',
  'settings.appearance.dark': 'Industrie-Dunkel',
  'settings.appearance.light': 'Konzern-Hell',
  'settings.appearance.density': 'UI-Dichte',
  'settings.appearance.densityDesc': 'Passt Zeilenabstände und Polsterungen in Tabellen, Formularen und Ansichten an.',
  'settings.appearance.comfortable': 'Komfortabel',
  'settings.appearance.compact': 'Kompakt (Hohe Dichte)',
  'settings.appearance.animations': 'Benutzeroberflächen-Animationen',
  'settings.appearance.animationsDesc': 'Flüssige Übergänge aktivieren. Beachtet automatisch die Systemeinstellung prefers-reduced-motion.',
  'settings.notifications.title': 'Ereignisbenachrichtigungen',
  'settings.notifications.desc': 'Verwalten Sie operative Abonnements und Alarmkanäle für Ihren Mandanten und Ihre Rolle.',
  'settings.notifications.email': 'E-Mail für Benachrichtigungen',
  'settings.notifications.roleNoticePrinthouse': 'Bereich: Druckerei-Bediener. Zeigt ausschließlich Werksaufträge & Produktionsdispositionen an.',
  'settings.notifications.roleNoticeSuperadmin': 'Bereich: Super-Administrator. Plattformintegrität, Anomalie-Erkennung und Bereitstellungsereignisse freigeschaltet.',
  'settings.notifications.eventJobDispatch': 'Neue Fertigungsdisposition',
  'settings.notifications.eventJobDispatchDesc': 'Benachrichtigung bei Eingang eines genehmigten Druckauftrags in diesem Werk.',
  'settings.notifications.eventPreflightFail': 'Preflight-Fehler / Kritische Abweichung',
  'settings.notifications.eventPreflightFailDesc': 'Sofortige Warnung, wenn eingehende Druckdaten die PDF/X-Prüfung verfehlen.',
  'settings.notifications.eventSlaWarning': 'SLA- & Cut-off-Warnung',
  'settings.notifications.eventSlaWarningDesc': 'Warnung bei Annäherung an die tägliche Annahmeschlusszeit des Standorts.',
  'settings.notifications.eventPlatformAnomalies': 'Plattform-Anomalieerkennung (Superadmin)',
  'settings.notifications.eventPlatformAnomaliesDesc': 'Intelligenz-Ebene-Warnungen für Latenzspitzen oder Schutzschalterauslösungen.',
  'settings.notifications.eventDeployments': 'Infrastruktur-Bereitstellungsereignisse (Superadmin)',
  'settings.notifications.eventDeploymentsDesc': 'Benachrichtigt über Canary-Rollouts, Migrationen und Federation-Mesh-Updates.',
  'settings.security.title': 'Sicherheit & Zugriffskontrolle',
  'settings.security.desc': 'Sitzungsdauer, Authentifizierungshärtung und mandantenbezogenes Audit-Protokoll.',
  'settings.security.sessionTimeout': 'Inaktivitäts-Timeout (Minuten)',
  'settings.security.sessionTimeoutDesc': 'Client-Sitzung wird bei Inaktivität beendet. Gedeckelt durch die Server-Token-Laufzeit.',
  'settings.security.mfa': 'Zwei-Faktor-Authentifizierung (2FA / TOTP)',
  'settings.security.mfaStatusDisabled': 'Deaktiviert (Einrichtung erforderlich)',
  'settings.security.mfaStatusActive': 'Aktiv (Durch Authenticator-App geschützt)',
  'settings.security.mfaSetupBtn': 'Authenticator-App einrichten',
  'settings.security.mfaDisableBtn': '2FA deaktivieren',
  'settings.security.mfaModalSetupTitle': 'Zwei-Faktor-Authentifizierung einrichten',
  'settings.security.mfaSecretLabel': 'Geheimschlüssel (Manuelle Eingabe)',
  'settings.security.mfaRecoveryCodesLabel': 'Wiederherstellungscodes (Sicher aufbewahren — werden nur einmal angezeigt)',
  'settings.security.mfaCodePrompt': '6-stelligen Code aus der Authenticator-App eingeben',
  'settings.security.mfaConfirmBtn': 'Bestätigen und Aktivieren',
  'settings.security.mfaDisableTitle': 'Zwei-Faktor-Authentifizierung deaktivieren',
  'settings.security.mfaPasswordPrompt': 'Passwort eingeben, um die Deaktivierung zu bestätigen',
  'settings.security.mfaDisableConfirmBtn': 'Deaktivierung bestätigen',
  'settings.security.sessionsTitle': 'Aktive Benutzersitzungen',
  'settings.security.sessionsDesc': 'Autorisierte Geräte überwachen und unbefugten Zugriff sitzungsübergreifend widerrufen.',
  'settings.security.sessionCurrent': 'AKTUELLE SITZUNG',
  'settings.security.sessionRevoke': 'Widerrufen',
  'settings.security.sessionRevokeAll': 'Alle anderen Sitzungen widerrufen',
  'settings.security.sessionIp': 'IP-Adresse',
  'settings.security.sessionAgent': 'Gerät / Browser',
  'settings.security.sessionCreated': 'Angemeldet',
  'settings.security.sessionLastActive': 'Zuletzt aktiv',
  'settings.security.sessionRevokedSuccess': 'Sitzung erfolgreich widerrufen.',
  'settings.security.sessionRevokeAllSuccess': 'Alle anderen Sitzungen wurden widerrufen.',
  'settings.security.auditLog': 'Audit-Trail-Explorer',
  'settings.security.auditLogDesc': 'Unveränderliches Live-Protokoll der operativen Aktionen dieses Mandanten.',
  'settings.security.auditEmpty': 'Noch keine Audit-Einträge für diesen Mandanten vorhanden.',
  'settings.integrations.title': 'Konnektoren & Webhooks',
  'settings.integrations.desc': 'Industrielle MIS/ERP-Brücken, JDF/JMF-Werkstatt-Automatisierung und ausgehende Webhooks.',
  'settings.integrations.webhookUrl': 'Produktionsdisposition-Webhook-URL',
  'settings.integrations.webhookSecret': 'Webhook-Signiergeheimnis (HMAC-SHA256)',
  'settings.integrations.webhookSecretHint': 'Payloads werden mit HMAC-SHA256 im Header X-PPOS-Signature signiert.',
  'settings.integrations.rotateSecretBtn': 'Geheimnis rotieren',
  'settings.integrations.rotateSecretSuccess': 'Webhook-Signiergeheimnis erfolgreich rotiert.',
  'settings.integrations.testWebhookBtn': 'Test-Webhook einreihen',
  'settings.integrations.testPayloadSuccess': 'Test-Payload erfolgreich in die Outbox eingereiht.',
  'settings.integrations.webhookSubscriptionsTitle': 'Aktive Webhook-Abonnements',
  'settings.integrations.recentDeliveriesTitle': 'Kürzliche Outbox-Zustellungen',
  'settings.integrations.resendBtn': 'Erneut senden',
  'settings.integrations.slackTitle': 'Operative Slack-Benachrichtigungen',
  'settings.integrations.slackToggle': 'Slack-Alarmkanal',
  'settings.integrations.slackDesc': 'Senden Sie dringende Fertigungs-, Kalibrier- und SLA-Warnungen an Ihren Slack-Kanal.',
  'settings.integrations.slackWebhook': 'Eingehende Slack-Webhook-URL',
  'settings.integrations.slackChannel': 'Kanalname',
  'settings.integrations.slackTestBtn': 'Test-Alarm senden',
  'settings.integrations.slackTestSuccess': 'Slack-Testalarm erfolgreich zugestellt.',
  'settings.integrations.slackSaved': 'Slack-Integrationskonfiguration gespeichert.',
  'settings.integrations.connectorsTitle': 'Industrielle MES- & Werkstatt-Konnektoren',
  'settings.integrations.statusActive': 'Verbunden',
  'settings.integrations.statusPending': 'Anmeldedaten erforderlich',
  'settings.integrations.statusRoadmap': 'Katalog-Konnektor',
  'settings.save': 'Änderungen speichern',
  'settings.saving': 'Konfiguration wird gespeichert...',
  'settings.saved': 'Änderungen gespeichert',
  'settings.error': 'Fehler beim Speichern. Bitte wiederholen.',
  'settings.savedLocalOnly': 'Einstellungen lokal gespeichert. Profilabgleich mit dem Server ausstehend oder offline.',
  'settings.savedProfileOnly': 'Profil gespeichert. Benachrichtigungseinstellungen ausstehend oder offline.',
  'settings.notifications.saveFailed': 'Benachrichtigungseinstellungen konnten auf dem Server nicht aktualisiert werden.',
  'settings.security.mfaStatusPending': 'MFA nicht eingerichtet',
  'settings.security.mfaDetailsBtn': '2FA konfigurieren',
  'settings.security.openForensics': 'Forensik-Explorer öffnen →',
  'settings.security.loadingAudit': 'Audit-Protokoll des Mandanten wird geladen...',
  'settings.security.mfaModalTitle': 'Zwei-Faktor-Authentifizierung konfigurieren',
  'settings.security.mfaModalStatus': 'Scannen Sie den QR-Code oder geben Sie den Geheimschlüssel in Ihre Authenticator-App ein.',
  'settings.security.mfaModalArchitecture': 'Industrielle Sicherheitsrichtlinien:',
  'settings.security.mfaModalWebAuthn': 'FIDO2 / WebAuthn-Sicherheitsschlüssel für Werkstatt-Terminals unterstützt.',
  'settings.security.mfaModalTotp': 'RFC 6238 TOTP Authenticator-App-Fallback.',
  'settings.security.mfaModalIsolation': 'Mandantenisolierter kryptografischer Salt und biometrische Absicherung pro Arbeitsplatz.',
  'settings.security.mfaCloseBtn': 'Schließen',
  'settings.integrations.testPayloadUnavailable': 'Live-Webhook-Gateway in dieser Umgebung nicht aktiv.',
  'settings.integrations.slackPendingNotice': 'Slack-Integration aktiv. Webhook-URL wird sicher auf dem Server gespeichert.',
  'nav.governance': 'Globale Governance',
  'nav.federation': 'Föderation',
  'nav.dashboard': 'Dashboard',
  'nav.printhouses': 'Druckereien',
  'nav.printhouse-onboarding': 'Druckerei-Onboarding',
  'nav.onboarding-observability': 'Onboarding-Observierbarkeit',
  'nav.jobs': 'Eingehende Aufträge',
  'nav.preflight': 'Preflight-Service',
  'nav.manufacturing': 'Fertigungswarteschlange',
  'nav.machines': 'Maschinenpark',
  'nav.materials': 'Materialien & Papier',
  'nav.pricing': 'Preisprofile',
  'nav.intelligence': 'Intelligenzebene',
  'nav.marketplace': 'Marktplatz',
  'nav.financials': 'Finanzoperationen',
  'nav.billing-usage': 'Abrechnung & Pläne',
  'nav.production-monitoring': 'Produktionsüberwachung',
  'nav.industrial': 'Industrieller Betrieb',
  'nav.beta-runtime': 'Beta-Laufzeitumgebung',
  'nav.beta-cohorts': 'Beta-Kohorten',
  'nav.beta-governance': 'Beta-Governance',
  'nav.tenants': 'Mandantenverwaltung',
  'nav.audit': 'Audit-Protokolle',
  'nav.settings': 'Einstellungen',
  'nav.printhouseSetup': 'Druckerei-Einrichtung',
  'nav.helpConsole': 'Betriebssystem-Hilfekonsole',
  'nav.logout': 'Sitzung beenden',
  'nav.navigation': 'Navigation',
  'nav.collapseSidebar': 'Seitenleiste einklappen',
  'nav.expandSidebar': 'Seitenleiste ausklappen',
  'setup.section.company': 'Firmenprofil',
  'setup.section.companyDesc': 'Rechtsträger, Sitzland, USt-IdNr./Steuernummer und kaufmännischer Ansprechpartner.',
  'setup.section.sites': 'Produktionsstandorte',
  'setup.section.sitesDesc': 'Physische Druckereistandorte, Werksadressen, Ortsangaben und Zeitzonen.',
  'setup.section.machines': 'Maschinenpark',
  'setup.section.machinesDesc': 'Bogenoffset, Digitaldrucksysteme, Schneidemaschinen, Bindegeräte und Weiterverarbeitung.',
  'setup.section.capabilities': 'Fertigungskapazitäten',
  'setup.section.capabilitiesDesc': 'Farbmanagement (CMYK, partieller UV-Lack, Weißdruck), Maximalformate und PDF/X-Spezifikationen.',
  'setup.section.materials': 'Materialien & Papier',
  'setup.section.materialsDesc': 'Substratkatalog, Papiergrammaturen, Bogenformate und Veredelungskompatibilität.',
  'setup.section.capacity': 'Produktionskapazität',
  'setup.section.capacityDesc': 'Tagesdurchsatz, Schichtmodelle, Betriebskalender und Auftragszuteilung.',
  'setup.section.leadTimes': 'Lieferzeiten & SLAs',
  'setup.section.leadTimesDesc': 'Standortbezogene Annahmeschlusszeiten (Cut-off), Zeitzonen, Durchlaufzeiten und Fertigstellung.',
  'setup.section.pricing': 'Industrielle Tarife & Kosten',
  'setup.section.pricingDesc': 'Grundpreise, Rüstkosten, Klickpreise, kg-Preise für Papier, Weiterverarbeitung und Fracht.',
  'setup.section.shipping': 'Versand & Logistik',
  'setup.section.shippingDesc': 'Speditionen, Verpackungsoptionen, Frachttariftabellen und Sendungsverfolgung.',
  'setup.section.integrations': 'Integrationen & Webhooks',
  'setup.section.integrationsDesc': 'Industrielle MIS/ERP-Schnittstellen, JDF/JMF-Werkstatt-Automatisierung und Webhooks.',
  'setup.section.marketplace': 'Marktplatzbereitschaft',
  'setup.section.marketplaceDesc': 'Qualifikationskriterien prüfen, Kapazitäten veröffentlichen und Aufträge empfangen.',
  'company.title': 'Firmenprofil',
  'company.legalName': 'Firmenname (Rechtsträger)',
  'company.tradingName': 'Handels- / Anzeigename',
  'company.country': 'Hauptsitzland',
  'company.city': 'Stadt / Gemeinde',
  'company.address': 'Geschäftsadresse',
  'company.postalCode': 'Postleitzahl',
  'company.phone': 'Offizielle Telefonnummer',
  'company.website': 'Website-URL',
  'company.contactName': 'Hauptansprechpartner',
  'company.taxId': 'USt-IdNr. / Steuernummer',
  'company.registrationId': 'Handelsregisternummer (Optional)',
  'company.saveBtn': 'Firmenprofil speichern',
  'company.savingBtn': 'Änderungen werden gespeichert...',
  'jobs.title': 'Eingehende Fertigungsaufträge',
  'jobs.subtitle': 'Operatives Leitpult — Produktionsabruf',
  'jobs.refresh': 'Aktualisieren',
  'jobs.statPending': 'Ausstehend',
  'jobs.statActive': 'Aktiv',
  'jobs.statRejected': 'Abgelehnt',
  'jobs.statExpired': 'Abgelaufen',
  'jobs.thIdentity': 'Auftragskennung',
  'jobs.thSpecs': 'Spezifikationen & Richtlinie',
  'jobs.thCustomer': 'Kunde',
  'jobs.thStatus': 'Status',
  'jobs.thActions': 'Aktionen',
  'jobs.actionAccept': 'Annehmen',
  'jobs.actionReject': 'Ablehnen',
  'jobs.actionStartProduction': 'Produktion starten',
  'jobs.actionComplete': 'Abschließen',
  'jobs.statusFinished': 'Fertiggestellt',
  'jobs.downloadBundle': 'Fertigungspaket herunterladen',
  'jobs.emptyTitle': 'Keine eingehenden Aufträge gefunden',
  'jobs.invalidPayload': 'Ungültige Fertigungsdaten vom Server empfangen',
  'jobs.errorTitle': 'Pipeline-Fehler',
  'jobs.retry': 'Erneut versuchen',
  'preflight.title': 'Industrielle Preflight-Konsole',
  'preflight.subtitle': 'Hochdichte Schnittstelle für reale Auftragsoperationen, Stapelverarbeitung und forensische Audittelemetrie direkt auf der kanonischen V2-Vertragsebene.',
  'preflight.quotaUsage': 'Globale Speicherquote',
  'preflight.allocated': 'zugewiesen',
  'preflight.upstreamDirect': 'Direkter Upstream-Vertrag',
  'preflight.tabJobs': 'Auftragsregister',
  'preflight.tabBatches': 'Stapelverarbeitung',
  'preflight.tabAudit': 'Audit-Protokollbuch',
  'preflight.tabGovernance': 'Governance-Matrix',
  'preflight.filterTenant': 'Nach Mandanten-ID filtern...',
  'manufacturing.title': 'Fertigungsleitsystem (MES)',
  'manufacturing.subtitle': 'Industrielle Werkstatt-Steuerung, Fertigungspakete, Abrufhistorie und Knotenabrechnung.',
  'manufacturing.tabIncoming': 'Eingehende Aufträge',
  'manufacturing.tabPackages': 'Fertigungspakete',
  'manufacturing.tabHistory': 'Abrufhistorie',
  'manufacturing.tabMatching': 'Knoten-Matching',
  'manufacturing.tabBilling': 'Finanzabrechnung',
  'manufacturing.packagesCatalog': 'Katalog der Fertigungspakete',
  'manufacturing.packagesDesc': 'Sichere Verbindungsebene zur Zuordnung geprüfter Vorstufendaten auf physische Produktionsbogen.',
  'marketplace.title': 'Marktplatz-Auftragseingang',
  'marketplace.subtitleSuperadmin': 'Operative Erfassung von Marktplatz-Aufträgen, Produktionsdateien, Preissitzungen, Druckreife und Übergabevorbereitung.',
  'marketplace.subtitlePrinthouse': 'Ihrer Druckerei zugewiesene Aufträge aus dem PrintPrice-Marktplatz, Produktionsdateien, Druckreife und Übergabe.',
  'marketplace.tabIntake': 'Auftragseingang',
  'marketplace.tabSessions': 'Preissitzungen',
  'marketplace.tabReadiness': 'Produktionsreife',
  'marketplace.tabHandoff': 'Druckerei-Übergabe',
  'marketplace.tabAuctions': 'Kapazitätsauktionen',
  'marketplace.tabAudit': 'Audit / Ereignisse',
  'marketplace.kpiNewOrders': 'Neue Aufträge',
  'marketplace.kpiFilesUploaded': 'Hochgeladene Dateien',
  'marketplace.kpiPreflightReq': 'Preflight erforderlich',
  'marketplace.kpiPaymentBlocked': 'Zahlung blockiert',
  'marketplace.kpiReadyHandoff': 'Bereit zur Übergabe',
  'marketplace.kpiBlockedOrders': 'Blockierte Aufträge',
  'marketplace.searchPlaceholder': 'Nach Auftragsref., E-Mail oder ID filtern...',
  'marketplace.thPublicRef': 'Öffentliche Ref.',
  'marketplace.thCreated': 'Erstellt',
  'marketplace.thCustomer': 'Kunde / Sitzung',
  'marketplace.thSpecs': 'Spezifikationen',
  'marketplace.thPrinter': 'Drucker / Druckerei',
  'marketplace.thFiles': 'Dateien',
  'marketplace.thPreflight': 'Preflight',
  'marketplace.thPayment': 'Zahlung',
  'marketplace.thTotal': 'Gesamtbetrag',
  'marketplace.thStatus': 'Betriebsstatus',
  'marketplace.thActions': 'Aktionen',
  'marketplace.viewOrder': 'Auftrag anzeigen',
  'marketplace.emptyOrders': 'Keine Marktplatz-Aufträge gefunden',
  'dashboard.titleControlPlane': 'Kontrollzentrum',
  'dashboard.titlePrinthouse': 'Druckerei-Portal',
  'dashboard.subtitleControlPlane': 'Operative Intelligenz & Einsatzleitung',
  'dashboard.subtitlePrinthouse': 'Operativer Arbeitsbereich & Fertigungsdisposition',
  'dashboard.kpiJobsToday': 'Aufträge heute',
  'dashboard.kpiActiveJobs': 'Aktive Aufträge',
  'dashboard.kpiRealExtraction': 'Reale Extraktion',
  'dashboard.kpiCertifiable': 'Zertifizierbar',
  'dashboard.kpiRuntimeFailures': 'Laufzeitfehler',
  'dashboard.kpiArtifactStorage': 'Artefaktspeicher',
  'dashboard.kpiOperationalNodes': 'Aktive Knoten',
  'dashboard.kpiAuditStatus': 'Audit-Status',
  'dashboard.panelPreflight': 'Preflight',
  'dashboard.panelGovernance': 'Governance',
  'dashboard.panelFederation': 'Föderationstopologie',
  'dashboard.liveStream': 'Aktueller operativer Ereignisstrom',
  'dashboard.systemStatus': 'System:',
  'setup.cta.configureCompany': 'Firmenprofil einrichten',
  'setup.cta.addSite': 'Produktionsstandort anlegen',
  'setup.cta.configureMachines': 'Maschinenpark konfigurieren',
  'setup.cta.configureCapabilities': 'Fertigungskapazitäten festlegen',
  'setup.cta.configureMaterials': 'Materialkatalog pflegen',
  'setup.cta.configureCapacity': 'Produktionskapazität einrichten',
  'setup.cta.configureLeadTimes': 'Lieferzeiten & SLAs festlegen',
  'setup.cta.configurePricing': 'Industrietarife kalibrieren',
  'setup.cta.reviewMarketplace': 'Marktplatzbereitschaft prüfen',
  'setup.module.resolveDependency': 'Voraussetzung beheben',
  'setup.nextStep.capacity': 'Schichtmodelle, Betriebskalender und Tagesdurchsatzgrenzen erforderlich',
  'setup.nextStep.leadTimes': 'Tägliche Annahmeschlusszeiten (Cut-off) und Durchlaufzeiten für Terminierung erforderlich',
  'setup.card.recommendedBadge': 'Empfohlener nächster Schritt',
  'setup.card.blockedBadge': 'Voraussetzung erforderlich',
  'setup.summary.dimensionAccount': 'Konto & Identität',
  'setup.summary.dimensionOps': 'Betriebsbereitschaft',
  'setup.summary.dimensionPricing': 'Industrielle Tarife',
  'setup.summary.dimensionMarketplace': 'Marktplatz-Status',
  'setup.summary.requirementsCount': 'Kriterien erfüllt',
  'setup.summary.ratesConfigured': 'Tarife & Bücher bereit',
  'setup.summary.ratesPending': 'Tarife nicht konfiguriert',
  'dashboard.metricDegradation': 'Verschlechterung der Quelltelemetrie:',
  'dashboard.metricDegradationDesc': 'Bestimmte Produktionsregister arbeiten im fehlertoleranten Isolationsmodus. Entsprechende KPIs zeigen N/V.',
  'dashboard.rowTotalAnalyzed': 'Gesamt analysiert (Heute)',
  'dashboard.rowActiveConcurrent': 'Aktive gleichzeitige Aufgaben',
  'dashboard.rowCompletedAnalyses': 'Abgeschlossene Analysen',
  'dashboard.rowFailedExecutions': 'Fehlgeschlagene Ausführungen',
  'dashboard.rowRealExtraction': 'Realer Extraktionsvertrag',
  'dashboard.rowRuntimeEnvFailures': 'Laufzeitumgebungsfehler',
  'dashboard.rowPartialArtifacts': 'Teilweise Artefaktblöcke',
  'dashboard.rowMeanRiskScore': 'Durchschnittliche Risikobewertung',
  'dashboard.rowRegistryBuffer': 'Register-Puffertiefe',
  'dashboard.rowLatestExecution': 'Letzter Ausführungsstatus',
  'dashboard.rowActivePolicies': 'Aktive Schwarm-Richtlinien',
  'dashboard.rowLatestRule': 'Zuletzt ausgelöste Regel',
  'dashboard.rowPolicyInterceptions': 'Richtlinien-Abfangvorgänge',
  'dashboard.rowCertBlocked': 'Zertifizierungsblockierte Objekte',
  'dashboard.rowPassedCertifiable': 'Freigegebene zertifizierbare Mengen',
  'dashboard.rowDeploymentClass': 'Bereitstellungsvertragsklasse',
  'dashboard.rowAuditRegistryState': 'Zustand des Audit-Registers',
  'dashboard.rowEstimatedValue': 'Geschätzter generierter Wert',
  'dashboard.rowAvoidedWaste': 'ROI durch vermiedene Nachdrucke',
  'dashboard.rowHoursSaved': 'Verifizierte eingesparte Vorstufenstunden',
  'dashboard.rowAutoFixSuccess': 'Erfolgreiche AutoFix-Korrekturen',
  'dashboard.rowAutoFixFailures': 'Fehlgeschlagene AutoFix-Versuche',
  'dashboard.rowQualityBenchmark': 'Abgeleiteter Qualitätsmaßstab',
  'dashboard.rowVerifiedNodes': 'Verifizierte Schwarm-Knoten',
  'dashboard.rowActiveRoutes': 'Aktive Routenzuweisungen',
  'dashboard.rowMissingGis': 'Fehlende GIS-Koordinaten',
  'dashboard.rowDegradedInfra': 'Degradierter Infrastrukturzustand',
  'dashboard.rowMeanUtilization': 'Durchschnittliche Knotenauslastung',
  'dashboard.consensusSecure': 'SCHWARM-KONSENS: GESICHERT',
  'dashboard.consensusDesc': 'Dispatch-Cluster arbeiten nativ über dezentrale Koordinatenvererbungskarten der Maschinenprofile.',
  'dashboard.viewGeoMap': 'Geografische Karte anzeigen ↓',
  'dashboard.noOperationalLogs': 'Keine operativen Protokolle im aktiven Datenbank-Snapshot. System im Bereitschaftsmodus.',
  'preflight.thJobPayload': 'Auftragslast',
  'preflight.thTenantIdentity': 'Mandantenidentität',
  'preflight.thTypePolicy': 'Typ / Geltungsrichtlinie',
  'preflight.thPayloadSize': 'Dateigröße',
  'preflight.thStatusFidelity': 'Status & Qualität',
  'preflight.thDiagnostics': 'Diagnose / Korrekturergebnis',
  'preflight.thTimeline': 'Zeitachse',
  'preflight.filterPrinthouse': 'Nach Druckereibereich filtern...',
  'preflight.resetFilters': 'Filter zurücksetzen',
  'preflight.statusAll': 'Status: Alle',
  'preflight.typeAll': 'Typ: Alle',
  'preflight.policyAll': 'Richtlinie: Alle',
  'marketplace.drawerTitle': 'Auftragskennung:',
  'marketplace.prodBlockers': 'Produktionsblockaden erkannt',
  'marketplace.btnAcknowledge': 'Auftrag bestätigen',
  'marketplace.preflightGates': '1. Vorstufen-Prüftore',
  'marketplace.runPreflight': 'Preflight ausführen',
  'marketplace.requirePreflight': 'Preflight verlangen',
  'marketplace.forcePass': 'Manuell freigeben',
  'marketplace.forceFail': 'Manuell ablehnen',
  'marketplace.paymentGates': '2. Zahlungstore',
  'marketplace.verifyApprove': 'Prüfen & Genehmigen',
  'marketplace.blockPayment': 'Zahlung blockieren',
  'marketplace.printhouseHandoff': '3. Druckerei-Übergabe',
  'marketplace.assignPh': 'Druckerei zuweisen',
  'marketplace.preparePackage': 'Paket vorbereiten',
  'marketplace.markReady': 'Als bereit markieren',
  'marketplace.requestAction': 'Kundenaktion anfordern',
  'marketplace.internalNotes': 'Interne Hauptbuchnotizen',
  'marketplace.addNote': 'Interne Notiz hinzufügen',
  'marketplace.auditTimeline': 'Unveränderliche Audit-Zeitleiste',
  'marketplace.selectedOffer': 'Ausgewähltes Marktplatzangebot',
  'marketplace.prodFiles': 'Produktionsdateien',
  'marketplace.noProdFiles': 'Keine Produktionsdateien gefunden',
  'topbar.devPreview': 'Entwicklungsvorschau',
  'topbar.prodEnv': 'Produktionsumgebung',
  'topbar.certified': 'v2.0.0 Zertifiziert',
  'topbar.region': 'EU-WEST-1 (Primär)',
  'topbar.settings': 'Einstellungen',
  'topbar.logout': 'Abmelden',
  'topbar.closeSession': 'Sitzung beenden?',
  'topbar.logoutConfirm': 'Sind Sie sicher, dass Sie sich vom Kontrollzentrum abmelden möchten?',
  'topbar.cancel': 'Abbrechen',
  'jobs.syncing': 'Fertigungswarteschlange wird synchronisiert...',
  'jobs.validationSeed': 'Validierungs-Seed — kein Fertigungspaket',
  'jobs.syncingPackage': 'Paketdaten werden synchronisiert...',
  'dashboard.osControlCenter': 'Betriebssystem-Leitstelle',
  'dashboard.printhouseHub': 'Druckerei-Zentrum',
  'dashboard.printhouseDesc': 'Echtzeit-Produktionsdaten, Auftragsstatus und Betriebsmetriken.',
  'dashboard.osControlDesc': 'Globale Governance, Echtzeitdaten und Infrastrukturkoordination.',
  'dashboard.last24Hours': 'Letzte 24 Stunden',
  'dashboard.assignedJobs': 'Zugewiesene Aufträge',
  'dashboard.globalJobs': 'Globale Aufträge',
  'dashboard.slaSuccess': 'SLA-Erfolgsrate',
  'dashboard.avgTurnaround': 'Durchschnittliche Durchlaufzeit',
  'dashboard.meanLatency': 'Mittlere Latenz',
  'dashboard.pendingAction': 'Ausstehende Aktionen',
  'dashboard.queueDepth': 'Warteschlangentiefe',
  'dashboard.activeGovBlocks': 'Aktive Governance-Blöcke',
  'dashboard.exploreAll': 'Alle anzeigen',
  'dashboard.noActiveGovBlocks': 'Keine aktiven Governance-Blöcke',
  'dashboard.workerCluster': 'Worker-Cluster',
  'dashboard.efficiency': 'Effizienz',
  'dashboard.workersActive': 'Aktive Worker',
  'dashboard.regionalCluster': 'Regionales Cluster eu-west-1',
  'dashboard.queueStream': 'Warteschlangen-Datenstrom',
  'dashboard.liveBufferTrace': 'Echtzeit-Puffer-Trace',
  'dashboard.attachingStream': 'Verbindung zum Stream wird hergestellt...',
  'dashboard.errorLoadingStream': 'Fehler beim Laden des Streams',
  'dashboard.queueStatus': 'Warteschlangenstatus',
  'dashboard.jobCount': 'Auftragsanzahl',
  'dashboard.description': 'Beschreibung',
  'dashboard.statusActiveDesc': 'Aufträge, die derzeit von Workern verarbeitet werden',
  'dashboard.statusWaitingDesc': 'Aufträge in der Warteschlange, die auf freie Worker warten',
  'dashboard.statusDelayedDesc': 'Geplante oder verzögerte Aufträge',
  'dashboard.statusFailedDesc': 'Aufträge mit Fehlern während der Ausführung',
  'dashboard.statusCompletedDesc': 'Erfolgreich abgeschlossene Aufträge',
  'dashboard.sourceUnavailable': 'N/V — Quelle nicht verfügbar',
  'dashboard.sourceUnavailableShort': 'N/V — nicht verfügbar',
  'dashboard.missionControlError': 'Telemetriefehler der Leitstelle',
  'dashboard.liveAuditPipeline': 'Echtzeit-Audit-Pipeline',
  'preflight.policiesUnavailable': 'Echte Preflight-Richtlinien sind nicht verfügbar. Die Transformation ist deaktiviert, bis der Upstream-Katalog wiederhergestellt ist.',
  'preflight.policiesDegraded': 'Upstream-Richtlinienkatalog nicht erreichbar. Autoritative lokale Versionen werden als Fallback für die Transformation verwendet.',
  'preflight.fixResult': 'Korrekturergebnis',
  'preflight.issues': 'Probleme',
  'preflight.fixes': 'Korrekturen',
  'preflight.batch': 'Stapel',
  'preflight.untitled': 'Ohne_Titel.pdf',
  'preflight.registered': 'Registriert',
  'preflight.batchId': 'Stapel-ID',
  'preflight.tenantArray': 'Tenant-Array',
  'preflight.stagedJobsCount': 'Anzahl vorbereiteter Aufträge',
  'preflight.executionStatus': 'Ausführungsstatus',
  'preflight.timestamp': 'Zeitstempel',
  'preflight.auditIdTrace': 'Audit-ID / Trace',
  'preflight.operationAction': 'Betriebsaktion',
  'preflight.resolutionStatus': 'Auflösungsstatus',
  'preflight.messageTrail': 'Meldungsverlauf',
  'preflight.loggedAt': 'Protokolliert am',
  'preflight.eventLedgerId': 'Ereignisbuch-ID',
  'preflight.tenantTarget': 'Ziel-Tenant',
  'preflight.rulePolicySlug': 'Richtlinien-Kürzel',
  'preflight.evaluationStatus': 'Bewertungsstatus',
  'preflight.enforcedAction': 'Erzwungene Aktion',
  'preflight.registeredTimestamp': 'Registrierter Zeitstempel',
  'preflight.gatewayCriticalError': 'Kritischer Fehler bei der Upstream-Gateway-Integration:',
  'preflight.executeRetry': 'Wiederholen',
  'dashboard.panelFleet': 'Maschinenflotte',
  'dashboard.panelStorage': 'Speicher',
  'dashboard.panelIncidentBridge': 'Störungszentrale',
  'dashboard.panelIntelligenceLayer': 'Intelligenzschicht',
  'dashboard.panelEconomy': 'Wirtschaft',
  'dashboard.panelHeartbeat': 'Heartbeat-Matrix',
  'dashboard.panelSystemRegistry': 'Systemregister',
  'dashboard.panelHeatmap': 'Fertigungs-Heatmap',
  'dashboard.panelDispatchConsole': 'Versandkonsole',
  'dashboard.panelRoutingSimulation': 'Routingsimulation',
  'dashboard.panelConsole': 'Systemkonsole',
  'dashboard.panelOperationalSummary': 'Betriebsübersicht',
  'dashboard.panelOperationalActivity': 'Betriebsaktivitätsstrom',
  'dashboard.activeJobs': 'Aktive Aufträge',
  'dashboard.failedToday': 'Fehlgeschlagen (Heute)',
  'dashboard.completedJobsToday': 'Heute abgeschlossene Aufträge',
  'dashboard.throughput': 'Durchsatz',
  'dashboard.storageUtilized': 'Belegter Speicher',
  'dashboard.activeArtifacts': 'Aktive Artefakte',
  'dashboard.artifacts': 'Artefakte',
  'dashboard.avgMargin': 'Durchschnittsmarge',
  'dashboard.quality': 'Qualität',
  'dashboard.sectorClear': 'Sektor frei',
  'dashboard.continuousSweep': 'Kontinuierlicher Scan',
  'dashboard.inferenceEngines': 'Inferenz-Engines',
  'dashboard.optimizationRate': 'Optimierungsrate',
  'dashboard.telemetryInference': 'Telemetrie-Inferenz',
  'dashboard.driftVariance': 'Drift-Varianz',
  'dashboard.activeIncidents': 'Aktive Störungen',
  'dashboard.noMachinesConfigured': 'Keine Maschinen konfiguriert',
  'dashboard.streamActive': 'Stream-Abonnement aktiv',
  'dashboard.listeningTraces': 'Warte auf Betriebsaktivitäts-Traces...',
  'dashboard.pauseQueue': 'Warteschlangenorchestrierung anhalten',
  'dashboard.pauseBadge': 'Globaler Notstopp',
  'dashboard.resumeQueue': 'Warteschlangenorchestrierung fortsetzen',
  'dashboard.resumeBadge': 'Worker-Knoten wieder aktivieren',
  'preflight.industrialExecution': 'Industrielle Preflight-Ausführung',
  'preflight.dropzoneTitle': 'PDF-Nutzlastblock hierher ziehen oder klicken',
  'preflight.magicByteNotice': 'Erzwingt Magic-Byte-Prüfung',
  'preflight.selectPdfBtn': 'PDF-Datei auswählen',
  'preflight.readyStatus': 'Bereit',
  'preflight.tenantIsolation': 'Mandantenisolation',
  'preflight.policyCatalog': 'Richtlinienkatalog',
  'preflight.policyUnavailable': 'Nicht verfügbar',
  'preflight.executionMode': 'Ausführungsmodus',
  'preflight.modeAnalyze': 'Nur analysieren',
  'preflight.modeAnalyzeDesc': 'Prüft das PDF und erstellt Diagnosedaten. Erzeugt kein korrigiertes PDF.',
  'preflight.modeAutofix': 'Automatische Korrektur',
  'preflight.modeAutofixDesc': 'Versucht das PDF zu reparieren und erzeugt bei Erfolg ein korrigiertes PDF.',
  'preflight.btnExecute': 'Preflight-Auftrag ausführen',
  'preflight.btnProcessing': 'Wird verarbeitet',
  'preflight.btnDispatched': 'Erfolgreich übermittelt',
  'preflight.execFailed': 'Industrielle Preflight-Gateway-Ausführung upstream fehlgeschlagen.',
  'dashboard.stateProcessing': 'In Bearbeitung',
  'dashboard.stateListening': 'Bereit / Überwachend',
  'dashboard.stateStandby': 'Bereitschaft',
  'dashboard.stateActive': 'Aktiv',
  'dashboard.stateOffline': 'Offline',
  'dashboard.stateDegraded': 'Eingeschränkt',
  'dashboard.stateSaturated': 'Ausgelastet',
  'dashboard.stateSecure': 'Sicher',
  'dashboard.stateSynced': 'Synchronisiert',
  'dashboard.stateHealthy': 'Betriebsbereit',
  'dashboard.metricLoad': 'Last',
  'dashboard.metricRisks': 'Risiken',
  'dashboard.metricSync': 'Sync',
  'dashboard.metricActive': 'Aktiv',
  'dashboard.queueStatusActive': 'Aktiv',
  'dashboard.queueStatusWaiting': 'Wartend',
  'dashboard.queueStatusDelayed': 'Verzögert',
  'dashboard.queueStatusFailed': 'Fehlgeschlagen',
  'dashboard.queueStatusCompleted': 'Abgeschlossen',
  // Tooltips & Accessibility Labels
  'topbar.toggleThemeLight': 'Zu hellem Farbschema wechseln',
  'topbar.toggleThemeDark': 'Zu dunklem Farbschema wechseln',
  'topbar.toggleLanguage': 'Sprache wechseln (aktuell: {{lang}})',
  'topbar.notificationsBtn': 'Benachrichtigungen ({{count}} ungelesen)',
  'topbar.notificationsBtnZero': 'Benachrichtigungen',
  'topbar.notificationsTitle': 'Benachrichtigungen',
  'topbar.markAllRead': 'Alle als gelesen markieren',
  'topbar.newBadge': 'neu',
  'sidebar.appSidebar': 'Anwendungsseitenleiste',
  'sidebar.closeMobile': 'Mobile Seitenleiste schließen',
  'settings.appearance.themeDarkTooltip': 'Industrielles dunkles Farbschema für kontrastreiche Arbeitsumgebungen',
  'settings.appearance.themeLightTooltip': 'Helles Unternehmensfarbschema für Büro- und Leitstellenbetrieb',
  'settings.appearance.densityComfortableTooltip': 'Komfortable Dichte mit Standardabständen und Bedienelementen',
  'settings.appearance.densityCompactTooltip': 'Kompakte Dichte optimiert für datenintensive Industrieanzeigen',
  'settings.appearance.animationsTooltip': 'Mikro-Animationen und Übergänge der Benutzeroberfläche umschalten',
  'pricing.workflow.group': 'Auswahl des Preisgestaltungsmodus',
  'pricing.workflow.assistantBtn': 'KI-Preisgestaltungs-Assistent',
  'pricing.workflow.manualBtn': 'Manuelle Tarifkonfiguration',
  'pricing.workflow.priceBooksBtn': 'Kommerzielle Staffelpreise und Kundenpreisbücher',
  'pricing.hawkeye.tooltip': 'Schreibgeschützter kanonischer Preisstatus, repräsentative kalibrierte Anker und Domänenvollständigkeit.',
  'pricing.hawkeye.anchorsTooltip': 'Repräsentative kalibrierte Ankersätze der kanonischen Preismatrix.',
  'pricing.hawkeye.modulesTooltip': 'Status und strukturelle Vollständigkeit je Preiskategorie.',
  'pricing.hawkeye.revisionTooltip': 'Zuletzt erstellte Revision (nicht live durch Checksumme verifiziert)',
  'pricing.action.editMetadata': 'Metadaten bearbeiten',
  'pricing.action.cloneVersion': 'Version klonen',
  'pricing.action.deleteDraft': 'Entwurf löschen',
  'pricing.action.calibrateQuote': 'Aus diesem Angebot kalibrieren',
  'pricing.action.previousSessions': 'Frühere kalibrierte Sitzungen',
  'pricing.action.removeEntry': '{{name}} entfernen',
  'pricing.action.dismissError': 'Fehler verwerfen',
  'setup.help.searchLabel': 'Einstellungen und Hilfedokumentation durchsuchen',
  'setup.help.closeBtn': 'Hilfefenster schließen',
  'setup.tutorial.exitBtn': 'Tutorial beenden',
  'setup.status.completed': 'Abgeschlossen',
  'setup.status.inProgress': 'In Bearbeitung',
  'setup.status.needsAttention': 'Erfordert Aufmerksamkeit',
  'setup.status.prerequisitesRequired': 'Voraussetzungen erforderlich',
  'setup.summary.regionLabel': 'Übersicht über Bereitschaftsdimensionen',
  'dashboard.orders.expectedRevenue': 'Erwarteter Druckerei-Umsatz',
  'dashboard.orders.filterAll': 'Alle Aufträge',
  'dashboard.orders.filterHighProfit': 'Hohe Marge',
  'dashboard.orders.filterUrgent': 'Dringend',
  'dashboard.orders.noOrders': 'Keine Aufträge entsprechen dem aktuellen Filter.',
  'pricing.calibration.currentSpec': 'Aktuelle Spezifikation',
  'pricing.calibration.editFullSpec': 'Vollständige Spezifikation bearbeiten',
  'pricing.calibration.drawerTitle': 'Aktuelle Spezifikation und extrahierte Details',
  'pricing.calibration.drawerSubtitle': 'Vom Assistenten oder der angehängten PDF extrahierte Parameter überprüfen.',
  'pricing.calibration.noSpecsYet': 'Bislang keine Spezifikationen eingegeben.',
  'pricing.calibration.noSpecsHint': 'Laden Sie ein Angebots-PDF hoch oder beschreiben Sie einen Druckauftrag, um zu beginnen.',
  'pricing.action.calibrateQuoteBtn': 'Angebot kalibrieren',
  'pricing.action.calibratedBooks': 'Kalibrierte Bücher',
  'pricing.action.revisions': 'Revisionen',
  'pricing.action.hideAdvanced': 'Erweitert ausblenden',
  'pricing.action.advancedDetails': 'Erweiterte Details',
  'pricing.dropzone.title': 'Angebots-PDF hier ablegen',
  'pricing.dropzone.subtitle': 'oder Dateien auswählen (PDF · max. ~10 MB)',
  'pricing.dropzone.dragOver': 'Loslassen, um Angebots-PDF zu analysieren',
  'pricing.dropzone.browse': 'Dateien durchsuchen',
  'pricing.dropzone.compactTitle': 'Weitere Angebots-PDF anhängen',
  'pricing.dropzone.compactAction': 'Neue PDF hochladen',
  'pricing.example.prompt1': '1.000 Exemplare, 170x240 mm, 128 S. 4/4 auf 80g Offset, 300g Umschlag, Klebebindung für 2.450 €',
  'pricing.example.prompt2': '500 Exemplare A4 210x297 mm, 64 Seiten 4/4 gestrichen 130g, Rückendrahtheftung für 1.200 €',
  'pricing.example.prompt3': 'Hardcover-Fotobuch, 250 Exemplare, 200 S. 4/4 150g gestrichen, Fadenheftung für 4.800 €',
  'pricing.review.extractedData': 'Extrahierte Angebotsdaten',
  'pricing.review.pendingConfirmation': 'Ausstehende Bestätigung',
  'pricing.review.selectedVariant': 'Ausgewähltes Angebot & Variante',
  'pricing.review.noVariantSelected': 'Noch keine Variante ausgewählt',
  'pricing.review.calibrationProposal': 'Kalibrierungsvorschlag',
  'pricing.review.noProposalYet': 'Noch kein Solver-Vorschlag erzeugt',
  'pricing.variant.selectedBadge': 'Ausgewählt',
  'pricing.spec.quantity': 'Auflage:',
  'pricing.spec.copies': 'Exemplare',
  'pricing.spec.trimSize': 'Endformat:',
  'pricing.spec.interiorPages': 'Innenseiten:',
  'pricing.spec.paper': 'Papier:',
  'pricing.spec.binding': 'Bindung:',
  'pricing.review.manufacturingTarget': 'Fertigungsziel:',
  'pricing.review.transportPerKg': 'Transport (€/kg):',
  'pricing.solver.awaitingSolver': 'Warten auf Solver',
  'pricing.solver.predictedPrice': 'Vorhergesagter Preis:',
  'pricing.solver.residual': 'Residuum:',
  'pricing.solver.accepted': 'Akzeptiert',
  'pricing.wizard.step1': 'Auftrag beschreiben',
  'pricing.wizard.step2': 'Prüfen',
  'pricing.wizard.step3': 'Fertigungskosten',
  'pricing.wizard.step4': 'Kalibrieren',
  'pricing.wizard.step5': 'Preise testen',
  'pricing.acceptance.modalTitle': 'Kalibrierungsübernahme bestätigen',
  'pricing.acceptance.modalSubtitle': 'Kalibrierten Tarif auf Produktionsknoten anwenden',
  'pricing.acceptance.targetNode': 'Ziel-Produktionsknoten:',
  'pricing.acceptance.referenceBook': 'Referenzbuch:',
  'pricing.acceptance.declaredTarget': 'Erklärtes Fertigungsziel:',
  'pricing.acceptance.calibratedPrice': 'Kalibrierter Vorwärtspreis:',
  'pricing.acceptance.solverResidual': 'Solver-Residuum:',
  'pricing.acceptance.immutableTitle': 'Erstellung unumstößlicher Preisrevision',
  'pricing.acceptance.immutableDesc': 'Beim Übernehmen wird die Basisintegrität atomar verifiziert, die aktive Tariftabelle des Knoten aktualisiert und eine unumstößliche Revision im Audit-Log eingetragen.',
  'pricing.acceptance.applying': 'Übernahme läuft...',
  'pricing.acceptance.acceptBtn': 'Preisrevision übernehmen',
  'pricing.acceptance.closeModal': 'Dialog schließen',
  'fileTooLargeError': 'Datei überschreitet die Servergrenze (10 MB). Bitte wählen Sie eine kleinere PDF-Datei.',
} as const;

export type TranslationKeys = keyof typeof de;
