export const en = {
  appName: 'PDF Preflight Check',
  dragDropPrompt: 'Drag & drop your PDF here, or click to select file',
  invalidFileType: 'Invalid file type. Please upload a PDF file.',
  loadingFile: 'Loading PDF file...',
  preparingFileForAnalysis: 'Preparing your file for analysis.',
  analyzingPDF: 'Analyzing PDF...',
  thisMayTakeAMoment: 'This may take a moment.',
  runPreflight: 'Run Preflight',
  or: 'or',
  of: 'of',
  browseYourComputer: 'browse your computer',
  pdfMaxHint: 'PDF · max. ~50 MB',
  selectedLabel: 'Selected PDF',
  changeLabel: 'Change',
  uploadTipLargePdf: 'Tip: large PDFs may take a bit longer.',
  uploadYourPdf: 'Upload Your PDF',
  uploadDescription: 'Select a PDF file to begin the preflight check',
  analyzingYourPdf: 'Analyzing Your PDF...',
  analysisComplete: 'Analysis Complete',
  fixIssuesTitle: 'Fix Issues',
  fixIssuesDescription: 'Review and fix the {{count}} issue(s) found in your PDF',
  fixIssuesRemaing: '{{count}} issue(s) remaining',
  reviewAndDownload: 'Review & Download',
  pdfProcessedReady: 'Your print-ready PDF is ready! Review and download below.',
  reviewAndApplyCorrections: 'Review your document and apply corrections if needed.',
  back: '← Back',
  next: 'Next →',
  igniteEngine: 'Ignite V2 Engine',
  fixIssues: 'Fix Issues →',
  continueToReview: 'Continue to Review →',
  startOver: 'Start Over',
  analysisWaitMessage: 'Please wait while we check your document for print readiness',
  issuesFoundMessage: 'Review the items that need attention below',
  pdfLooksGood: 'Great! Your PDF looks good',
  checkingDetails: 'Checking fonts, colors, images, and more...',
  perfectNoIssues: 'Perfect! No issues found',
  readyForPrinting: 'Your PDF is ready for printing',
  readyForPrint: 'Ready for Print!',
  reviewRequired: 'Review Required',
  readyForProduction: 'Ready for Production',
  actionRequired: 'Action Required',
  availableReports: 'Available Reports',
  complianceCertified: 'Compliance Certified',
  txtSummary: 'TXT Summary',
  productionTools: 'Production Tools',
  aiMagicApplied: 'AI Magic Applied!',
  aiMagicDescription: 'Our AI Wizard has automatically optimized your colors, resolution, and margins for professional printing.',
  processedSuccessfully: 'Document processed successfully{{count, plural, =0 {} other { ({{count}} issue(s) addressed)}}}',
  issuesSummary: 'Issues Summary',
  overallScore: 'Overall Score',
  issueCategories: 'Issue Categories',
  fileLabel: 'File',
  downloadReport: 'Download Report',
  downloadOriginal: 'Download Original',
  reanalyzePdf: '🔄 Re-analyze PDF',
  pdfViewer: 'PDF Viewer',
  pageNavigation: 'Page Navigation',
  prevPage: 'Previous Page',
  nextPage: 'Next Page',
  goToPage: 'Go to page',
  typePageNumber: 'Type page number',
  heatmap: 'Heatmap',
  aiVisualCheck: 'AI Visual Check',
  toggleTacHeatmap: 'Toggle TAC Heatmap (Total Area Coverage)',
  aiVisualQualityCheck: 'AI Visual Quality Check',
  analyzingInk: 'Analyzing Ink...',
  tacLessThan280: '<280%',
  tac280to300: '280-300%',
  tacMoreThan300: '>300%',
  severity: 'Severity',
  page: 'Page',
  documentWide: 'Document-wide',
  message: 'Message',
  details: 'Details',
  close: 'Close',
  error: 'Error',
  noPdfLoaded: 'No PDF loaded. Please upload a file to begin.',
  noIssuesToDisplay: 'No issues to display.',
  noIssuesFound: 'No issues found. Your PDF looks perfect!',
  noIssues: 'No issues',
  noIssuesPdf: 'No issues found in your PDF',
  totalIssues: 'total issues',
  issuesFoundApplyOrDownload: '{{count}} issue(s) found - apply corrections or download the original file',
  issuesFound: 'Issues Found',
  issues: 'Issues',
  errors: 'Errors',
  warnings: 'Warnings',
  info: 'Info',
  errAbbr: 'err',
  warnAbbr: 'warn',
  infoAbbr: 'info',
  selectAnIssue: 'Select an issue to view its details and potential fixes.',
  selectedIssueDetails: 'Selected Issue Details',
  currentIssue: 'Current Issue',
  categoryImages: 'Images',
  categoryColor: 'Color Spaces',
  categoryFonts: 'Fonts',
  categoryMetadata: 'Metadata',
  categoryTransparency: 'Transparency',
  categoryBleedMargins: 'Bleed & Margins',
  categoryResolution: 'Resolution',
  categoryCompliance: 'Compliance',
  categoryPageSetup: 'Page setup',
  categoryAnnotations: 'Annotations',
  categoryFormFields: 'Form fields',
  categoryMultimedia: 'Multimedia',
  categoryLayers: 'Layers',
  categoryOther: 'Other',
  quickFixes: 'Quick Fixes',
  aiAssistance: 'AI Assistance',
  add3mmBleed: '🔧 Add 3mm Bleed',
  convertToCMYK: '🎨 Convert to CMYK',
  convertToGrayscaleBtn: '⚫ Convert to Grayscale',
  rebuildHighRes300dpi: '🛠️ Rebuild High-Res (300 DPI)',
  converting: 'Converting...',
  fixing: 'Fixing...',
  cmykProfile: 'CMYK Profile:',
  genericCMYK: 'Generic CMYK',
  coatedFogra39: 'Coated FOGRA39 (ISO 12647-2:2004)',
  coatedFogra51: 'ISO Coated v3 (FOGRA51) - Modern Standard',
  uncoatedFogra52: 'PSO Uncoated v3 (FOGRA52)',
  gracol2006: 'GRACoL 2006 (Coated #1)',
  swop2006: 'SWOP 2006 (Coated #3)',
  uncoatedFogra29: 'Uncoated FOGRA29',
  bleedSafe: 'Safe (Box-only / Canvas)',
  bleedAggressive: 'Aggressive (Scale-fill)',
  bleedMode: 'Bleed Mode:',
  bleedSafeHint: 'Safe mode adds margin without stretching. Border may appear white. Note: Interactive elements (links/annotations) might not be preserved.',
  optionalTools: 'Optional Tools',
  additionalProcessingOptions: 'Additional processing options',
  convertToGrayscale: 'Convert to Grayscale',
  convertColorsToCMYK: 'Convert Colors to CMYK',
  rebuildPdfHighRes: 'Rebuild PDF (High-Res)',
  createBooklet: 'Create Booklet',
  downloadProcessedPdf: 'Download Processed PDF',
  stepNumber: 'Step {{number}}',
  uploadPdf: 'Upload PDF',
  analysis: 'Analysis',
  review: 'Review',
  explainSuggestFix: 'Explain & Suggest Fix (AI Audit)',
  explainAndSuggestFix: 'Explain & Suggest Fix (AI Audit)',
  getEfficiencyTips: 'Get Efficiency Tips (AI Audit)',
  aiAuditTitle: 'AI Audit: Explain & Suggest Fixes',
  efficiencyAuditTitle: 'AI Audit: Get Efficiency Tips',
  fetchingAIResponse: 'Fetching AI response...',
  aiResponse: 'AI Response',
  aiError: 'Failed to fetch AI response. Please check your API key and try again.',
  geminiKeyMissingError: 'Gemini API key is missing or invalid. AI features are disabled.',
  billingDocLink: 'See billing documentation',
  visualMode: 'Visual Mode',
  fastestFix: 'Fastest Fix',
  bestFix: 'Best Fix',
  timeImpact: 'Time Impact',
  costImpact: 'Cost Impact',
  aiDescriptionExplain: 'Get a detailed explanation of this issue and step-by-step suggestions on how to fix it, including specific instructions for common tools like Adobe InDesign or Acrobat.',
  aiDescriptionEfficiency: 'Discover the most efficient ways to resolve this issue. Compare the fastest fix with the best-quality fix, and understand their potential time and cost impacts.',
  pageLabel: 'Page {{page}}',
  suggestedFix: 'Suggested fix',
  issueSummary: 'Issue Summary',
  engineHint: 'Engine Hint',
  drawerActions: 'Actions',
  actions: 'Actions',
  severityError: 'Error',
  severityWarning: 'Warning',
  severityInfo: 'Info',
  issue: 'Issue',
  aiHintInDrawer: 'Use the AI buttons to get a detailed explanation or efficiency tips for this issue.',
  aiMagicFix: 'AI Magic Fix',
  aiMagicFixDesc: 'One click. We handle everything automatically.',
  manualMode: 'Manual',
  manualModeDesc: 'For advanced users who want to review issues and choose fixes.',
  recommended: 'Recommended',
  bestWithAi: 'Best with AI Magic Fix',
  readyForAnalysis: 'Ready for analysis',
  browseFiles: 'Browse files',
  processingTime: 'Processing time',
  processingTimeVal: '~10-60 seconds',
  pdfLimit: 'PDF up to 50 MB',
  magicWait: 'Wait for the magic to happen',
  dragAndDropModern: 'Drag & drop your PDF',
  changeFile: 'Change selected file',
  safeProcessing: 'Safe & temporary processing',
  continue: 'Continue',
  headerUploadTitle: 'Upload your PDF',
  headerUploadSubset: 'Choose AI Magic Fix (recommended) or Manual.',
  chooseWorkflow: 'Choose workflow',
  recommendMagicHint: 'We recommend Magic Fix for most users.',
  uploadToContinue: 'Upload a PDF to continue.',
  magicPoint1: 'Fixes the most common print problems',
  magicPoint2: 'Produces a print-ready PDF you can download',
  magicPoint3: 'No technical knowledge required',
  tempProcessNote: 'We process your file temporarily and clean it up automatically.',
  manualControlTip: 'FULL CONTROL OVER INDIVIDUAL FIXES AND COLOR PROFILES.',
  serverUnavailable: 'SERVER CONNECTION REQUIRED',
  serverUnavailableDesc: 'Color conversion (CMYK/Gray) and Magic Fix are currently unavailable. Please check your internet connection or try again later.',
  retry: 'Retry / Reload',
  profileLabel: 'Profile:',
  outputIntentLabel: 'OutputIntent:',
  bleedLabel: 'Bleed:',
  standardDpiLabel: 'Standard DPI:',
  verified: 'Verified ✅',
  embedded: 'Embedded',
  real3mmBox: 'Real 3mm (Box Geometry)',
  highEndPrint: '300 (High-End Print)',
  technicalNoteTitle: 'Prepress Technical Note',
  technicalNoteDesc: 'This document has been professionally optimized for prepress production.',
  outputIntentExplain: 'A valid PDF/X OutputIntent (GTS_PDFX) has been embedded to guarantee color consistency across professional RIP software.',
  bypassExplain: 'No color conversion was applied to existing compliant objects because they already matched the requested profile.',
  rewriteExplain: 'The file has been structurally stabilized using Ghostscript pdfwrite to ensure font embedding and xref integrity.',
  negativeStatement: 'No further color transformations were performed after OutputIntent finalization.',
  closeNote: 'Close Note',
  complianceSummaryTitle: 'Prepress Compliance Summary',
  labelCertificateId: 'Certificate ID:',
  labelEngineVersion: 'Engine Version:',
  labelRiskLevel: 'Risk Level:',
  labelOutputIntent: 'Output Intent:',
  labelStructure: 'Structure:',
  labelConversion: 'CMYK Conversion:',
  labelProcessing: 'Processing:',
  labelTransparency: 'Transparency:',
  labelBleed: 'Bleed:',
  statusVerified: 'Verified (GTS_PDFX)',
  statusSkipped: 'Skipped (Compliant)',
  statusStabilized: 'Stabilized via Rewrite',
  statusPreserved: 'Preserved',
  statusApplied: 'Applied',
  riskGreen: 'GREEN (Safe for Production)',
  riskAttention: 'ATTENTION (Review Required)',
  riskBlocking: 'BLOCKING (Rejected by Preflight)',
  labelInkCoverage: 'Ink Coverage (TAC):',
  labelMaxTac: 'Max. Ink Density:',
  labelWorstPage: 'Worst Page:',
  labelTacLimit: 'Density Limit:',
  tacWarningDrying: 'Ink density may cause drying or setoff issues on press.',
  tacVerified: 'Verified within limits',
  labelOverprint: 'Black Overprint:',
  statusOverprintOk: 'Verified ✅',
  statusOverprintRisk: 'Knockout Risk',
  overprintWarningKnockout: 'Black text may knock out underlying inks, causing halos or misregistration.',
  overprintWarningRegistration: 'Registration color (100% CMYK) detected in artwork, which can cause artifacts.',
  overprintWarningRichBlack: 'Rich black text detected in small font sizes; some presses recommend K-only for sharpness.',
  spotTitle: 'Spot Color Policy',
  spotLabelDetected: 'Spot Colors:',
  spotLabelPolicy: 'Policy:',
  spotStatusNone: 'NONE',
  spotPolicyStrict: 'Strict CMYK (Offset)',
  spotPolicyConvert: 'Convert to CMYK (Digital)',
  spotRiskGreen: 'GREEN',
  spotRiskAttention: 'ATTENTION',
  spotRiskBlocking: 'BLOCKING',
  spotWarnWhitelistOnly: 'Only technical spot colors detected (printer whitelist).',
  spotWarnNonWhitelist: 'Non-whitelisted spot colors detected for this profile.',
  spotNoteTacIncluded: 'Spots are included in the TAC estimate (spot-to-CMYK conversion).',
  spotNoteRegistration: 'Registration color detected (/All or /Registration); forbidden in artwork.',
  spotNoteSpotsInText: 'Spot colors detected in text; conversion may affect typographic sharpness.',
  bleedMethod: 'Bleed Method:',
  bleedMethodScale: 'Centered Scaling (V3)',
  bleedMethodBox: 'Box Adjustment (Real Margin)',
  bleedScaleWarning: 'Aggressive scaling detected (>4%). Safety margins are compressed.',
  'admin.title': 'Admin Control Center',
  'admin.subtitle': 'SRE COCKPIT & SYSTEM HEALTH',
  'admin.range.24h': 'Last 24 Hours',
  'admin.range.7d': 'Last 7 Days',
  'admin.range.30d': 'Last 30 Days',
  'admin.refresh.off': 'Manual Refresh',
  'admin.tabs.overview': 'Overview',
  'admin.tabs.tenants': 'Tenants',
  'admin.tenants.tenant': 'Tenant Identity',
  'admin.tenants.total': 'Traffic Volume',
  'admin.tenants.success': 'Reliability',
  'admin.tenants.latency': 'Sync Latency',
  'admin.tenants.last': 'Last Pulse',
  'admin.tabs.jobs': 'Jobs',
  'admin.tabs.errors': 'Errors',
  'admin.tabs.audit': 'Audit Log',
  'admin.tabs.controls': 'Controls ⚠️',
  'admin.kpi.totalJobs': 'Total Jobs',
  'admin.kpi.successRate': 'Success Rate',
  'admin.kpi.avgLatency': 'Avg Latency',
  'admin.kpi.deltaRate': 'Delta Improvement',
  'admin.kpi.costProxy': 'Cost Proxy',
  'admin.kpi.p95Latency': 'P95 Latency',
  'admin.kpi.queueBacklog': 'Queue Backlog',
  'admin.kpi.oldestAge': 'Oldest Job Age',
  'admin.queue.title': 'Queue Performance Matrix',
  'admin.jobs.filterTenant': 'Filter by Tenant ID...',
  'admin.jobs.filterType': 'Filter by Process Type...',
  'admin.jobs.all': 'All Statuses',
  'admin.jobs.empty': 'No transactions found',
  'admin.audit.filterTenant': 'Search audit logs...',
  'admin.audit.empty': 'No audit events found',
  'admin.errors.code': 'Fault Code',
  'admin.errors.count': 'Stack Count',
  'admin.errors.lastSeen': 'Last Observed',
  'common.loading': 'Loading sequence...',
  'common.na': 'N/A',
  partialCalculationTitle: 'Partial calculation: incomplete rates',
  governedQuoteIncompleteRatesNotice: 'This simulation does not constitute a valid commercial price due to missing or uncalibrated manufacturing rates on the node:',
  reviewCardIncompleteRatesNotice: 'This quote is not presented as a valid commercial price due to missing or uncalibrated manufacturing rates:',
  realQuotationOutcome: 'Real Quotation Outcome',
  diagnosticOutcome: 'Diagnostic Outcome',
  customerPriceBeforeTax: 'Customer Price (Before Tax)',
  partialDiagnosticSubtotalTitle: 'Partial Diagnostic Subtotal (Incomplete Rates)',
  partialDiagnosticSubtotalBadge: 'Partial Diagnostic Subtotal',
  perCopyNet: '€ {{price}} / copy (Net)',
  chatInputPlaceholder: 'Describe your book or attach a PDF…',
  attachPdfTooltip: 'Attach a PDF',
  pdfOnlyError: 'Only PDF documents are supported.',
  uploadingQuote: 'Uploading quote document…',
  selectThisVariant: 'Select this variant',
  analyzingPdfDocument: 'Analyzing PDF…',
  pdfDetectedLanguage: 'Document detected: {{language}}',
  pdfExtractionComplete: 'Extraction complete. Quote ready for review.',
  pdfUploadErrorMessage: 'Error processing quote PDF.',
  pdfUploadedUserMsg: '[Uploaded PDF]: {{filename}}',
  'onboarding.title': 'Printhouse Setup',
  'onboarding.subtitle': 'Configure your printing plant, machinery, paper and pricing with intelligent guidance.',
  'onboarding.sections': 'Setup Sections',
  'onboarding.findSettingOrHelp': 'Find a setting or get help...',
  'onboarding.guideMe': 'Guide Me',
  'onboarding.continueSetup': 'Continue Setup',
  'onboarding.setupOverview': 'Overview & Readiness',
  'onboarding.activeModule': 'Active Module',
  'onboarding.nextAction': 'Recommended Action',
  'onboarding.saveChanges': 'Save Changes',
  'onboarding.unsavedChangesWarning': 'You have unsaved changes. Leaving this section will discard them. Do you want to proceed?',
  'onboarding.collapseSidebar': 'Collapse sidebar',
  'onboarding.expandSidebar': 'Expand sidebar',
  'onboarding.reviewDetails': 'Review Details',
  'onboarding.quickSpecs': 'Quick Specifications',
  'onboarding.mode.assistant': 'AI assistant',
  'onboarding.mode.manual': 'Manual rate cards',
  'onboarding.mode.descAssistant': 'Describe a job or upload a quote PDF. The assistant extracts specifications for guided calibration.',
  'onboarding.mode.descManual': 'Directly edit industrial rate cards: base rates, make-ready, click rates, paper and binding costs.',
  'onboarding.startOption.upload': 'Upload quote or job ticket PDF',
  'onboarding.startOption.uploadDesc': 'Upload a PDF quote or job ticket to automatically extract book specs and price points.',
  'onboarding.startOption.describe': 'Describe a product',
  'onboarding.startOption.describeDesc': 'Tell the assistant about a book you previously produced in plain language.',
  'onboarding.startOption.manual': 'Enter product specifications manually',
  'onboarding.startOption.manualDesc': 'Open the manual specification and rate cards editor to fill values directly.',
  'onboarding.tutorial.stepOf': 'Step {{current}} of {{total}}',
  'onboarding.tutorial.next': 'Next',
  'onboarding.tutorial.back': 'Back',
  'onboarding.tutorial.exit': 'Exit Tutorial',
  'onboarding.tutorial.doThisNow': 'Do this now',
  'onboarding.help.searchPlaceholder': 'Search settings, modules, terms (e.g. Munken, CMYK, VAT, transport)...',
  'onboarding.help.noResults': 'No matching settings or help topics found.',
  'onboarding.help.tip': 'Press Esc to close, ↑↓ to navigate, Enter to select.',
  'pricing.assistant.title': 'Pricing Assistant',
  'pricing.assistant.header': 'Multilingual Pricing Assistant',
  'pricing.assistant.subtitle': 'Describe a produced book or attach a PDF quote document.',
  'pricing.assistant.headerTag': 'Multilingual PDF Intake & Calibration',
  'pricing.assistant.inspectEvidence': 'Inspect Evidence',
  'pricing.assistant.busyTitle': 'AI assistant is busy right now',
  'pricing.assistant.busyDesc': 'Your setup is safe and nothing has been saved. You can try again or enter the job details manually.',
  'pricing.assistant.orExample': 'Or try an example prompt:',
  'pricing.assistant.analyzing': 'Analyzing specifications...',
  'pricing.assistant.proposedTitle': 'Proposed Book Updates Ready',
  'pricing.assistant.requiresConfirmation': 'Requires Confirmation',
  'pricing.assistant.proposedDesc': 'The assistant extracted details from your message. Review the structured summary on the right and confirm to apply.',
  'pricing.assistant.applyBtn': 'Apply Extracted Details',
  'pricing.assistant.sendBtn': 'Send',
  'pricing.assistant.retryBtn': 'Retry',
  'pricing.assistant.drawerTitle': 'Quote Evidence & Variant Details',
  'pricing.assistant.drawerSubtitle': 'Detailed breakdown of active document and selected commercial offer',
  'pricing.assistant.activeExtractedDoc': 'Active Extracted Document',
  'pricing.assistant.fileLabel': 'File:',
  'pricing.assistant.evidenceIdLabel': 'Evidence ID:',
  'pricing.assistant.languageLabel': 'Language:',
  'pricing.assistant.pageCountLabel': 'PDF Page Count:',
  'pricing.assistant.printhouseLabel': 'Printhouse:',
  'pricing.assistant.selectedOfferTitle': 'Selected Offer',
  'pricing.assistant.quantityLabel': 'Quantity:',
  'pricing.assistant.manufacturingLabel': 'Manufacturing:',
  'pricing.assistant.transportLabel': 'Transport:',
  'pricing.assistant.quotedTotalLabel': 'Quoted Total:',
  'pricing.assistant.quotedUnitLabel': 'Quoted Unit Price:',
  'pricing.assistant.validationLabel': 'Validation:',
  'pricing.assistant.sourceTextLabel': 'Source text:',
  'pricing.assistant.noOfferSelected': 'No specific offer variant selected yet.',
  'pricing.assistant.noEvidenceAttached': 'No quote evidence document is currently attached.',
  'pricing.assistant.physicalSpecs': 'Extracted Physical Specifications',
  'pricing.assistant.formatLabel': 'Format:',
  'pricing.assistant.bindingLabel': 'Binding:',
  'pricing.assistant.finishingLabel': 'Finishing:',
  'pricing.assistant.interiorPagesLabel': 'Product Interior Pages:',
  'quoteReview.pagesExtracted': '{{count}} page(s) extracted',
  'quoteReview.optionLabel': 'Option {{idx}}: €{{price}} (Manufacturing)',
  'quoteReview.unitsLabel': '{{count}} units',
  'quoteReview.consistent': '✓ Correct',
  'quoteReview.inconsistent': '⚠ Inconsistency Detected',
  'quoteReview.readyForCalibration': 'Ready for Calibration Review',
  'quoteReview.productTitle': 'Product Title',
  'quoteReview.formatAndBinding': 'Format & Binding',
  'quoteReview.variantsForCopies': 'Extracted Commercial Offer Variants for {{copies}} copies ({{count}} variants)',
  'quoteReview.quantitiesAndPrices': 'Extracted Commercial Quantities & Prices ({{count}})',
  'quoteReview.mfgOffered': 'Offered Manufacturing Price:',
  'quoteReview.transportSep': 'Separate Transport:',
  'quoteReview.notSpecified': 'Not specified',
  'quoteReview.totalOffered': 'Total Offered by Vendor:',
  'quoteReview.unitOffered': 'Offered Unit Price:',
  'quoteReview.vendorDisclaimer': 'Price quoted by vendor • Internal cost calculated upon calibration',
  'quoteReview.selectVariantBtn': 'Select variant (€{{price}})',
  'quoteReview.unitPriceDiffWarning': 'Indicated unit price (€{{quoted}}) differs from calculated total divided by quantity (€{{computed}}).',
  'quoteReview.showOriginalText': 'Show original text & normalized canonical terms',
  'quoteReview.hideDetails': 'Hide details',
  'quoteReview.normalizedTerms': 'Normalized Terms:',
  'quoteReview.rawExtractedText': 'Raw Extracted Text:',
  'quoteReview.noneDetected': 'None detected',
  'quoteReview.editInterpretation': 'Edit Interpretation',
  'quoteReview.saveCorrections': 'Save Corrections',
  'quoteReview.saving': 'Saving...',
  'quoteReview.ignoreDocument': 'Ignore Document',
  'quoteReview.markValidOffersReady': 'Mark Valid Offers Ready for Calibration',
  'quoteReview.docIgnored': 'Document {{filename}} ignored.',
  'pricing.mode.assistant': 'AI assistant',
  'pricing.mode.manual': 'Manual rate cards',
  'pricing.mode.priceBooks': 'Price Books',
  'pricing.mode.node': 'Node:',
  'pricing.mode.manualHeading': 'Industrial Manufacturing Cost & Rate Cards',
  'setup.summary.account': '1. Account & Sites',
  'setup.summary.production': '2. Production Readiness',
  'setup.summary.pricing': '3. Industrial Pricing',
  'setup.summary.coreStatus': 'Core Setup Status',
  'setup.summary.status': 'Status:',
  'setup.summary.configured': 'Configured',
  'setup.summary.inProgress': 'In Progress',
  'setup.summary.notStarted': 'Not Started',
  'setup.summary.complete': 'SETUP COMPLETE',
  'setup.summary.incomplete': 'SETUP INCOMPLETE',
  'setup.summary.readyDesc': 'Ready for dashboard & marketplace review',
  'setup.summary.incompleteDesc': 'Complete 8 modules below',
  'setup.tabs.overview': 'Setup Overview',
  'setup.tabs.company': 'Company Profile',
  'setup.tabs.sites': 'Production Sites',
  'setup.tabs.machines': 'Machinery Fleet',
  'setup.tabs.capabilities': 'Machine Capabilities',
  'setup.tabs.materials': 'Materials & Paper',
  'setup.tabs.capacity': 'Production Capacity',
  'setup.tabs.leadTimes': 'Lead Times & SLAs',
  'setup.tabs.pricing': 'Industrial Pricing',
  'setup.tabs.shipping': 'Shipping & Logistics',
  'setup.tabs.integrations': 'Integrations & Webhooks',
  'setup.tabs.marketplace': 'Marketplace Review',
  'setup.tabs.completeBadge': 'Complete',
  'tutorial.step1.title': 'Printhouse Setup Sections Switcher',
  'tutorial.step1.desc': 'Easily navigate between all 8 setup modules (Company Profile, Fleet, Materials, Pricing, and more) or review your overall setup status from this top toolbar control.',
  'tutorial.step1.action': 'Sections Menu',
  'tutorial.step2.title': 'AI Pricing Calibration Assistant',
  'tutorial.step2.desc': 'Our primary pricing experience. Simply describe a previously produced book or upload a quote PDF, and Hawkeye will solve and calibrate your production rate cards.',
  'tutorial.step2.action': 'Open Pricing Assistant',
  'tutorial.step3.title': 'Instant Manual Mode Toggle',
  'tutorial.step3.desc': 'Prefer traditional spreadsheet rate cards? Switch to Manual anytime with one click. Your draft changes, attached quotes, and calculations remain intact.',
  'tutorial.step3.action': 'Inspect Mode Toggle',
  'tutorial.step4.title': 'Find Settings & Get Help',
  'tutorial.step4.desc': 'Search for any printing term, substrate name, or configuration setting quickly without guessing where it lives.',
  'tutorial.step4.action': 'Open Help Search',
  'setup.overview.modulesHeading': 'Operational Modules (8 Steps)',
  'setup.overview.module1.title': '1. Company Profile',
  'setup.overview.module1.desc': 'Legal company identity, primary country, tax/VAT identifier, and administrative contact.',
  'setup.overview.module2.title': '2. Production Sites',
  'setup.overview.module2.desc': 'Physical printing plants, operating addresses, city location, and facility timezone.',
  'setup.overview.module3.title': '3. Machinery Fleet',
  'setup.overview.module3.desc': 'Offset presses, digital devices, cutting tables, binders, and finishing equipment.',
  'setup.overview.module4.title': '4. Machine Capabilities',
  'setup.overview.module4.desc': 'Color management (CMYK, Spot UV, White Ink), maximum sheet dimensions, and PDF/X specs.',
  'setup.overview.module5.title': '5. Materials & Substrates',
  'setup.overview.module5.desc': 'Substrate catalog, paper grammages, sheet sizes, and finishing compatibility.',
  'setup.overview.module6.title': '6. Production Capacity',
  'setup.overview.module6.desc': 'Daily throughput constraints, shift schedules, working calendar, and job allocations.',
  'setup.overview.module7.title': '7. Lead Times',
  'setup.overview.module7.desc': 'Site-level daily cut-off times, timezone cut-offs, turnaround SLAs, and completion schedules.',
  'setup.overview.module8.title': '8. Industrial Pricing',
  'setup.overview.module8.desc': 'Base manufacturing rates, paper kg costs, binding operations, and transport rates.',
  'setup.module.cta.review': 'Review / Edit',
  'setup.module.cta.continue': 'Continue Setup',
  'setup.module.cta.start': 'Start Setup',
  'setup.module.missingRequirements': 'Missing Requirements:',
  'setup.module.requiresSites': 'Requires at least 1 Production Site',
  'setup.module.requiresMachines': 'Requires at least 1 Machine',
  'setup.nextStep.company': 'Required legal identity and VAT data for invoicing',
  'setup.nextStep.sites': 'At least one operating plant is required to configure presses',
  'setup.nextStep.machines': 'Presses and finishing lines are needed to verify printing capabilities',
  'setup.nextStep.capabilities': 'Defines supported sheet formats, colors and binding',
  'setup.nextStep.materials': 'Required substrate grammages and paper catalog',
  'setup.nextStep.pricing': 'Calibrate manufacturing rates to generate commercial quotes',
  'setup.nextStep.marketplace': 'All operational requirements complete. Finalize marketplace readiness.',
  'setup.error.retryLoading': 'Retry Loading',
  'settings.title': 'Global Settings',
  'settings.subtitle': 'Platform configuration, tenant profile and operator preferences.',
  'settings.nav.general': 'General',
  'settings.nav.notifications': 'Notifications',
  'settings.nav.security': 'Security',
  'settings.nav.integrations': 'Integrations',
  'settings.nav.appearance': 'Appearance',
  'settings.general.title': 'General Settings',
  'settings.general.desc': 'Personal preferences and tenant organizational parameters.',
  'settings.general.personalSection': 'Personal & Regional Preferences',
  'settings.general.tenantSection': 'Printhouse Tenant Profile',
  'settings.general.language': 'Interface Language',
  'settings.general.timezone': 'Timezone',
  'settings.general.region': 'Cloud Infrastructure Region',
  'settings.general.regionNotice': 'Primary EU Sovereign Cloud Node (Managed)',
  'settings.general.companyName': 'Company Legal Name',
  'settings.general.taxId': 'VAT / Tax ID',
  'settings.general.country': 'Country of Operation',
  'settings.general.address': 'Headquarters Address',
  'settings.general.currency': 'Commercial Calculation Currency',
  'settings.appearance.title': 'Appearance & Display',
  'settings.appearance.desc': 'Theme mode, layout density, and interface motion preferences.',
  'settings.appearance.theme': 'Color Scheme',
  'settings.appearance.dark': 'Industrial Dark',
  'settings.appearance.light': 'Corporate Light',
  'settings.appearance.density': 'UI Density',
  'settings.appearance.densityDesc': 'Adjust padding and row height across tables, forms and views.',
  'settings.appearance.comfortable': 'Comfortable',
  'settings.appearance.compact': 'Compact (High Density)',
  'settings.appearance.animations': 'Interface Animations',
  'settings.appearance.animationsDesc': 'Enable smooth transitions. System prefers-reduced-motion is respected automatically.',
  'settings.notifications.title': 'Event Notifications',
  'settings.notifications.desc': 'Manage operational subscriptions and alert channels for your tenant and role.',
  'settings.notifications.email': 'Notification Recipient Email',
  'settings.notifications.roleNoticePrinthouse': 'Scope: Printhouse Operator. Showing factory operations & manufacturing dispatches only.',
  'settings.notifications.roleNoticeSuperadmin': 'Scope: Super Administrator. Platform health, anomaly detection, and deployment events unlocked.',
  'settings.notifications.eventJobDispatch': 'New Manufacturing Dispatch',
  'settings.notifications.eventJobDispatchDesc': 'Alert when an approved print order is dispatched to this plant.',
  'settings.notifications.eventPreflightFail': 'Preflight Failure / Critical Issue',
  'settings.notifications.eventPreflightFailDesc': 'Immediate alert when incoming artwork fails PDF/X verification.',
  'settings.notifications.eventSlaWarning': 'SLA & Cut-off Warning',
  'settings.notifications.eventSlaWarningDesc': 'Alert when production lead time approaches site deadline.',
  'settings.notifications.eventPlatformAnomalies': 'Platform Anomaly Detection (Superadmin)',
  'settings.notifications.eventPlatformAnomaliesDesc': 'Intelligence layer alerts for latency spikes or distributed circuit-breaker triggers.',
  'settings.notifications.eventDeployments': 'Infrastructure Deployment Events (Superadmin)',
  'settings.notifications.eventDeploymentsDesc': 'Notifies on canary rollouts, migrations, and federation mesh updates.',
  'settings.security.title': 'Security & Access Control',
  'settings.security.desc': 'Session lifetime, authentication hardening, and tenant-scoped audit logging.',
  'settings.security.sessionTimeout': 'Inactivity Timeout (minutes)',
  'settings.security.sessionTimeoutDesc': 'Client session will terminate automatically upon user inactivity. Capped by server token lifetime.',
  'settings.security.mfa': 'Two-Factor Authentication (2FA / TOTP)',
  'settings.security.mfaStatusDisabled': 'Disabled (Enrollment Required)',
  'settings.security.mfaStatusActive': 'Active (Authenticator App Protected)',
  'settings.security.mfaSetupBtn': 'Setup Authenticator App',
  'settings.security.mfaDisableBtn': 'Disable 2FA',
  'settings.security.mfaModalSetupTitle': 'Setup Two-Factor Authentication',
  'settings.security.mfaSecretLabel': 'Secret Key (Manual Entry)',
  'settings.security.mfaRecoveryCodesLabel': 'Recovery Codes (Save these securely — shown only once)',
  'settings.security.mfaCodePrompt': 'Enter 6-digit code from authenticator app',
  'settings.security.mfaConfirmBtn': 'Verify and Activate',
  'settings.security.mfaDisableTitle': 'Disable Two-Factor Authentication',
  'settings.security.mfaPasswordPrompt': 'Enter your password to confirm deactivation',
  'settings.security.mfaDisableConfirmBtn': 'Confirm Deactivation',
  'settings.security.sessionsTitle': 'Active User Sessions',
  'settings.security.sessionsDesc': 'Track authorized devices and revoke access across all locations.',
  'settings.security.sessionCurrent': 'CURRENT SESSION',
  'settings.security.sessionRevoke': 'Revoke',
  'settings.security.sessionRevokeAll': 'Revoke All Other Sessions',
  'settings.security.sessionIp': 'IP Address',
  'settings.security.sessionAgent': 'Device / Agent',
  'settings.security.sessionCreated': 'Signed In',
  'settings.security.sessionLastActive': 'Last Active',
  'settings.security.sessionRevokedSuccess': 'Session revoked successfully.',
  'settings.security.sessionRevokeAllSuccess': 'All other sessions have been revoked.',
  'settings.security.auditLog': 'Audit Trail Explorer',
  'settings.security.auditLogDesc': 'Live immutable log of operational actions for this tenant.',
  'settings.security.auditEmpty': 'No audit records for this tenant yet.',
  'settings.integrations.title': 'Connectors & Webhooks',
  'settings.integrations.desc': 'Industrial MIS/ERP bridges, JDF/JMF shopfloor automation and outward webhooks.',
  'settings.integrations.webhookUrl': 'Production Dispatch Webhook URL',
  'settings.integrations.webhookSecret': 'Webhook Signing Secret',
  'settings.integrations.webhookSecretHint': 'Payloads are signed via HMAC-SHA256 in header X-PPOS-Signature.',
  'settings.integrations.rotateSecretBtn': 'Rotate Secret',
  'settings.integrations.rotateSecretSuccess': 'Webhook signing secret rotated.',
  'settings.integrations.testWebhookBtn': 'Enqueue Test Webhook',
  'settings.integrations.testPayloadSuccess': 'Test payload enqueued into outbox.',
  'settings.integrations.webhookSubscriptionsTitle': 'Active Webhook Subscriptions',
  'settings.integrations.recentDeliveriesTitle': 'Recent Webhook Outbox Deliveries',
  'settings.integrations.resendBtn': 'Redeliver',
  'settings.integrations.slackTitle': 'Slack Operational Alerts',
  'settings.integrations.slackToggle': 'Slack Alerts Channel',
  'settings.integrations.slackDesc': 'Send high-priority manufacturing alerts to your operations channel.',
  'settings.integrations.slackWebhook': 'Slack Incoming Webhook URL',
  'settings.integrations.slackChannel': 'Channel Name',
  'settings.integrations.slackTestBtn': 'Send Test Alert',
  'settings.integrations.slackTestSuccess': 'Slack test alert delivered successfully.',
  'settings.integrations.slackSaved': 'Slack integration configuration saved.',
  'settings.integrations.connectorsTitle': 'Industrial MES / Shopfloor Connectors',
  'settings.integrations.statusActive': 'Connected',
  'settings.integrations.statusPending': 'Requires Credentials',
  'settings.integrations.statusRoadmap': 'Catalog Connector',
  'settings.save': 'Save Changes',
  'settings.saving': 'Saving configuration...',
  'settings.saved': 'Changes Saved',
  'settings.error': 'Failed to save settings. Please retry.',
  'settings.savedLocalOnly': 'Preferences saved locally. Backend profile sync pending or offline.',
  'settings.savedProfileOnly': 'Profile saved. Notification preferences sync pending or offline.',
  'settings.notifications.saveFailed': 'Notification preferences could not be updated on server.',
  'settings.security.mfaStatusPending': 'MFA Not Configured',
  'settings.security.mfaDetailsBtn': 'Configure 2FA',
  'settings.security.openForensics': 'Open Forensics Explorer →',
  'settings.security.loadingAudit': 'Loading tenant audit log...',
  'settings.security.mfaModalTitle': 'Two-Factor Authentication Setup',
  'settings.security.mfaModalStatus': 'Scan the QR code or enter the secret key into your authenticator app.',
  'settings.security.mfaModalArchitecture': 'Industrial Security Guidelines:',
  'settings.security.mfaModalWebAuthn': 'FIDO2 / WebAuthn hardware security keys supported for shopfloor terminals.',
  'settings.security.mfaModalTotp': 'RFC 6238 TOTP authenticator application backup protocol.',
  'settings.security.mfaModalIsolation': 'Tenant-isolated cryptographic salt and biometric enforcement per seat.',
  'settings.security.mfaCloseBtn': 'Close',
  'settings.integrations.testPayloadUnavailable': 'Live webhook dispatch gateway not active in this environment.',
  'settings.integrations.slackPendingNotice': 'Slack integration active. Webhook URL is stored securely on the server.',
  'nav.governance': 'Global Governance',
  'nav.federation': 'Federation',
  'nav.dashboard': 'Dashboard',
  'nav.printhouses': 'Printhouses',
  'nav.printhouse-onboarding': 'Printhouse Onboarding',
  'nav.onboarding-observability': 'Onboarding Observability',
  'nav.jobs': 'Incoming Jobs',
  'nav.preflight': 'Preflight Service',
  'nav.manufacturing': 'Manufacturing Queue',
  'nav.machines': 'Machines',
  'nav.materials': 'Materials & Paper',
  'nav.pricing': 'Pricing Profiles',
  'nav.intelligence': 'Intelligence Layer',
  'nav.marketplace': 'Marketplace',
  'nav.financials': 'Financial Ops',
  'nav.billing-usage': 'Billing & Plans',
  'nav.production-monitoring': 'Production Monitoring',
  'nav.industrial': 'Industrial Ops',
  'nav.beta-runtime': 'Beta Runtime',
  'nav.beta-cohorts': 'Beta Cohorts',
  'nav.beta-governance': 'Beta Governance',
  'nav.tenants': 'Tenant Management',
  'nav.audit': 'Audit Logs',
  'nav.settings': 'Settings',
  'nav.printhouseSetup': 'Printhouse Setup',
  'nav.helpConsole': 'OS Help Console',
  'nav.logout': 'Logout Session',
  'nav.navigation': 'Navigation',
  'nav.collapseSidebar': 'Collapse sidebar',
  'nav.expandSidebar': 'Expand sidebar',
  'setup.section.company': 'Company Profile',
  'setup.section.companyDesc': 'Legal company identity, primary country, tax/VAT identifier, and administrative contact.',
  'setup.section.sites': 'Production Sites',
  'setup.section.sitesDesc': 'Physical printing plants, operating addresses, city location, and facility timezone.',
  'setup.section.machines': 'Machinery Fleet',
  'setup.section.machinesDesc': 'Offset presses, digital devices, cutting tables, binders, and finishing equipment.',
  'setup.section.capabilities': 'Machine Capabilities',
  'setup.section.capabilitiesDesc': 'Color management (CMYK, Spot UV, White Ink), maximum sheet dimensions, and PDF/X specs.',
  'setup.section.materials': 'Materials & Paper',
  'setup.section.materialsDesc': 'Substrate catalog, paper grammages, sheet sizes, and finishing compatibility.',
  'setup.section.capacity': 'Production Capacity',
  'setup.section.capacityDesc': 'Daily throughput constraints, shift schedules, working calendar, and job allocations.',
  'setup.section.leadTimes': 'Lead Times & SLAs',
  'setup.section.leadTimesDesc': 'Site-level daily cut-off times, timezone cut-offs, turnaround SLAs, and completion schedules.',
  'setup.section.pricing': 'Industrial Pricing & Rates',
  'setup.section.pricingDesc': 'Base manufacturing rates, paper kg costs, binding operations, and transport rates.',
  'setup.section.shipping': 'Shipping & Logistics',
  'setup.section.shippingDesc': 'Carriers, packaging options, freight rate calculation tables, and delivery tracking.',
  'setup.section.integrations': 'Integrations & Webhooks',
  'setup.section.integrationsDesc': 'Industrial MIS/ERP bridges, JDF/JMF shopfloor automation and outward webhooks.',
  'setup.section.marketplace': 'Marketplace Readiness',
  'setup.section.marketplaceDesc': 'Review qualification criteria, publish capacity to the budget network, and start receiving orders.',
  'company.title': 'Company Profile',
  'company.legalName': 'Legal Company Name',
  'company.tradingName': 'Trading / Display Name',
  'company.country': 'Primary Country',
  'company.city': 'City / Municipality',
  'company.address': 'Registered Street Address',
  'company.postalCode': 'Postal Code / ZIP',
  'company.phone': 'Official Phone Number',
  'company.website': 'Company Website URL',
  'company.contactName': 'Primary Contact Name',
  'company.taxId': 'Tax ID / VAT Number',
  'company.registrationId': 'Company Registration Number (Optional)',
  'company.saveBtn': 'Save Company Profile',
  'company.savingBtn': 'Saving Changes...',
  'jobs.title': 'Incoming Manufacturing Jobs',
  'jobs.subtitle': 'Operational Cockpit — Production Dispatch',
  'jobs.refresh': 'Refresh',
  'jobs.statPending': 'Pending',
  'jobs.statActive': 'Active',
  'jobs.statRejected': 'Rejected',
  'jobs.statExpired': 'Expired',
  'jobs.thIdentity': 'Job Identity',
  'jobs.thSpecs': 'Specs & Policy',
  'jobs.thCustomer': 'Customer',
  'jobs.thStatus': 'Status',
  'jobs.thActions': 'Actions',
  'jobs.actionAccept': 'Accept',
  'jobs.actionReject': 'Reject',
  'jobs.actionStartProduction': 'Start Production',
  'jobs.actionComplete': 'Complete',
  'jobs.statusFinished': 'Finished',
  'jobs.downloadBundle': 'Download Bundle',
  'jobs.emptyTitle': 'No Incoming Jobs Found',
  'jobs.invalidPayload': 'Invalid manufacturing payload received from server',
  'jobs.errorTitle': 'Pipeline Error',
  'jobs.retry': 'Retry',
  'preflight.title': 'Industrial Preflight Console',
  'preflight.subtitle': 'High-density administrative interface proxying unmocked job operations, array batches, and forensic audit telemetry directly onto the canonical V2 contract layer.',
  'preflight.quotaUsage': 'Global Quota Usage',
  'preflight.allocated': 'allocated',
  'preflight.upstreamDirect': 'Upstream Contract Direct',
  'preflight.tabJobs': 'Jobs Registry',
  'preflight.tabBatches': 'Batches Pipeline',
  'preflight.tabAudit': 'Audit Ledger',
  'preflight.tabGovernance': 'Governance Matrix',
  'preflight.filterTenant': 'Filter Scope by Tenant ID...',
  'manufacturing.title': 'Manufacturing Execution System',
  'manufacturing.subtitle': 'Industrial shopfloor routing, packages catalog, dispatch history and node settlement.',
  'manufacturing.tabIncoming': 'Incoming Jobs',
  'manufacturing.tabPackages': 'Manufacturing Packages',
  'manufacturing.tabHistory': 'Dispatch History',
  'manufacturing.tabMatching': 'Node Matching',
  'manufacturing.tabBilling': 'Financial Settlement',
  'manufacturing.packagesCatalog': 'Manufacturing Packages Catalog',
  'manufacturing.packagesDesc': 'Secure bridging layer mapping validated preflight documents to physical target production frames.',
  'marketplace.title': 'Marketplace Order Intake',
  'marketplace.subtitleSuperadmin': 'Operational intake for Budget marketplace orders, production files, pricing sessions, preflight readiness, and handoff preparation.',
  'marketplace.subtitlePrinthouse': 'Orders assigned to your printhouse from the PrintPrice marketplace, production files, preflight readiness, and handoff preparation.',
  'marketplace.tabIntake': 'Order Intake',
  'marketplace.tabSessions': 'Pricing Sessions',
  'marketplace.tabReadiness': 'Production Readiness',
  'marketplace.tabHandoff': 'Printhouse Handoff',
  'marketplace.tabAuctions': 'Capacity Auctions',
  'marketplace.tabAudit': 'Audit / Events',
  'marketplace.kpiNewOrders': 'New Orders',
  'marketplace.kpiFilesUploaded': 'Files Uploaded',
  'marketplace.kpiPreflightReq': 'Preflight Required',
  'marketplace.kpiPaymentBlocked': 'Payment Blocked',
  'marketplace.kpiReadyHandoff': 'Ready for Handoff',
  'marketplace.kpiBlockedOrders': 'Blocked Orders',
  'marketplace.searchPlaceholder': 'Filter by Order Ref, Email or ID...',
  'marketplace.thPublicRef': 'Public Ref',
  'marketplace.thCreated': 'Created',
  'marketplace.thCustomer': 'Customer / Session',
  'marketplace.thSpecs': 'Specs',
  'marketplace.thPrinter': 'Printer / Printhouse',
  'marketplace.thFiles': 'Files',
  'marketplace.thPreflight': 'Preflight',
  'marketplace.thPayment': 'Payment',
  'marketplace.thTotal': 'Total',
  'marketplace.thStatus': 'Operational Status',
  'marketplace.thActions': 'Actions',
  'marketplace.viewOrder': 'View Order',
  'marketplace.emptyOrders': 'No marketplace orders found',
  'dashboard.titleControlPlane': 'Control Plane',
  'dashboard.titlePrinthouse': 'Printhouse Portal',
  'dashboard.subtitleControlPlane': 'Operational Intelligence & Mission Control',
  'dashboard.subtitlePrinthouse': 'Operational Workspace & Production Dispatch',
  'dashboard.kpiJobsToday': 'Jobs Today',
  'dashboard.kpiActiveJobs': 'Active Jobs',
  'dashboard.kpiRealExtraction': 'Real Extraction',
  'dashboard.kpiCertifiable': 'Certifiable',
  'dashboard.kpiRuntimeFailures': 'Runtime Failures',
  'dashboard.kpiArtifactStorage': 'Artifact Storage',
  'dashboard.kpiOperationalNodes': 'Operational Nodes',
  'dashboard.kpiAuditStatus': 'Audit Status',
  'dashboard.panelPreflight': 'Preflight',
  'dashboard.panelGovernance': 'Governance',
  'dashboard.panelFederation': 'Federation Topology',
  'dashboard.liveStream': 'Latest Operational Events Stream',
  'dashboard.systemStatus': 'System:',
  'setup.cta.configureCompany': 'Configure Company Profile',
  'setup.cta.addSite': 'Add Production Site',
  'setup.cta.configureMachines': 'Configure Machinery Fleet',
  'setup.cta.configureCapabilities': 'Set Machine Capabilities',
  'setup.cta.configureMaterials': 'Add Materials to Catalog',
  'setup.cta.configureCapacity': 'Configure Production Capacity',
  'setup.cta.configureLeadTimes': 'Set Lead Times & SLAs',
  'setup.cta.configurePricing': 'Configure Industrial Rates',
  'setup.cta.reviewMarketplace': 'Review Marketplace Readiness',
  'setup.module.resolveDependency': 'Resolve Dependency',
  'setup.nextStep.capacity': 'Shift schedules, working calendar and daily throughput limits required',
  'setup.nextStep.leadTimes': 'Daily order cut-off times and turnaround SLAs required for scheduling',
  'setup.card.recommendedBadge': 'Recommended Next Action',
  'setup.card.blockedBadge': 'Prerequisite Required',
  'setup.summary.dimensionAccount': 'Account & Identity',
  'setup.summary.dimensionOps': 'Operational Readiness',
  'setup.summary.dimensionPricing': 'Industrial Pricing',
  'setup.summary.dimensionMarketplace': 'Marketplace Status',
  'setup.summary.requirementsCount': 'requirements verified',
  'setup.summary.ratesConfigured': 'Rates & Books Ready',
  'setup.summary.ratesPending': 'Rates Not Configured',
  'dashboard.metricDegradation': 'Source Telemetry Degradation:',
  'dashboard.metricDegradationDesc': 'Certain production registries are operating in fail-loud isolation state. Corresponding KPIs display N/A.',
  'dashboard.rowTotalAnalyzed': 'Total Analyzed (Today)',
  'dashboard.rowActiveConcurrent': 'Active Concurrent Tasks',
  'dashboard.rowCompletedAnalyses': 'Completed Analyses',
  'dashboard.rowFailedExecutions': 'Failed Executions',
  'dashboard.rowRealExtraction': 'Real Extraction Contract',
  'dashboard.rowRuntimeEnvFailures': 'Runtime Env Failures',
  'dashboard.rowPartialArtifacts': 'Partial Artifact Blocks',
  'dashboard.rowMeanRiskScore': 'Mean Document Risk Score',
  'dashboard.rowRegistryBuffer': 'Registry Buffer Depth',
  'dashboard.rowLatestExecution': 'Latest Execution Tail',
  'dashboard.rowActivePolicies': 'Active Swarm Policies',
  'dashboard.rowLatestRule': 'Latest Rule Triggered',
  'dashboard.rowPolicyInterceptions': 'Policy Execution Interceptions',
  'dashboard.rowCertBlocked': 'Certification Blocked Items',
  'dashboard.rowPassedCertifiable': 'Passed Certifiable Volumes',
  'dashboard.rowDeploymentClass': 'Deployment Contract Class',
  'dashboard.rowAuditRegistryState': 'Audit Trace Registry State',
  'dashboard.rowEstimatedValue': 'Estimated Value Generated',
  'dashboard.rowAvoidedWaste': 'Avoided Reprint Waste ROI',
  'dashboard.rowHoursSaved': 'Verified Prepress Hours Saved',
  'dashboard.rowAutoFixSuccess': 'AutoFix Success Count',
  'dashboard.rowAutoFixFailures': 'AutoFix Intercept Failures',
  'dashboard.rowQualityBenchmark': 'Derived Quality Benchmark',
  'dashboard.rowVerifiedNodes': 'Verified Swarm Nodes',
  'dashboard.rowActiveRoutes': 'Active Route Assignments',
  'dashboard.rowMissingGis': 'Missing GIS Coordinates',
  'dashboard.rowDegradedInfra': 'Degraded Infrastructure State',
  'dashboard.rowMeanUtilization': 'Mean Node Utilization',
  'dashboard.consensusSecure': 'SWARM CONSENSUS: SECURE',
  'dashboard.consensusDesc': 'Dispatch clusters operating natively via decentralized machine profile coordinate inheritance maps.',
  'dashboard.viewGeoMap': 'View Geographic Map ↓',
  'dashboard.noOperationalLogs': 'No operational logs retrieved in active database snapshot. System standing by.',
  'preflight.thJobPayload': 'Job Payload',
  'preflight.thTenantIdentity': 'Tenant Identity',
  'preflight.thTypePolicy': 'Type / Scope Policy',
  'preflight.thPayloadSize': 'Payload Size',
  'preflight.thStatusFidelity': 'Status & Fidelity',
  'preflight.thDiagnostics': 'Diagnostics / Fix Result',
  'preflight.thTimeline': 'Timeline',
  'preflight.filterPrinthouse': 'Filter Printhouse Scope...',
  'preflight.resetFilters': 'Reset Filters',
  'preflight.statusAll': 'Status: All',
  'preflight.typeAll': 'Type: All',
  'preflight.policyAll': 'Policy: All',
  'marketplace.drawerTitle': 'Order Identity:',
  'marketplace.prodBlockers': 'Production Blockers Detected',
  'marketplace.btnAcknowledge': 'Acknowledge Order',
  'marketplace.preflightGates': '1. Preflight Gates',
  'marketplace.runPreflight': 'Run Preflight',
  'marketplace.requirePreflight': 'Require Preflight',
  'marketplace.forcePass': 'Force Pass',
  'marketplace.forceFail': 'Force Fail',
  'marketplace.paymentGates': '2. Payment Gates',
  'marketplace.verifyApprove': 'Verify & Approve',
  'marketplace.blockPayment': 'Block Payment',
  'marketplace.printhouseHandoff': '3. Printhouse Handoff',
  'marketplace.assignPh': 'Assign PH',
  'marketplace.preparePackage': 'Prepare Package',
  'marketplace.markReady': 'Mark Ready',
  'marketplace.requestAction': 'Request Customer Action',
  'marketplace.internalNotes': 'Internal Ledger Notes',
  'marketplace.addNote': 'Add Internal Note',
  'marketplace.auditTimeline': 'Immutable Audit Timeline',
  'marketplace.selectedOffer': 'Selected Marketplace Offer',
  'marketplace.prodFiles': 'Production File Assets',
  'marketplace.noProdFiles': 'No production files found',
  'topbar.devPreview': 'Development Preview',
  'topbar.prodEnv': 'Production Environment',
  'topbar.certified': 'v2.0.0 Certified',
  'topbar.region': 'EU-WEST-1 (Primary)',
  'topbar.settings': 'Settings',
  'topbar.logout': 'Logout',
  'topbar.closeSession': 'Close Session?',
  'topbar.logoutConfirm': 'Are you sure you want to log out of the Control Plane?',
  'topbar.cancel': 'Cancel',
  'jobs.syncing': 'Syncing manufacturing pipeline...',
  'jobs.validationSeed': 'Validation seed — no production package',
  'jobs.syncingPackage': 'Syncing package data...',
  'dashboard.osControlCenter': 'OS Control Center',
  'dashboard.printhouseHub': 'Printhouse Hub',
  'dashboard.printhouseDesc': 'Real-time production vitals, job status, and operational metrics.',
  'dashboard.osControlDesc': 'Global governance, real-time vitals, and infrastructure coordination.',
  'dashboard.last24Hours': 'Last 24 Hours',
  'dashboard.assignedJobs': 'Assigned Jobs',
  'dashboard.globalJobs': 'Global Jobs',
  'dashboard.slaSuccess': 'SLA Success',
  'dashboard.avgTurnaround': 'Avg. Turnaround',
  'dashboard.meanLatency': 'Mean Latency',
  'dashboard.pendingAction': 'Pending Action',
  'dashboard.queueDepth': 'Queue Depth',
  'dashboard.activeGovBlocks': 'Active Governance Blocks',
  'dashboard.exploreAll': 'Explore All',
  'dashboard.noActiveGovBlocks': 'No active governance blocks',
  'dashboard.workerCluster': 'Worker Cluster',
  'dashboard.efficiency': 'Efficiency',
  'dashboard.workersActive': 'Workers Active',
  'dashboard.regionalCluster': 'Regional Cluster eu-west-1',
  'dashboard.queueStream': 'Queue Stream',
  'dashboard.liveBufferTrace': 'Live Buffer Trace',
  'dashboard.attachingStream': 'Attaching to stream...',
  'dashboard.errorLoadingStream': 'Error loading stream',
  'dashboard.queueStatus': 'Queue Status',
  'dashboard.jobCount': 'Job Count',
  'dashboard.description': 'Description',
  'dashboard.statusActiveDesc': 'Jobs currently being processed by workers',
  'dashboard.statusWaitingDesc': 'Jobs in queue waiting for an available worker',
  'dashboard.statusDelayedDesc': 'Scheduled or delayed jobs',
  'dashboard.statusFailedDesc': 'Jobs that encountered errors during execution',
  'dashboard.statusCompletedDesc': 'Successfully completed jobs',
  'dashboard.sourceUnavailable': 'N/A — source unavailable',
  'dashboard.sourceUnavailableShort': 'N/A — unavailable',
  'dashboard.missionControlError': 'Mission Control Telemetry Error',
  'dashboard.liveAuditPipeline': 'Live Audit Pipeline',
  'preflight.policiesUnavailable': 'Real preflight policies are unavailable. Transformation is disabled until upstream policy catalog is restored.',
  'preflight.policiesDegraded': 'Upstream policy catalog is unreachable. Using authoritative local versioned contract fallbacks for transformation enablement.',
  'preflight.fixResult': 'Fix Result',
  'preflight.issues': 'Issues',
  'preflight.fixes': 'Fixes',
  'preflight.batch': 'Batch',
  'preflight.untitled': 'Untitled.pdf',
  'preflight.registered': 'Registered',
  'preflight.batchId': 'Batch ID',
  'preflight.tenantArray': 'Tenant Array',
  'preflight.stagedJobsCount': 'Staged Jobs Count',
  'preflight.executionStatus': 'Execution Status',
  'preflight.timestamp': 'Timestamp',
  'preflight.auditIdTrace': 'Audit ID / Trace',
  'preflight.operationAction': 'Operation Action',
  'preflight.resolutionStatus': 'Resolution Status',
  'preflight.messageTrail': 'Message Trail',
  'preflight.loggedAt': 'Logged At',
  'preflight.eventLedgerId': 'Event Ledger ID',
  'preflight.tenantTarget': 'Tenant Target',
  'preflight.rulePolicySlug': 'Rule Policy Slug',
  'preflight.evaluationStatus': 'Evaluation Status',
  'preflight.enforcedAction': 'Enforced Action',
  'preflight.registeredTimestamp': 'Registered Timestamp',
  'preflight.gatewayCriticalError': 'Upstream Gateway integration encountered a critical error:',
  'preflight.executeRetry': 'Execute Retry',
  'dashboard.panelFleet': 'Fleet',
  'dashboard.panelStorage': 'Storage',
  'dashboard.panelIncidentBridge': 'Incident Bridge',
  'dashboard.panelIntelligenceLayer': 'Intelligence Layer',
  'dashboard.panelEconomy': 'Economy',
  'dashboard.panelHeartbeat': 'Heartbeat Matrix',
  'dashboard.panelSystemRegistry': 'System Registry',
  'dashboard.panelHeatmap': 'Manufacturing Heatmap',
  'dashboard.panelDispatchConsole': 'Dispatch Console',
  'dashboard.panelRoutingSimulation': 'Routing Simulation',
  'dashboard.panelConsole': 'Console',
  'dashboard.panelOperationalSummary': 'Operational Summary',
  'dashboard.panelOperationalActivity': 'Operational Activity Stream',
  'dashboard.activeJobs': 'Active Jobs',
  'dashboard.failedToday': 'Failed (Today)',
  'dashboard.completedJobsToday': 'Completed Jobs Today',
  'dashboard.throughput': 'Throughput',
  'dashboard.storageUtilized': 'Storage Utilized',
  'dashboard.activeArtifacts': 'Active Artifacts',
  'dashboard.artifacts': 'Artifacts',
  'dashboard.avgMargin': 'Avg Margin',
  'dashboard.quality': 'Quality',
  'dashboard.sectorClear': 'Sector Clear',
  'dashboard.continuousSweep': 'Continuous Sweep',
  'dashboard.inferenceEngines': 'Inference Engines',
  'dashboard.optimizationRate': 'Optimization Rate',
  'dashboard.telemetryInference': 'Telemetry Inference',
  'dashboard.driftVariance': 'Drift Variance',
  'dashboard.activeIncidents': 'Active Incidents',
  'dashboard.noMachinesConfigured': 'No Machines Configured',
  'dashboard.streamActive': 'Stream Subscription Active',
  'dashboard.listeningTraces': 'Listening for operational activity traces...',
  'dashboard.pauseQueue': 'Pause Queue Orchestration',
  'dashboard.pauseBadge': 'Emergency Global Stop',
  'dashboard.resumeQueue': 'Resume Queue Orchestration',
  'dashboard.resumeBadge': 'Re-engage Worker Hubs',
  'preflight.industrialExecution': 'Industrial Preflight Execution',
  'preflight.dropzoneTitle': 'Click or drag PDF payload block',
  'preflight.magicByteNotice': 'Enforces Magic Byte Checks',
  'preflight.selectPdfBtn': 'Select PDF File',
  'preflight.readyStatus': 'Ready',
  'preflight.tenantIsolation': 'Tenant Isolation',
  'preflight.policyCatalog': 'Policy Catalog',
  'preflight.policyUnavailable': 'Unavailable',
  'preflight.executionMode': 'Execution Mode',
  'preflight.modeAnalyze': 'Analyze Only',
  'preflight.modeAnalyzeDesc': 'Checks the PDF and produces diagnostics. It may not produce a corrected PDF.',
  'preflight.modeAutofix': 'Autofix',
  'preflight.modeAutofixDesc': 'Attempts to repair the PDF and should produce a Fixed PDF when successful.',
  'preflight.btnExecute': 'Execute Preflight Job',
  'preflight.btnProcessing': 'Processing',
  'preflight.btnDispatched': 'Dispatched Successfully',
  'preflight.execFailed': 'Industrial Preflight Gateway execution failed upstream.',
  'dashboard.stateProcessing': 'Processing',
  'dashboard.stateListening': 'Listening',
  'dashboard.stateStandby': 'Standby',
  'dashboard.stateActive': 'Active',
  'dashboard.stateOffline': 'Offline',
  'dashboard.stateDegraded': 'Degraded',
  'dashboard.stateSaturated': 'Saturated',
  'dashboard.stateSecure': 'Secure',
  'dashboard.stateSynced': 'Synced',
  'dashboard.stateHealthy': 'Healthy',
  'dashboard.metricLoad': 'Load',
  'dashboard.metricRisks': 'Risks',
  'dashboard.metricSync': 'Sync',
  'dashboard.metricActive': 'Active',
  'dashboard.queueStatusActive': 'Active',
  'dashboard.queueStatusWaiting': 'Waiting',
  'dashboard.queueStatusDelayed': 'Delayed',
  'dashboard.queueStatusFailed': 'Failed',
  'dashboard.queueStatusCompleted': 'Completed',
  // Tooltips & Accessibility Labels
  'topbar.toggleThemeLight': 'Switch to Light mode',
  'topbar.toggleThemeDark': 'Switch to Dark mode',
  'topbar.toggleLanguage': 'Switch language (current: {{lang}})',
  'topbar.notificationsBtn': 'Notifications ({{count}} unread)',
  'topbar.notificationsBtnZero': 'Notifications',
  'topbar.notificationsTitle': 'Notifications',
  'topbar.markAllRead': 'Mark all read',
  'topbar.newBadge': 'new',
  'sidebar.appSidebar': 'Application Sidebar',
  'sidebar.closeMobile': 'Close mobile sidebar',
  'settings.appearance.themeDarkTooltip': 'Industrial Dark theme for high-contrast low-light operations',
  'settings.appearance.themeLightTooltip': 'Corporate Light theme for daytime administrative work',
  'settings.appearance.densityComfortableTooltip': 'Comfortable density with standard padding and controls',
  'settings.appearance.densityCompactTooltip': 'Compact density optimized for data-dense industrial displays',
  'settings.appearance.animationsTooltip': 'Toggle UI micro-animations and transitions',
  'pricing.workflow.group': 'Pricing mode selector',
  'pricing.workflow.assistantBtn': 'AI pricing calibration assistant',
  'pricing.workflow.manualBtn': 'Manual rate cards setup',
  'pricing.workflow.priceBooksBtn': 'Commercial quantity tiers and client price books',
  'pricing.hawkeye.tooltip': 'Read-only canonical pricing health, representative calibrated anchors, and domain completeness.',
  'pricing.hawkeye.anchorsTooltip': 'Representative calibrated anchor rates from the canonical rate card.',
  'pricing.hawkeye.modulesTooltip': 'Health and structural completeness per pricing domain.',
  'pricing.hawkeye.revisionTooltip': 'Latest created revision (not live checksum verified)',
  'pricing.action.editMetadata': 'Edit metadata',
  'pricing.action.cloneVersion': 'Clone Version',
  'pricing.action.deleteDraft': 'Delete draft',
  'pricing.action.calibrateQuote': 'Calibrate from this quote',
  'pricing.action.previousSessions': 'Previous calibrated sessions',
  'pricing.action.removeEntry': 'Remove {{name}}',
  'pricing.action.dismissError': 'Dismiss error',
  'setup.help.searchLabel': 'Search settings and help documentation',
  'setup.help.closeBtn': 'Close help modal',
  'setup.tutorial.exitBtn': 'Exit tutorial',
  'setup.status.completed': 'Completed',
  'setup.status.inProgress': 'In Progress',
  'setup.status.needsAttention': 'Needs Attention',
  'setup.status.prerequisitesRequired': 'Prerequisites Required',
  'setup.summary.regionLabel': 'Readiness Dimensions Overview',
  'dashboard.orders.expectedRevenue': 'Expected Printhouse Revenue',
  'dashboard.orders.filterAll': 'All Orders',
  'dashboard.orders.filterHighProfit': 'High Profit',
  'dashboard.orders.filterUrgent': 'Urgent',
  'dashboard.orders.noOrders': 'No orders matching the current filter.',
  'pricing.calibration.currentSpec': 'Current Specification',
  'pricing.calibration.editFullSpec': 'Edit Full Specification',
  'pricing.calibration.drawerTitle': 'Current Specification & Extracted Details',
  'pricing.calibration.drawerSubtitle': 'Review parameters extracted by the assistant or attached PDF.',
  'pricing.calibration.noSpecsYet': 'No specifications entered yet.',
  'pricing.calibration.noSpecsHint': 'Upload a quote PDF or type a job description to begin.',
  'pricing.action.calibrateQuoteBtn': 'Calibrate Quote',
  'pricing.action.calibratedBooks': 'Calibrated Books',
  'pricing.action.revisions': 'Revisions',
  'pricing.action.hideAdvanced': 'Hide Advanced',
  'pricing.action.advancedDetails': 'Advanced Details',
  'pricing.dropzone.title': 'Drop your quotation PDF here',
  'pricing.dropzone.subtitle': 'or browse your files (PDF · max. ~10 MB)',
  'pricing.dropzone.dragOver': 'Release to analyze PDF quotation',
  'pricing.dropzone.browse': 'Browse files',
  'pricing.dropzone.compactTitle': 'Attach another PDF quote',
  'pricing.dropzone.compactAction': 'Upload new PDF',
  'pricing.example.prompt1': '1,000 copies, 170x240mm, 128p 4/4 on 80g offset, 300g cover, perfect bound for €2,450',
  'pricing.example.prompt2': '500 copies of 210x297mm A4, 64 pages 4/4 coated 130g, saddle stitched for €1,200',
  'pricing.example.prompt3': 'Hardcover photo book, 250 copies, 200p 4/4 150g coated, sewn binding for €4,800',
  'pricing.review.extractedData': 'Extracted Quote Data',
  'pricing.review.pendingConfirmation': 'Pending Confirmation',
  'pricing.review.selectedVariant': 'Selected Offer & Variant',
  'pricing.review.noVariantSelected': 'No variant selected yet',
  'pricing.review.calibrationProposal': 'Calibration Proposal',
  'pricing.review.noProposalYet': 'No solver proposal generated yet',
  'pricing.variant.selectedBadge': 'Selected',
  'pricing.spec.quantity': 'Quantity:',
  'pricing.spec.copies': 'copies',
  'pricing.spec.trimSize': 'Trim Size:',
  'pricing.spec.interiorPages': 'Interior Pages:',
  'pricing.spec.paper': 'Paper:',
  'pricing.spec.binding': 'Binding:',
  'pricing.review.manufacturingTarget': 'Manufacturing Target:',
  'pricing.review.transportPerKg': 'Transport (€/kg):',
  'pricing.solver.awaitingSolver': 'Awaiting Solver',
  'pricing.solver.predictedPrice': 'Predicted Price:',
  'pricing.solver.residual': 'Residual:',
  'pricing.solver.accepted': 'Accepted',
  'pricing.wizard.step1': 'Describe Job',
  'pricing.wizard.step2': 'Review',
  'pricing.wizard.step3': 'Manufacturing Cost',
  'pricing.wizard.step4': 'Calibrate',
  'pricing.wizard.step5': 'Test Pricing',
  'pricing.acceptance.modalTitle': 'Confirm Governed Acceptance',
  'pricing.acceptance.modalSubtitle': 'Apply calibrated rate card to production node',
  'pricing.acceptance.targetNode': 'Target Production Node:',
  'pricing.acceptance.referenceBook': 'Reference Book:',
  'pricing.acceptance.declaredTarget': 'Declared Manufacturing Target:',
  'pricing.acceptance.calibratedPrice': 'Calibrated Forward Price:',
  'pricing.acceptance.solverResidual': 'Solver Residual:',
  'pricing.acceptance.immutableTitle': 'Immutable Pricing Revision Creation',
  'pricing.acceptance.immutableDesc': 'Accepting will atomically verify baseline integrity, update active production rate cards for this node, and record an immutable pricing revision in the audit ledger.',
  'pricing.acceptance.applying': 'Applying Revision...',
  'pricing.acceptance.acceptBtn': 'Accept Pricing Revision',
  'pricing.acceptance.closeModal': 'Close modal',
  'fileTooLargeError': 'File exceeds server size limit (10 MB). Please select a smaller PDF.',

  // Topbar and Governance Posture
  'topbar.governedPosture': 'Active Governance',
  'topbar.governedVerifying': 'Verifying...',
  'topbar.governedDegraded': 'Partial Governance',
  'topbar.governedOffline': 'No Telemetry',
  'topbar.governedActiveTooltip': 'Server telemetry and RBAC access control verified in real time.',
  'topbar.governedDegradedTooltip': 'Connectivity established with degraded server dependencies.',
  'topbar.governedOfflineTooltip': 'Live server telemetry could not be verified; no operational guarantees asserted.',
  'topbar.governedVerifyingTooltip': 'Checking server dependencies telemetry and RBAC control.',

  // Industrial Operations Page
  'industrial.title': 'Industrial Operations',
  'industrial.subtitle': 'High-fidelity orchestration and governance for distributed infrastructure.',
  'industrial.operational': 'Operational',
  'industrial.intelligence': 'Intelligence',
  'industrial.governance': 'Governance',
  'industrial.systemOperational': 'System Operational',
  'industrial.telemetryDegraded': 'Partial Telemetry',
  'industrial.telemetryUnconfigured': 'Unconfigured',
  'industrial.verifyingStatus': 'Verifying Status...',
  'industrial.liveMap': 'Live Map',
  'industrial.nodesConnected': 'Connected Nodes',

  // Geospatial Map & Nodes
  'map.unconfiguredProvider': 'Geospatial provider Carto lacks configured API key',
  'map.unconfiguredProviderHint': 'To avoid loading failing or watermarked tiles ("API KEY REQUIRED"), infrastructure is displayed in structured tactical mode with direct node inspection.',
  'map.tacticalSurface': 'Geospatial Tactical Surface',
  'map.nodeRegistry': 'Tactical Node Registry',
  'map.inspectMachine': 'Inspect Machine',
  'map.coordinatesMissing': 'No coordinates assigned',
  'map.coordinatesAssigned': 'Coordinates assigned',
  'map.routingDecalog': 'Routing Decalog',
  'map.routingExplanation': 'Operational history of routing and assignment decisions.',
  'map.collapseTelemetry': 'Collapse Telemetry',
  'map.inspectExclusions': 'Inspect Exclusions',
  'map.nodesExcluded': 'nodes excluded from geospatial map',
  'map.nodeExcluded': 'node excluded from geospatial map',

  // Common & Maps
  'common.cancel': 'Cancel',
  'common.confirm': 'Confirm',
  'common.done': 'Operation completed successfully.',
  'setup.region': 'Region',

  // Beta Workspace & Runtime
  'beta.runtime.title': 'Limited Beta Runtime & Recovery Console',
  'beta.runtime.subtitle': 'Monitor active sessions, audit events, and restart recovery drills.',
  'beta.runtime.safetyWarning': 'Invite-Only Limited Beta Runtime. This does not enable public access, open marketplace, payment execution, payouts, or unauthorized code mutations.',
  'beta.runtime.drillWarning': 'Restart Recovery Drill. Strict verification of persistence invariants and access boundaries.',
  'beta.runtime.hardenedStatus': 'Integrity & Restart Recovery Registry',
  'beta.runtime.restartDrillPanel': 'Restart Recovery Drill Panel',
  'beta.runtime.noDrillRun': 'No drill executed — Run a drill to capture hashes and verify integrity',
  'beta.runtime.pendingSnapshot': 'Pending snapshot',
  'beta.runtime.notEvaluated': 'Not evaluated (run check)',
  'beta.runtime.createDrill': 'Create Drill',
  'beta.runtime.snapshotBefore': 'Snapshot Before',
  'beta.runtime.verifyAfter': 'Verify After',
  'beta.runtime.compareSnapshots': 'Compare Snapshots',
  'beta.runtime.verifyKillSwitch': 'Verify Kill Switch',
  'beta.runtime.verifyAccess': 'Verify Access',
  'beta.runtime.gateContext': 'Beta Gate Context',
  'beta.runtime.enableGate': 'Enable Gate',
  'beta.runtime.disableGate': 'Disable Gate',
  'beta.runtime.checkReadiness': 'Check Readiness',
  'beta.runtime.killSwitchConfirmTitle': 'Confirm Emergency Kill Switch',
  'beta.runtime.killSwitchConfirmMsg': 'Do you want to trigger the emergency kill switch? This action will immediately suspend beta runtime access for the selected gate.',
  'beta.runtime.disableGateConfirmTitle': 'Confirm Gate Disabling',
  'beta.runtime.disableGateConfirmMsg': 'Do you want to disable this access gate? Participants will lose access to assigned capabilities.',
  'beta.runtime.advancedJson': 'Advanced Options & JSON Diagnostics',
  'beta.runtime.limitedBeta': 'Beta Environment',
  'beta.runtime.recoveryRegistry': 'Integrity & Restart Recovery Registry',
  'beta.runtime.triggerKillSwitch': 'Trigger Kill Switch',
  'beta.runtime.clearKillSwitch': 'Clear Kill Switch',
  'beta.runtime.evidenceOutputs': 'Evidence & Audit Timeline Outputs',
  'beta.runtime.getAuditTimeline': 'Audit Timeline',
  'beta.runtime.buildEvidencePack': 'Evidence Pack',
  'beta.runtime.advancedDiagnostics': 'Technical Diagnostics & JSON Payload',
  'beta.runtime.activityReview': 'Beta Runtime Activity Observation',
  'beta.runtime.warningTitle': 'Beta Runtime Safety Warning',
  'beta.runtime.safetyInvariants': 'Guaranteed Safety Invariants',

  // Beta Sessions
  'beta.sessions.title': 'Controlled Beta Runtime Sessions',
  'beta.sessions.subtitle': 'Manage concurrency limits, TTL, and operational session revocation.',
  'beta.sessions.warning': 'Strictly scoped beta runtime sessions. Does not grant general access or commercial permissions.',

  // Beta Health & Reviews
  'beta.health.title': 'Cohort Activity Review & Health',
  'beta.health.subtitle': 'Evaluate usage signals, detect anomalies, and generate recommendations before intervening.',
  'beta.health.warning': 'Cohort health review gate. Does not automatically alter access, marketplace scope, or billing rules.',
  'beta.health.noReviews': 'No activity reviews generated yet.',
  'beta.health.actionableHint': 'Evaluating cohort health requires prior activity observation records while preserving security invariants.',
  'beta.health.goToActivity': 'Go to Activity Observation',
  'beta.health.goToObservation': 'Go to Activity Observation',
  'beta.health.noFinalizedReviews': 'No finalized health reviews found.',
  'beta.health.createOrFinalizeHint': 'Finalize a health review in this tab to be able to prepare an intervention package.',

  // Beta Governance & Interventions
  'beta.governance.title': 'Governed Cohort Intervention Preparation',
  'beta.governance.subtitle': 'Prepare and formalize intervention packages with strict auditability.',
  'beta.governance.warning': 'Proposed action package for review only. Strictly for preparing governed intervention packages. No operational mutations or commercial changes are executed.',
  'beta.governance.noReviewsWarning': 'No finalized prior health reviews found.',
  'beta.governance.noFinalizedReviews': 'No finalized health reviews found.',
  'beta.governance.preparationHint': 'Preparing a governed intervention proposal requires a finalized activity review.',
  'beta.governance.goToHealthReviews': 'Go to Cohort Health Reviews',
  'beta.governance.approvalNotExecution': 'Approval does not constitute immediate execution',
  'beta.governance.approvalsTitle': 'Governed Intervention Approvals',
  'beta.governance.executionsTitle': 'Safe Execution of Governed Interventions',

  // Topbar Telemetry
  'topbar.telemetryHealthy': 'Core Telemetry: OK',
  'topbar.telemetryDegraded': 'Degraded Telemetry',
  'topbar.telemetryOffline': 'No Telemetry',
  'topbar.telemetryVerifying': 'Checking Core...',
  'topbar.telemetryVerifyingTooltip': 'Checking process state and dependencies on /api/system/health...',

  // Map Cartography Fallback
  'map.tileLoadFailed': 'Failed to load map tiles (401/403/Network)',
  'map.tileLoadFailedHint': 'Configured tile provider failed to respond. Tactical node registry and machine inspection remain fully operational.',
  'common.retry': 'Retry',

  // Workspace and Navigation Shells
  'beta.runtime.workspaceTitle': 'Controlled Beta Runtime',
  'beta.runtime.workspaceDesc': 'Monitor active sessions, activity tracking, and cohort health reviews.',
  'beta.runtime.breadcrumb': 'Runtime',
  'beta.runtime.tabOverview': 'Overview',
  'beta.runtime.tabSessions': 'Sessions',
  'beta.runtime.tabActivity': 'Activity',
  'beta.runtime.tabHealth': 'Cohort Health',

  'beta.governance.workspaceTitle': 'Beta Cohort Governance',
  'beta.governance.workspaceDesc': 'Govern cohort intervention proposals, approvals, operational executions, and simulations.',
  'beta.governance.breadcrumb': 'Governance',
  'beta.governance.tabInterventions': 'Interventions',
  'beta.governance.tabApprovals': 'Approvals',
  'beta.governance.tabExecutions': 'Executions',
  'beta.governance.tabSimulations': 'Simulations',
  'beta.governance.tabSimulationReviews': 'Simulation Reviews',

  'beta.cohort.workspaceTitle': 'Beta Cohort Management',
  'beta.cohort.workspaceDesc': 'Manage cohort activation, issue invites, and audit active participants.',
  'beta.cohort.breadcrumb': 'Cohorts',
  'beta.cohort.tabActivation': 'Activation',
  'beta.cohort.tabInvitations': 'Invitations',
  'beta.cohort.tabParticipants': 'Participants',

  // Industrial Operations Navigation Tabs
  'industrial.tabLive': 'Live Loop',
  'industrial.tabWorkers': 'Fleet',
  'industrial.tabNodes': 'Nodes',
  'industrial.tabDispatch': 'Dispatch',
  'industrial.tabMetrics': 'Metrics',
  'industrial.tabEconomics': 'Economics',
  'industrial.tabTemporal': 'Temporal',
  'industrial.tabSim': 'Simulation',
  'industrial.tabPolicies': 'Policies',
  'industrial.tabIncidents': 'Incidents',
  'industrial.tabLifecycle': 'Lifecycle',
  'industrial.tabStorage': 'Storage',

  // Machine Detail Drawer & Node Inspection
  'drawer.title': 'Operational Detail',
  'drawer.node': 'Node',
  'drawer.machine': 'Machine',
  'drawer.syncing': 'Syncing industrial data...',
  'drawer.telemetryFailure': 'Telemetry Failure',
  'drawer.retrySync': 'Retry Synchronization',
  'drawer.region': 'Region',
  'drawer.heartbeat': 'Heartbeat',
  'drawer.uptime': 'Uptime',
  'drawer.mode': 'Mode',
  'drawer.trustTier': 'Trust Tier',
  'drawer.equipment': 'Industrial Equipment',
  'drawer.noMachineAssociated': 'No physical machine associated with this node',
  'drawer.unassignedEquipment': 'Unassigned equipment (Node infrastructure only)',
  'drawer.capabilities': 'Capabilities Matrix',
  'drawer.noCapabilities': 'No capabilities registered',
  'drawer.liveTelemetry': 'Live Telemetry',
  'drawer.jobsRunning': 'Active Jobs',
  'drawer.jobsQueued': 'Queued Jobs',
  'drawer.jobsFailed24h': 'Failed (24h)',
  'drawer.throughputH': 'Throughput/h',
  'drawer.utilization': 'Utilization',
  'drawer.avgTurnaround': 'Avg Turnaround',
  'drawer.noTelemetry': 'No live telemetry data available for this node',
  'drawer.queuePressure': 'Queue Pressure',
  'drawer.saturation': 'Saturation',
  'drawer.overloadRisk': 'Overload Risk',
  'drawer.dispatchContention': 'Dispatch Contention',
  'drawer.estBacklog': 'Est. Backlog',
  'drawer.historicalPerformance': 'Historical Performance',
  'drawer.window24h': '24h Window',
  'drawer.window7d': '7d Window',
  'drawer.slaSuccess': 'SLA',
  'drawer.preflightScore': 'Preflight',
  'drawer.completed': 'Completed',
  'drawer.volume': 'Volume',
  'drawer.failureRatio': 'Failure Ratio',
  'drawer.subRealtime': 'Real-time',
  'drawer.subBacklog': 'Backlog',
  'drawer.subNonRecoverable': 'Non-recoverable',
  'drawer.subCompleted': 'Completed',
  'drawer.subCapacity': 'Capacity',
  'drawer.subAverage': 'Average',
  'common.noData': 'No data',

  // Tenant Selector & Dynamic Filtering
  'tenant.label': 'Authorized Tenant',
  'tenant.selectPrompt': '-- Select Tenant --',
  'tenant.allTenants': 'All Tenants',
  'tenant.loading': 'Loading tenants...',
  'tenant.error': 'Error loading tenants:',
  'tenant.retry': 'Retry',
  'tenant.noTenants': 'No registered tenants found.',

  // Technical Details Collapsible
  'technicalDetails.title': 'Technical Details & Diagnostics',
  'technicalDetails.show': 'Show',
  'technicalDetails.hide': 'Hide',
  'technicalDetails.copy': 'Copy',
  'technicalDetails.copied': 'Copied!',
  'technicalDetails.copyJson': 'Copy JSON',
  'technicalDetails.jsonPayload': 'JSON Diagnostic Payload',
  'technicalDetails.backendNoticeTitle': 'Backend API Gap / Assisted Manual Entry',

  // Beta Cohorts Management
  'beta.cohort.activationSafetyNotice': 'First Controlled Invite-Only Beta Cohort Activation. This does not enable FULL_PUBLIC, open marketplace access, payment execution, refund execution, payout execution, provider external submission, tax/accounting submission, or uncontrolled source mutation.',
  'beta.cohort.invitationSafetyNotice': 'Controlled invite issuance only. This is not public beta, not open marketplace, and not automatic expansion. Execution of invite issuance is gated under strict approved preparation and hard limits.',
  'beta.cohort.participantSafetyNotice': 'Controlled invite acceptance and participant onboarding only. This is not public signup, not public beta, and not open marketplace. Runtime access is strictly confined to the approved scope.',
  'beta.cohort.sectionStatus': 'Status Inquiry & Verification',
  'beta.cohort.sectionPrep': 'Preparation & Configuration',
  'beta.cohort.sectionGovernance': 'Access Modification Actions',
  'beta.cohort.sectionAudit': 'Audit & Evidence',
  'beta.cohort.sectionMetrics': 'Dashboard Metrics',
  'beta.cohort.gateId': 'Gate ID',
  'beta.cohort.cohortId': 'Cohort ID',
  'beta.cohort.activationId': 'Activation ID',
  'beta.cohort.batchId': 'Batch ID',
  'beta.cohort.inviteId': 'Invite ID',
  'beta.cohort.participantId': 'Participant ID',
  'beta.cohort.preparationId': 'Preparation ID',
  'beta.cohort.evidencePackId': 'Evidence Pack ID',
  'beta.cohort.verifyReadiness': 'Verify Readiness',
  'beta.cohort.readinessStatus': 'Readiness Status',
  'beta.cohort.loginRequired': 'Session expired or missing. Please log in.',
  'beta.cohort.loginBtn': 'Log In',
  'beta.cohort.retryBtn': 'Retry',
  'beta.cohort.confirmAction': 'Confirm Action',
  'beta.cohort.cancelAction': 'Cancel',
  'beta.cohort.noData': 'No data',
  'beta.cohort.reasonNotes': 'Reason / Justification',
  'beta.cohort.manualEntryNotice': 'Validated manual entry: This entity does not have a listing endpoint in the backend.',
} as const;

export type TranslationKeys = keyof typeof en;
