export const es = {
  appName: 'Verificación Pre-vuelo de PDF',
  dragDropPrompt: 'Arrastra y suelta tu PDF aquí, o haz clic para seleccionar un archivo',
  invalidFileType: 'Tipo de archivo inválido. Por favor, sube un archivo PDF.',
  loadingFile: 'Cargando archivo PDF...',
  preparingFileForAnalysis: 'Preparando tu archivo para el análisis.',
  analyzingPDF: 'Analizando PDF...',
  thisMayTakeAMoment: 'Esto puede tardar un momento.',
  runPreflight: 'Ejecutar Verificación Pre-vuelo',
  or: 'o',
  of: 'de',
  browseYourComputer: 'examinar tu computadora',
  pdfMaxHint: 'PDF · máx. ~50 MB',
  selectedLabel: 'PDF seleccionado',
  changeLabel: 'Cambiar',
  uploadTipLargePdf: 'Consejo: los PDF grandes pueden tardar un poco más.',
  uploadYourPdf: 'Sube tu PDF',
  uploadDescription: 'Selecciona un archivo PDF para iniciar la verificación pre-vuelo',
  analyzingYourPdf: 'Analizando tu PDF...',
  analysisComplete: 'Análisis Completado',
  fixIssuesTitle: 'Corregir Incidencias',
  fixIssuesDescription: 'Revisa y corrige las {{count}} incidencia(s) encontradas en tu PDF',
  fixIssuesRemaing: '{{count}} incidencia(s) pendiente(s)',
  reviewAndDownload: 'Revisar y Descargar',
  pdfProcessedReady: 'Tu PDF listo para imprimir está listo. Revísalo y descárgalo a continuación.',
  reviewAndApplyCorrections: 'Revisa tu documento y aplica correcciones si es necesario.',
  back: '← Atrás',
  next: 'Siguiente →',
  igniteEngine: 'Probar Motor V2',
  fixIssues: 'Corregir Incidencias →',
  continueToReview: 'Continuar para Revisar →',
  startOver: 'Empezar de Nuevo',
  analysisWaitMessage: 'Espera mientras verificamos tu documento para impresión',
  issuesFoundMessage: 'Revisa los elementos a continuación que requieren atención',
  pdfLooksGood: '¡Genial! Tu PDF se ve bien',
  checkingDetails: 'Verificando fuentes, colores, imágenes y más...',
  perfectNoIssues: '¡Perfecto! No se encontraron incidencias',
  readyForPrinting: 'Tu PDF está listo para imprimir',
  readyForPrint: 'Listo para Imprimir!',
  reviewRequired: 'Requiere Revisión',
  readyForProduction: 'Listo para Producción',
  actionRequired: 'Acción Requerida',
  availableReports: 'Reportes Disponibles',
  complianceCertified: 'Certificado de Cumplimiento',
  txtSummary: 'Resumen TXT',
  productionTools: 'Herramientas de Producción',
  aiMagicApplied: '¡Magia de IA Aplicada!',
  aiMagicDescription: 'Nuestro Asistente IA ha optimizado automáticamente tus colores, resolución y márgenes para impresión profesional.',
  processedSuccessfully: 'Documento procesado exitosamente{{count, plural, =0 {} other { ({{count}} incidencia(s) resuelta(s))}}}',
  issuesSummary: 'Resumen de Incidencias',
  overallScore: 'Puntuación General',
  issueCategories: 'Categorías de Incidencias',
  fileLabel: 'Archivo',
  downloadReport: 'Descargar Informe',
  downloadOriginal: 'Descargar Original',
  reanalyzePdf: '🔄 Volver a analizar PDF',
  noPdfLoaded: 'Ningún PDF cargado. Por favor, sube un archivo para empezar.',
  pdfViewer: 'Visor de PDF',
  pageNavigation: 'Navegación por Páginas',
  prevPage: 'Página Anterior',
  nextPage: 'Página Siguiente',
  goToPage: 'Ir a la página',
  typePageNumber: 'Escribe el número de página',
  heatmap: 'Mapa de Calor',
  aiVisualCheck: 'Verificación Visual IA',
  toggleTacHeatmap: 'Alternar Mapa de Calor TAC (Cobertura Total de Área)',
  aiVisualQualityCheck: 'Verificación de Calidad Visual IA',
  analyzingInk: 'Analizando Tinta...',
  tacLessThan280: '<280%',
  tac280to300: '280-300%',
  tacMoreThan300: '>300%',
  severity: 'Severidad',
  page: 'Página',
  documentWide: 'Todo el documento',
  message: 'Mensaje',
  details: 'Detalles',
  close: 'Cerrar',
  error: 'Error',
  noIssuesToDisplay: 'No hay incidencias para mostrar.',
  noIssuesFound: '¡No se encontraron incidencias. Tu PDF se ve perfecto!',
  noIssues: 'No hay incidencias',
  noIssuesPdf: 'No se encontraron incidencias en tu PDF',
  totalIssues: 'incidencias en total',
  issuesFoundApplyOrDownload: 'Se encontraron {{count}} incidencia(s) - aplica correcciones o descarga el archivo original',
  issuesFound: 'Incidencias Encontradas',
  issues: 'Incidencias',
  errors: 'Errores',
  warnings: 'Advertencias',
  info: 'Información',
  errAbbr: 'err',
  warnAbbr: 'adv',
  infoAbbr: 'inf',
  selectAnIssue: 'Selecciona una incidencia para ver sus detalles y posibles soluciones.',
  selectedIssueDetails: 'Detalle de la Incidencia Seleccionada',
  currentIssue: 'Incidencia Actual',
  categoryImages: 'Imágenes',
  categoryColor: 'Espacios de Color',
  categoryFonts: 'Fuentes',
  categoryMetadata: 'Metadatos',
  categoryTransparency: 'Transparencia',
  categoryBleedMargins: 'Sangrado y Márgenes',
  categoryResolution: 'Resolución',
  categoryCompliance: 'Cumplimiento',
  categoryPageSetup: 'Configuración de Página',
  categoryAnnotations: 'Anotaciones',
  categoryFormFields: 'Campos de Formulario',
  categoryMultimedia: 'Multimedia',
  categoryLayers: 'Capas',
  categoryOther: 'Otros',
  quickFixes: 'Soluciones Rápidas',
  aiAssistance: 'Asistencia IA',
  add3mmBleed: '🔧 Añadir Sangrado de 3mm',
  convertToCMYK: '🎨 Convertir a CMYK',
  convertToGrayscaleBtn: '⚫ Convertir a Escala de Grises',
  rebuildHighRes300dpi: '🛠️ Reconstruir Alta Resolución (300 DPI)',
  converting: 'Convirtiendo...',
  fixing: 'Corrigiendo...',
  cmykProfile: 'Perfil CMYK:',
  genericCMYK: 'CMYK Genérico',
  coatedFogra39: 'Coated FOGRA39 (ISO 12647-2:2004)',
  coatedFogra51: 'ISO Coated v3 (FOGRA51) - Estándar Moderno',
  uncoatedFogra52: 'PSO Uncoated v3 (FOGRA52)',
  gracol2006: 'GRACoL 2006 (Coated #1)',
  swop2006: 'SWOP 2006 (Coated #3)',
  uncoatedFogra29: 'Uncoated FOGRA29',
  bleedSafe: 'Seguro (Solo Boxes / Lienzo)',
  bleedAggressive: 'Agresivo (Escalado-relleno)',
  bleedMode: 'Modo de Sangrado:',
  bleedSafeHint: 'El modo seguro añade margen sin deformar. El diseño puede quedar con borde blanco. Nota: Las acciones interactivas (links/anotaciones) podrían no conservarse.',
  optionalTools: 'Herramientas Opcionales',
  additionalProcessingOptions: 'Opciones de procesamiento adicionales',
  convertToGrayscale: 'Convertir a Escala de Grises',
  convertColorsToCMYK: 'Convertir Colores a CMYK',
  rebuildPdfHighRes: 'Reconstruir PDF (Alta Resolución)',
  createBooklet: 'Crear Folleto',
  downloadProcessedPdf: 'Descargar PDF Procesado',
  stepNumber: 'Paso {{number}}',
  uploadPdf: 'Subir PDF',
  analysis: 'Análisis',
  review: 'Revisar',
  explainSuggestFix: 'Explicar y Sugerir Corrección (Auditoría IA)',
  explainAndSuggestFix: 'Explicar y Sugerir Corrección (Auditoría IA)',
  getEfficiencyTips: 'Obtener Consejos de Eficiencia (Auditoría IA)',
  aiAuditTitle: 'Auditoría IA: Explicar y Sugerir Correcciones',
  efficiencyAuditTitle: 'Auditoría IA: Obtener Consejos de Eficiencia',
  fetchingAIResponse: 'Obteniendo respuesta de la IA...',
  aiResponse: 'Respuesta de la IA',
  aiError: 'No se pudo obtener la respuesta de la IA. Por favor, verifica tu clave API y vuelve a intentarlo.',
  geminiKeyMissingError: 'La clave API de Gemini falta o es inválida. Las características de IA están deshabilitadas.',
  billingDocLink: 'Ver documentación de facturación',
  visualMode: 'Modo Visual',
  fastestFix: 'Solución Más Rápida',
  bestFix: 'Mejor Solución',
  timeImpact: 'Impacto en el Tiempo',
  costImpact: 'Impacto en el Costo',
  aiDescriptionExplain: 'Obtén una explicación detallada de esta incidencia y sugerencias paso a paso sobre cómo solucionarla, incluyendo instrucciones específicas para herramientas comunes como Adobe InDesign o Acrobat.',
  aiDescriptionEfficiency: 'Descubre las formas más eficientes de resolver esta incidencia. Compara la solución más rápida con la de mejor calidad, y entiende sus posibles impactos en tiempo y costo.',
  pageLabel: 'Página {{page}}',
  suggestedFix: 'Sugerencia de corrección',
  issueSummary: 'Resumen de la Incidencia',
  engineHint: 'Pista del Motor',
  drawerActions: 'Acciones',
  actions: 'Acciones',
  severityError: 'Error',
  severityWarning: 'Advertencia',
  severityInfo: 'Información',
  issue: 'Incidencia',
  aiHintInDrawer: 'Usa los botones de IA para obtener una explicación detallada o consejos de eficiencia sobre esta incidencia.',
  aiMagicFix: 'AI Magic Fix',
  aiMagicFixDesc: 'Un solo clic. Nos encargamos de todo automáticamente.',
  manualMode: 'Manual',
  manualModeDesc: 'Para usuarios avanzados que quieren revisar problemas y elegir correcciones.',
  recommended: 'Recomendado',
  bestWithAi: 'Mejor con AI Magic Fix',
  readyForAnalysis: 'Listo para análisis',
  browseFiles: 'Examinar archivos',
  processingTime: 'Tiempo de procesamiento',
  processingTimeVal: '~10-60 segundos',
  pdfLimit: 'PDF hasta 50 MB',
  magicWait: 'Espere a que ocurra la magia',
  dragAndDropModern: 'Arrastre y suelte su PDF',
  changeFile: 'Cambiar archivo seleccionado',
  safeProcessing: 'Procesamiento seguro y temporal',
  continue: 'Continuar',
  headerUploadTitle: 'Sube tu PDF',
  headerUploadSubset: 'Elige AI Magic Fix (recomendado) o Manual.',
  chooseWorkflow: 'Elige flujo de trabajo',
  recommendMagicHint: 'Recomendamos Magic Fix para la mayoría.',
  uploadToContinue: 'Suba un PDF para continuar.',
  magicPoint1: 'Corrige los problemas de impresión más comunes',
  magicPoint2: 'Genera un PDF listo para imprimir',
  magicPoint3: 'Sin conocimientos técnicos requeridos',
  tempProcessNote: 'Procesamos tu archivo temporalmente y lo limpiamos automáticamente.',
  manualControlTip: 'CONTROL TOTAL SOBRE CORRECCIONES INDIVIDUALES Y PERFILES DE COLOR.',
  serverUnavailable: 'CONEXIÓN CON EL SERVIDOR REQUERIDA',
  serverUnavailableDesc: 'La conversión de color (CMYK/Gris) y el Magic Fix no están disponibles actualmente. Por favor, verifica tu conexión o inténtalo más tarde.',
  retry: 'Reintentar / Recargar',
  profileLabel: 'Perfil:',
  outputIntentLabel: 'OutputIntent:',
  bleedLabel: 'Sangrado:',
  standardDpiLabel: 'DPI Estándar:',
  verified: 'Verificado ✅',
  embedded: 'Incrustado',
  real3mmBox: '3mm Reales (Geometría Box)',
  highEndPrint: '300 (Gama Alta)',
  technicalNoteTitle: 'Nota Técnica de Pre-impresión',
  technicalNoteDesc: 'Este documento ha sido optimizado profesionalmente para la producción en imprenta.',
  outputIntentExplain: 'Se ha incrustado un OutputIntent PDF/X (GTS_PDFX) válido para garantizar la consistencia del color en RIPs profesionales.',
  bypassExplain: 'No se aplicó conversión de color a los objetos conformes existentes porque ya coincidían con el perfil solicitado.',
  rewriteExplain: 'El archivo ha sido estabilizado estructuralmente con Ghostscript pdfwrite para asegurar la incrustación de fuentes e integridad xref.',
  negativeStatement: 'No se realizaron más transformaciones de color después de la finalización del OutputIntent.',
  closeNote: 'Cerrar Nota',
  complianceSummaryTitle: 'Resumen de Cumplimiento de Pre-impresión',
  labelCertificateId: 'ID de Certificado:',
  labelEngineVersion: 'Versión del Motor:',
  labelRiskLevel: 'Nivel de Riesgo:',
  labelOutputIntent: 'Output Intent:',
  labelStructure: 'Estructura:',
  labelConversion: 'Conversión CMYK:',
  labelProcessing: 'Procesamiento:',
  labelTransparency: 'Transparencia:',
  labelBleed: 'Sangrado:',
  statusVerified: 'Verificado (GTS_PDFX)',
  statusSkipped: 'Omitido (Conforme)',
  statusStabilized: 'Estabilizado via Rewrite',
  statusPreserved: 'Preservada',
  statusApplied: 'Aplicado',
  riskGreen: 'VERDE (Seguro para Producción)',
  riskAttention: 'ATENCIÓN (Requiere Revisión)',
  riskBlocking: 'BLOQUEANTE (Rechazado por Preflight)',
  labelInkCoverage: 'Carga de Tinta (TAC):',
  labelMaxTac: 'Densidad Máx. Tinta:',
  labelWorstPage: 'Peor Página:',
  labelTacLimit: 'Límite Densidad:',
  tacWarningDrying: 'La densidad de tinta puede causar problemas de secado o repinte en prensa.',
  tacVerified: 'Verificado dentro de límites',
  labelOverprint: 'Sobreimpresión Negro:',
  statusOverprintOk: 'Verificado ✅',
  statusOverprintRisk: 'Riesgo de Reserva',
  overprintWarningKnockout: 'El texto negro puede hacer reserva sobre las tintas inferiores, causando halos o desajuste.',
  overprintWarningRegistration: 'Se detectó color de registro (100% CMYK) en el arte, lo que puede causar artefactos.',
  overprintWarningRichBlack: 'Texto en negro enriquecido en fuentes pequeñas; se recomienda K-único para mayor nitidez.',
  spotTitle: 'Política de Tintas Directas (Spot)',
  spotLabelDetected: 'Tintas Directas:',
  spotLabelPolicy: 'Política:',
  spotStatusNone: 'NINGUNA',
  spotPolicyStrict: 'CMYK Estricto (Offset)',
  spotPolicyConvert: 'Convertir a CMYK (Digital)',
  spotRiskGreen: 'VERDE',
  spotRiskAttention: 'ATENCIÓN',
  spotRiskBlocking: 'BLOQUEANTE',
  spotWarnWhitelistOnly: 'Solo se detectaron tintas técnicas (lista permitida de imprenta).',
  spotWarnNonWhitelist: 'Tintas directas fuera de la lista permitida para este perfil.',
  spotNoteTacIncluded: 'Tintas directas incluidas en la estimación de TAC (conversión Spot→CMYK).',
  spotNoteRegistration: 'Color de registro detectado (/All o /Registration); prohibido en arte.',
  spotNoteSpotsInText: 'Tintas directas en texto; la conversión puede afectar la nitidez tipográfica.',
  bleedMethod: 'Método de Sangrado:',
  bleedMethodScale: 'Escalado Centrado (V3)',
  bleedMethodBox: 'Ajuste de Cajas (Margen Real)',
  bleedScaleWarning: 'Escalado agresivo detectado (>4%). Los márgenes de seguridad están comprimidos.',
  'admin.title': 'Centro de Control Admin',
  'admin.subtitle': 'SRE COCKPIT & SALUD DEL SISTEMA',
  'admin.range.24h': 'Últimas 24 Horas',
  'admin.range.7d': 'Últimos 7 Días',
  'admin.range.30d': 'Últimos 30 Días',
  'admin.refresh.off': 'Refresco Manual',
  'admin.tabs.overview': 'Vista General',
  'admin.tabs.tenants': 'Clientes',
  'admin.tenants.tenant': 'Identidad Cliente',
  'admin.tenants.total': 'Volumen Tráfico',
  'admin.tenants.success': 'Fiabilidad %',
  'admin.tenants.latency': 'Latencia Sincro',
  'admin.tenants.last': 'Último Pulso',
  'admin.tabs.jobs': 'Trabajos',
  'admin.tabs.errors': 'Errores',
  'admin.tabs.audit': 'Auditoría',
  'admin.tabs.controls': 'Controles ⚠️',
  'admin.kpi.totalJobs': 'Total Trabajos',
  'admin.kpi.successRate': 'Tasa de Éxito',
  'admin.kpi.avgLatency': 'Latencia Media',
  'admin.kpi.deltaRate': 'Mejora Delta',
  'admin.kpi.costProxy': 'Coste Proxy',
  'admin.kpi.p95Latency': 'Latencia P95',
  'admin.kpi.queueBacklog': 'Cola Pendiente',
  'admin.kpi.oldestAge': 'Trabajo más Antiguo',
  'admin.queue.title': 'Matriz de Rendimiento de Colas',
  'admin.jobs.filterTenant': 'Filtrar por ID de Inquilino...',
  'admin.jobs.filterType': 'Filtrar por Tipo de Proceso...',
  'admin.jobs.all': 'Todos los Estados',
  'admin.jobs.empty': 'No se encontraron transacciones',
  'admin.audit.filterTenant': 'Buscar en registros de auditoría...',
  'admin.audit.empty': 'No se encontraron eventos de auditoría',
  'admin.errors.code': 'Código de Fallo',
  'admin.errors.count': 'Recuento de Pilas',
  'admin.errors.lastSeen': 'Última Observación',
  'common.loading': 'Cargando secuencia...',
  'common.na': 'N/D',
  partialCalculationTitle: 'Cálculo parcial: tarifas incompletas',
  governedQuoteIncompleteRatesNotice: 'Esta simulación no constituye un precio comercial válido debido a tarifas de fabricación ausentes o no calibradas en el nodo:',
  reviewCardIncompleteRatesNotice: 'Esta cotización no se presenta como un precio comercial válido debido a tarifas de fabricación ausentes o no calibradas:',
  realQuotationOutcome: 'Resultado de Cotización Real',
  diagnosticOutcome: 'Resultado Diagnóstico',
  customerPriceBeforeTax: 'Precio al Cliente (Antes de Impuestos)',
  partialDiagnosticSubtotalTitle: 'Subtotal Parcial Diagnóstico (Tarifas Incompletas)',
  partialDiagnosticSubtotalBadge: 'Subtotal Parcial Diagnóstico',
  perCopyNet: '€ {{price}} / ej. (Neto)',
  chatInputPlaceholder: 'Describe el libro o adjunta un PDF…',
  attachPdfTooltip: 'Adjuntar un PDF',
  pdfOnlyError: 'Únicamente se admiten archivos en formato PDF.',
  uploadingQuote: 'Subiendo presupuesto…',
  selectThisVariant: 'Seleccionar variante',
  analyzingPdfDocument: 'Analizando PDF…',
  pdfDetectedLanguage: 'Documento detectado: {{language}}',
  pdfExtractionComplete: 'Extracción completada. Presupuesto listo para revisión.',
  pdfUploadErrorMessage: 'Error al procesar el presupuesto PDF.',
  pdfUploadedUserMsg: '[PDF subido]: {{filename}}',
  'onboarding.title': 'Configuración de Imprenta',
  'onboarding.subtitle': 'Configura tu planta, maquinaria, catálogo de papeles y tarifas con asistencia guiada.',
  'onboarding.sections': 'Secciones de Configuración',
  'onboarding.findSettingOrHelp': 'Buscar un ajuste o consultar ayuda...',
  'onboarding.guideMe': 'Guíame',
  'onboarding.continueSetup': 'Continuar Configuración',
  'onboarding.setupOverview': 'Resumen y Preparación',
  'onboarding.activeModule': 'Módulo Activo',
  'onboarding.nextAction': 'Acción Recomendada',
  'onboarding.saveChanges': 'Guardar Cambios',
  'onboarding.unsavedChangesWarning': 'Tienes cambios sin guardar. Salir de esta sección descartará los cambios. ¿Deseas continuar?',
  'onboarding.collapseSidebar': 'Colapsar barra lateral',
  'onboarding.expandSidebar': 'Expandir barra lateral',
  'onboarding.reviewDetails': 'Revisar Detalles',
  'onboarding.quickSpecs': 'Especificaciones Rápidas',
  'onboarding.mode.assistant': 'Asistente IA',
  'onboarding.mode.manual': 'Tarifas manuales',
  'onboarding.mode.descAssistant': 'Describe un trabajo o adjunta un presupuesto en PDF. El asistente extraerá especificaciones para calibración guiada.',
  'onboarding.mode.descManual': 'Edita directamente las tarifas industriales: costes base, puesta a punto, clics, papel y encuadernación.',
  'onboarding.startOption.upload': 'Subir PDF de presupuesto o ficha de trabajo',
  'onboarding.startOption.uploadDesc': 'Sube un presupuesto o ficha en PDF para extraer automáticamente especificaciones y precios.',
  'onboarding.startOption.describe': 'Describir un producto',
  'onboarding.startOption.describeDesc': 'Cuéntale al asistente en lenguaje natural sobre un libro que hayas impreso anteriormente.',
  'onboarding.startOption.manual': 'Introducir especificaciones de producto manualmente',
  'onboarding.startOption.manualDesc': 'Abre el editor manual de especificaciones y tarifas para rellenar los datos directamente.',
  'onboarding.tutorial.stepOf': 'Paso {{current}} de {{total}}',
  'onboarding.tutorial.next': 'Siguiente',
  'onboarding.tutorial.back': 'Atrás',
  'onboarding.tutorial.exit': 'Salir del Tutorial',
  'onboarding.tutorial.doThisNow': 'Hacer esto ahora',
  'onboarding.help.searchPlaceholder': 'Buscar ajustes, módulos, términos (ej. Munken, CMYK, NIF, transporte)...',
  'onboarding.help.noResults': 'No se encontraron temas de ayuda ni ajustes coincidentes.',
  'onboarding.help.tip': 'Pulsa Esc para cerrar, ↑↓ para navegar, Enter para seleccionar.',
  'pricing.assistant.title': 'Asistente de Precios',
  'pricing.assistant.header': 'Asistente Multilingüe de Precios',
  'pricing.assistant.subtitle': 'Describe un libro producido o adjunta un documento PDF con un presupuesto.',
  'pricing.assistant.headerTag': 'Ingesta y Calibración Multilingüe de PDF',
  'pricing.assistant.inspectEvidence': 'Inspeccionar Evidencia',
  'pricing.assistant.busyTitle': 'El asistente IA está ocupado ahora mismo',
  'pricing.assistant.busyDesc': 'Tu configuración está a salvo y nada se ha guardado. Puedes reintentarlo o introducir los datos manualmente.',
  'pricing.assistant.orExample': 'O prueba un mensaje de ejemplo:',
  'pricing.assistant.analyzing': 'Analizando especificaciones...',
  'pricing.assistant.proposedTitle': 'Actualizaciones de Libro Propuestas Listas',
  'pricing.assistant.requiresConfirmation': 'Requiere Confirmación',
  'pricing.assistant.proposedDesc': 'El asistente extrajo los detalles de tu mensaje. Revisa el resumen estructurado a la derecha y confirma para aplicar.',
  'pricing.assistant.applyBtn': 'Aplicar Detalles Extraídos',
  'pricing.assistant.sendBtn': 'Enviar',
  'pricing.assistant.retryBtn': 'Reintentar',
  'pricing.assistant.drawerTitle': 'Evidencia de Presupuesto y Detalles de Variante',
  'pricing.assistant.drawerSubtitle': 'Desglose detallado del documento activo y la oferta comercial seleccionada',
  'pricing.assistant.activeExtractedDoc': 'Documento Activo Extraído',
  'pricing.assistant.fileLabel': 'Archivo:',
  'pricing.assistant.evidenceIdLabel': 'ID de Evidencia:',
  'pricing.assistant.languageLabel': 'Idioma:',
  'pricing.assistant.pageCountLabel': 'Páginas PDF:',
  'pricing.assistant.printhouseLabel': 'Imprenta:',
  'pricing.assistant.selectedOfferTitle': 'Oferta Seleccionada',
  'pricing.assistant.quantityLabel': 'Cantidad:',
  'pricing.assistant.manufacturingLabel': 'Fabricación:',
  'pricing.assistant.transportLabel': 'Transporte:',
  'pricing.assistant.quotedTotalLabel': 'Total Ofertado:',
  'pricing.assistant.quotedUnitLabel': 'Precio Unitario Ofertado:',
  'pricing.assistant.validationLabel': 'Validación:',
  'pricing.assistant.sourceTextLabel': 'Texto fuente:',
  'pricing.assistant.noOfferSelected': 'Aún no se ha seleccionado ninguna variante de oferta específica.',
  'pricing.assistant.noEvidenceAttached': 'Actualmente no hay ningún documento de presupuesto adjunto.',
  'pricing.assistant.physicalSpecs': 'Especificaciones Físicas Extraídas',
  'pricing.assistant.formatLabel': 'Formato:',
  'pricing.assistant.bindingLabel': 'Encuadernación:',
  'pricing.assistant.finishingLabel': 'Acabados:',
  'pricing.assistant.interiorPagesLabel': 'Páginas Interiores:',
  'quoteReview.pagesExtracted': '{{count}} página(s) extraída(s)',
  'quoteReview.optionLabel': 'Opción {{idx}}: €{{price}} (Fabricación)',
  'quoteReview.unitsLabel': '{{count}} unidades',
  'quoteReview.consistent': '✓ Correcto',
  'quoteReview.inconsistent': '⚠ Inconsistencia Detectada',
  'quoteReview.readyForCalibration': 'Listo para Revisión de Calibración',
  'quoteReview.productTitle': 'Título del Producto',
  'quoteReview.formatAndBinding': 'Formato y Encuadernación',
  'quoteReview.variantsForCopies': 'Variantes de Oferta Comercial Extraídas para {{copies}} ejemplares ({{count}} variantes)',
  'quoteReview.quantitiesAndPrices': 'Cantidades y Precios Comerciales Extraídos ({{count}})',
  'quoteReview.mfgOffered': 'Precio Ofertado Fabricación:',
  'quoteReview.transportSep': 'Transporte Separado:',
  'quoteReview.notSpecified': 'No especificado',
  'quoteReview.totalOffered': 'Total Ofertado Proveedor:',
  'quoteReview.unitOffered': 'Unitario Ofertado:',
  'quoteReview.vendorDisclaimer': 'Precio ofertado por el proveedor • Coste interno se calcula tras calibración',
  'quoteReview.selectVariantBtn': 'Seleccionar variante (€{{price}})',
  'quoteReview.unitPriceDiffWarning': 'El precio unitario indicado (€{{quoted}}) difiere del total calculado dividido por la cantidad (€{{computed}}).',
  'quoteReview.showOriginalText': 'Mostrar texto original y términos normalizados',
  'quoteReview.hideDetails': 'Ocultar detalles',
  'quoteReview.normalizedTerms': 'Términos Normalizados:',
  'quoteReview.rawExtractedText': 'Texto Extraído Original:',
  'quoteReview.noneDetected': 'Ninguno detectado',
  'quoteReview.editInterpretation': 'Editar Interpretación',
  'quoteReview.saveCorrections': 'Guardar Correcciones',
  'quoteReview.saving': 'Guardando...',
  'quoteReview.ignoreDocument': 'Ignorar Documento',
  'quoteReview.markValidOffersReady': 'Marcar Ofertas Válidas Listas para Calibración',
  'quoteReview.docIgnored': 'Documento {{filename}} ignorado.',
  'pricing.mode.assistant': 'Asistente IA',
  'pricing.mode.manual': 'Tarifas manuales',
  'pricing.mode.priceBooks': 'Tarifarios Comerciales',
  'pricing.mode.node': 'Nodo:',
  'pricing.mode.manualHeading': 'Costes Industriales y Tarifarios de Fabricación',
  'setup.summary.account': '1. Cuenta y Plantas',
  'setup.summary.production': '2. Preparación Operativa',
  'setup.summary.pricing': '3. Tarifas Industriales',
  'setup.summary.coreStatus': 'Estado de Configuración Base',
  'setup.summary.status': 'Estado:',
  'setup.summary.configured': 'Configurado',
  'setup.summary.inProgress': 'En Curso',
  'setup.summary.notStarted': 'No Iniciado',
  'setup.summary.complete': 'CONFIGURACIÓN COMPLETA',
  'setup.summary.incomplete': 'CONFIGURACIÓN INCOMPLETA',
  'setup.summary.readyDesc': 'Listo para el panel y revisión del marketplace',
  'setup.summary.incompleteDesc': 'Completa los 8 módulos siguientes',
  'setup.tabs.overview': 'Resumen de Configuración',
  'setup.tabs.company': 'Perfil de la Empresa',
  'setup.tabs.sites': 'Plantas de Producción',
  'setup.tabs.machines': 'Parque de Maquinaria',
  'setup.tabs.capabilities': 'Capacidades de Máquina',
  'setup.tabs.materials': 'Materiales y Papel',
  'setup.tabs.capacity': 'Capacidad de Producción',
  'setup.tabs.leadTimes': 'Plazos de Entrega y ANS',
  'setup.tabs.pricing': 'Precios Industriales',
  'setup.tabs.shipping': 'Envíos y Logística',
  'setup.tabs.integrations': 'Integraciones y Webhooks',
  'setup.tabs.marketplace': 'Revisión del Mercado',
  'setup.tabs.completeBadge': 'Completado',
  'tutorial.step1.title': 'Selector de Secciones de Configuración',
  'tutorial.step1.desc': 'Navega fácilmente entre los 8 módulos de configuración (Perfil de Empresa, Parque de Maquinaria, Materiales, Tarifas y más) o revisa tu estado global desde este control de la barra superior.',
  'tutorial.step1.action': 'Menú de Secciones',
  'tutorial.step2.title': 'Asistente IA de Calibración de Precios',
  'tutorial.step2.desc': 'Nuestra experiencia principal de tarificación. Simplemente describe un libro producido previamente o sube un presupuesto en PDF, y Hawkeye resolverá y calibrará tus matrices de costes.',
  'tutorial.step2.action': 'Abrir Asistente de Precios',
  'tutorial.step3.title': 'Alternancia Instantánea a Modo Manual',
  'tutorial.step3.desc': '¿Prefieres tarifarios tradicionales en hoja de cálculo? Cambia a Manual en cualquier momento con un clic. Tus borradores, presupuestos adjuntos y cálculos permanecen intactos.',
  'tutorial.step3.action': 'Inspeccionar Selector de Modo',
  'tutorial.step4.title': 'Buscar Ajustes y Consultar Ayuda',
  'tutorial.step4.desc': 'Busca cualquier término de impresión, sustrato o parámetro de configuración rápidamente sin tener que adivinar dónde se encuentra.',
  'tutorial.step4.action': 'Abrir Búsqueda de Ayuda',
  'setup.overview.modulesHeading': 'Módulos Operativos (8 Pasos)',
  'setup.overview.module1.title': '1. Perfil de Empresa',
  'setup.overview.module1.desc': 'Identidad legal de la empresa, país principal, NIF/CIF/IVA y contacto administrativo.',
  'setup.overview.module2.title': '2. Plantas de Producción',
  'setup.overview.module2.desc': 'Plantas físicas de impresión, direcciones operativas, ciudad y huso horario.',
  'setup.overview.module3.title': '3. Parque de Maquinaria',
  'setup.overview.module3.desc': 'Prensas offset, dispositivos digitales, mesas de corte, encuadernadoras y acabado.',
  'setup.overview.module4.title': '4. Capacidades de Maquinaria',
  'setup.overview.module4.desc': 'Gestión de color (CMYK, Barniz UVI, Tinta Blanca), formatos máximos de pliego y normas PDF/X.',
  'setup.overview.module5.title': '5. Materiales y Sustratos',
  'setup.overview.module5.desc': 'Catálogo de sustratos, gramajes de papel, formatos de pliego y compatibilidad de acabado.',
  'setup.overview.module6.title': '6. Capacidad Productiva',
  'setup.overview.module6.desc': 'Límites de producción diaria, turnos de trabajo, calendario laboral y asignaciones.',
  'setup.overview.module7.title': '7. Plazos de Entrega',
  'setup.overview.module7.desc': 'Horas de corte diario por planta, zonas horarias, acuerdos de nivel de servicio (SLA) y plazos.',
  'setup.overview.module8.title': '8. Tarifas Industriales',
  'setup.overview.module8.desc': 'Tarifas base de fabricación, costes de papel por kg, operaciones de encuadernación y portes.',
  'setup.module.cta.review': 'Revisar / Editar',
  'setup.module.cta.continue': 'Continuar Configuración',
  'setup.module.cta.start': 'Iniciar Configuración',
  'setup.module.missingRequirements': 'Requisitos Pendientes:',
  'setup.module.requiresSites': 'Requiere al menos 1 Planta de Producción',
  'setup.module.requiresMachines': 'Requiere al menos 1 Máquina',
  'setup.nextStep.company': 'Datos de identidad legal y NIF/IVA requeridos para facturación',
  'setup.nextStep.sites': 'Se requiere al menos una planta operativa para configurar las prensas',
  'setup.nextStep.machines': 'Se necesitan prensas y líneas de acabado para verificar capacidades de impresión',
  'setup.nextStep.capabilities': 'Define formatos de pliego admitidos, tintas y tipos de encuadernación',
  'setup.nextStep.materials': 'Gramajes de sustrato y catálogo de papel requeridos',
  'setup.nextStep.pricing': 'Calibra las tarifas de fabricación para generar presupuestos comerciales',
  'setup.nextStep.marketplace': 'Todos los requisitos operativos completos. Finaliza la preparación para el marketplace.',
  'setup.error.retryLoading': 'Reintentar Carga',
  'settings.title': 'Configuración Global',
  'settings.subtitle': 'Configuración de plataforma, perfil del tenant y preferencias del operador.',
  'settings.nav.general': 'General',
  'settings.nav.notifications': 'Notificaciones',
  'settings.nav.security': 'Seguridad',
  'settings.nav.integrations': 'Integraciones',
  'settings.nav.appearance': 'Apariencia',
  'settings.general.title': 'Ajustes Generales',
  'settings.general.desc': 'Preferencias personales y parámetros organizativos del tenant.',
  'settings.general.personalSection': 'Preferencias Personales y Regionales',
  'settings.general.tenantSection': 'Perfil de la Imprenta (Tenant)',
  'settings.general.language': 'Idioma de la Interfaz',
  'settings.general.timezone': 'Zona Horaria',
  'settings.general.region': 'Región de Infraestructura Cloud',
  'settings.general.regionNotice': 'Nodo Soberano Primario UE (Gestionado)',
  'settings.general.companyName': 'Razón Social de la Empresa',
  'settings.general.taxId': 'NIF / CIF / Identificador Fiscal',
  'settings.general.country': 'País de Operación',
  'settings.general.address': 'Dirección de la Sede Central',
  'settings.general.currency': 'Moneda Comercial de Cálculo',
  'settings.appearance.title': 'Apariencia y Visualización',
  'settings.appearance.desc': 'Modo de tema, densidad del layout y preferencias de animación.',
  'settings.appearance.theme': 'Esquema de Color',
  'settings.appearance.dark': 'Oscuro Industrial',
  'settings.appearance.light': 'Claro Corporativo',
  'settings.appearance.density': 'Densidad de la Interfaz',
  'settings.appearance.densityDesc': 'Ajusta el espaciado y altura de fila en tablas, formularios y vistas.',
  'settings.appearance.comfortable': 'Cómoda (Estándar)',
  'settings.appearance.compact': 'Compacta (Alta Densidad)',
  'settings.appearance.animations': 'Animaciones de la Interfaz',
  'settings.appearance.animationsDesc': 'Activar transiciones suaves. Respeta automáticamente la preferencia prefers-reduced-motion del sistema.',
  'settings.notifications.title': 'Notificaciones de Eventos',
  'settings.notifications.desc': 'Gestiona las suscripciones operativas y canales de alerta para tu tenant y rol.',
  'settings.notifications.email': 'Correo de Notificaciones',
  'settings.notifications.roleNoticePrinthouse': 'Ámbito: Operador de Imprenta. Mostrando únicamente operaciones de planta y despachos de fabricación.',
  'settings.notifications.roleNoticeSuperadmin': 'Ámbito: Super Administrador. Eventos de plataforma, detección de anomalías y despliegues habilitados.',
  'settings.notifications.eventJobDispatch': 'Nuevo Despacho de Fabricación',
  'settings.notifications.eventJobDispatchDesc': 'Alerta cuando una orden aprobada se despacha a esta planta.',
  'settings.notifications.eventPreflightFail': 'Fallo de Pre-vuelo / Incidencia Crítica',
  'settings.notifications.eventPreflightFailDesc': 'Alerta inmediata cuando un archivo entrante no supera la verificación PDF/X.',
  'settings.notifications.eventSlaWarning': 'Aviso de SLA y Hora de Corte',
  'settings.notifications.eventSlaWarningDesc': 'Alerta cuando el plazo de fabricación se aproxima a la hora de corte de la planta.',
  'settings.notifications.eventPlatformAnomalies': 'Detección de Anomalías de Plataforma (Superadmin)',
  'settings.notifications.eventPlatformAnomaliesDesc': 'Alertas del motor de inteligencia por picos de latencia o activación de circuit-breakers.',
  'settings.notifications.eventDeployments': 'Eventos de Despliegue de Infraestructura (Superadmin)',
  'settings.notifications.eventDeploymentsDesc': 'Notifica sobre despliegues canario, migraciones y actualizaciones de malla federada.',
  'settings.security.title': 'Seguridad y Control de Acceso',
  'settings.security.desc': 'Duración de sesión, refuerzo de autenticación y registro de auditoría aislado por tenant.',
  'settings.security.sessionTimeout': 'Tiempo de Inactividad Máximo (minutos)',
  'settings.security.sessionTimeoutDesc': 'La sesión del cliente finalizará automáticamente tras inactividad. Limitada por el token del servidor.',
  'settings.security.mfa': 'Autenticación de Dos Factores (2FA / TOTP)',
  'settings.security.mfaStatusDisabled': 'Desactivado (Requiere Alta)',
  'settings.security.mfaStatusActive': 'Activo (Protegido por App Autenticadora)',
  'settings.security.mfaSetupBtn': 'Configurar App Autenticadora',
  'settings.security.mfaDisableBtn': 'Desactivar 2FA',
  'settings.security.mfaModalSetupTitle': 'Configurar Autenticación de Dos Factores',
  'settings.security.mfaSecretLabel': 'Clave Secreta (Entrada Manual)',
  'settings.security.mfaRecoveryCodesLabel': 'Códigos de Recuperación (Guardar en lugar seguro — solo se muestran una vez)',
  'settings.security.mfaCodePrompt': 'Introduce el código de 6 dígitos de tu app autenticadora',
  'settings.security.mfaConfirmBtn': 'Verificar y Activar',
  'settings.security.mfaDisableTitle': 'Desactivar Autenticación de Dos Factores',
  'settings.security.mfaPasswordPrompt': 'Introduce tu contraseña para confirmar la desactivación',
  'settings.security.mfaDisableConfirmBtn': 'Confirmar Desactivación',
  'settings.security.sessionsTitle': 'Sesiones Activas de Usuario',
  'settings.security.sessionsDesc': 'Supervisa dispositivos autorizados y revoca accesos en todas las ubicaciones.',
  'settings.security.sessionCurrent': 'SESIÓN ACTUAL',
  'settings.security.sessionRevoke': 'Revocar',
  'settings.security.sessionRevokeAll': 'Revocar Todas las Demás Sesiones',
  'settings.security.sessionIp': 'Dirección IP',
  'settings.security.sessionAgent': 'Dispositivo / Agente',
  'settings.security.sessionCreated': 'Iniciada',
  'settings.security.sessionLastActive': 'Última Actividad',
  'settings.security.sessionRevokedSuccess': 'Sesión revocada correctamente.',
  'settings.security.sessionRevokeAllSuccess': 'Todas las demás sesiones han sido revocadas.',
  'settings.security.auditLog': 'Explorador de Auditoría',
  'settings.security.auditLogDesc': 'Registro inmutable en vivo de acciones operativas para este tenant.',
  'settings.security.auditEmpty': 'Aún no hay registros de auditoría para este tenant.',
  'settings.integrations.title': 'Conectores y Webhooks',
  'settings.integrations.desc': 'Puentes industriales MIS/ERP, automatización de taller JDF/JMF y webhooks de salida.',
  'settings.integrations.webhookUrl': 'URL de Webhook para Despacho de Producción',
  'settings.integrations.webhookSecret': 'Secreto de Firma Webhook (HMAC-SHA256)',
  'settings.integrations.webhookSecretHint': 'Las cargas útiles se firman con HMAC-SHA256 en la cabecera X-PPOS-Signature.',
  'settings.integrations.rotateSecretBtn': 'Rotar Secreto',
  'settings.integrations.rotateSecretSuccess': 'Secreto de firma de webhook rotado con éxito.',
  'settings.integrations.testWebhookBtn': 'Encolar Webhook de Prueba',
  'settings.integrations.testPayloadSuccess': 'Evento de prueba encolado en el buzón de salida.',
  'settings.integrations.webhookSubscriptionsTitle': 'Suscripciones Activas de Webhooks',
  'settings.integrations.recentDeliveriesTitle': 'Entregas Recientes en Buzón de Salida',
  'settings.integrations.resendBtn': 'Reenviar',
  'settings.integrations.slackTitle': 'Alertas Operativas en Slack',
  'settings.integrations.slackToggle': 'Canal de Alertas Slack',
  'settings.integrations.slackDesc': 'Enviar alertas de fabricación, calibración y SLA al canal de operaciones.',
  'settings.integrations.slackWebhook': 'URL de Webhook Entrante de Slack',
  'settings.integrations.slackChannel': 'Nombre del Canal',
  'settings.integrations.slackTestBtn': 'Enviar Alerta de Prueba',
  'settings.integrations.slackTestSuccess': 'Alerta de prueba entregada en Slack con éxito.',
  'settings.integrations.slackSaved': 'Configuración de integración con Slack guardada.',
  'settings.integrations.connectorsTitle': 'Conectores Industriales MES / Taller',
  'settings.integrations.statusActive': 'Conectado',
  'settings.integrations.statusPending': 'Requiere Credenciales',
  'settings.integrations.statusRoadmap': 'Conector de Catálogo',
  'settings.save': 'Guardar Cambios',
  'settings.saving': 'Guardando configuración...',
  'settings.saved': 'Cambios Guardados',
  'settings.error': 'Error al guardar configuración. Reintenta.',
  'settings.savedLocalOnly': 'Preferencias guardadas localmente. Sincronización del perfil en servidor pendiente o sin conexión.',
  'settings.savedProfileOnly': 'Perfil guardado. Sincronización de notificaciones pendiente o sin conexión.',
  'settings.notifications.saveFailed': 'No se pudieron actualizar las preferencias de notificación en el servidor.',
  'settings.security.mfaStatusPending': 'MFA No Configurado',
  'settings.security.mfaDetailsBtn': 'Configurar 2FA',
  'settings.security.openForensics': 'Abrir Explorador Forense →',
  'settings.security.loadingAudit': 'Cargando registro de auditoría del tenant...',
  'settings.security.mfaModalTitle': 'Configuración de Autenticación en Dos Pasos',
  'settings.security.mfaModalStatus': 'Escanea el código QR o introduce la clave secreta en tu app autenticadora.',
  'settings.security.mfaModalArchitecture': 'Pautas de Seguridad Industrial:',
  'settings.security.mfaModalWebAuthn': 'Llaves de seguridad por hardware FIDO2 / WebAuthn para terminales de planta.',
  'settings.security.mfaModalTotp': 'Protocolo de respaldo de aplicación autenticadora RFC 6238 TOTP.',
  'settings.security.mfaModalIsolation': 'Sal criptográfica aislada por tenant y exigencia biométrica por puesto.',
  'settings.security.mfaCloseBtn': 'Cerrar',
  'settings.integrations.testPayloadUnavailable': 'Pasarela de despacho de webhooks en vivo no activa en este entorno.',
  'settings.integrations.slackPendingNotice': 'Integración con Slack activa. La URL del webhook se almacena cifrada en el servidor.',
  'nav.governance': 'Gobernanza Global',
  'nav.federation': 'Federación',
  'nav.dashboard': 'Panel Principal',
  'nav.printhouses': 'Imprentas',
  'nav.printhouse-onboarding': 'Incorporación de Imprentas',
  'nav.onboarding-observability': 'Observabilidad de Incorporación',
  'nav.jobs': 'Trabajos Entrantes',
  'nav.preflight': 'Servicio de Preflight',
  'nav.manufacturing': 'Cola de Fabricación',
  'nav.machines': 'Maquinaria',
  'nav.materials': 'Materiales y Papel',
  'nav.pricing': 'Perfiles de Tarifas',
  'nav.intelligence': 'Capa de Inteligencia',
  'nav.marketplace': 'Mercado Digital',
  'nav.financials': 'Operaciones Financieras',
  'nav.billing-usage': 'Facturación y Planes',
  'nav.production-monitoring': 'Monitorización de Producción',
  'nav.industrial': 'Operaciones Industriales',
  'nav.beta-runtime': 'Entorno Beta',
  'nav.beta-cohorts': 'Cohortes Beta',
  'nav.beta-governance': 'Gobernanza Beta',
  'nav.tenants': 'Gestión de Tenants',
  'nav.audit': 'Registros de Auditoría',
  'nav.settings': 'Configuración',
  'nav.printhouseSetup': 'Configuración de Imprenta',
  'nav.helpConsole': 'Consola de Ayuda del SO',
  'nav.logout': 'Cerrar Sesión',
  'nav.navigation': 'Navegación',
  'nav.collapseSidebar': 'Colapsar barra lateral',
  'nav.expandSidebar': 'Expandir barra lateral',
  'setup.section.company': 'Perfil de la Empresa',
  'setup.section.companyDesc': 'Identidad legal de la empresa, país principal, NIF/CIF y contacto administrativo.',
  'setup.section.sites': 'Plantas de Producción',
  'setup.section.sitesDesc': 'Plantas físicas de impresión, direcciones operativas, ciudad y zona horaria.',
  'setup.section.machines': 'Parque de Maquinaria',
  'setup.section.machinesDesc': 'Prensas offset, dispositivos digitales, mesas de corte, encuadernadoras y acabado.',
  'setup.section.capabilities': 'Capacidades de Máquina',
  'setup.section.capabilitiesDesc': 'Gestión de color (CMYK, Barniz UVI, Tinta Blanca), formatos de pliego y especificaciones PDF/X.',
  'setup.section.materials': 'Materiales y Papel',
  'setup.section.materialsDesc': 'Catálogo de soportes, gramajes de papel, tamaños de hoja y compatibilidad de acabado.',
  'setup.section.capacity': 'Capacidad de Producción',
  'setup.section.capacityDesc': 'Límites de rendimiento diario, turnos de trabajo, calendario operativo y asignación de trabajos.',
  'setup.section.leadTimes': 'Plazos de Entrega y ANS',
  'setup.section.leadTimesDesc': 'Horas de corte diarias por planta, cortes por zona horaria, ANS y calendarios de entrega.',
  'setup.section.pricing': 'Precios Industriales y Tarifas',
  'setup.section.pricingDesc': 'Tarifas base de fabricación, costes de papel por kg, operaciones de encuadernación y transporte.',
  'setup.section.shipping': 'Envíos y Logística',
  'setup.section.shippingDesc': 'Transportistas, opciones de embalaje, tablas de tarifas de flete y seguimiento de envíos.',
  'setup.section.integrations': 'Integraciones y Webhooks',
  'setup.section.integrationsDesc': 'Puentes con MIS/ERP industrial, automatización de taller JDF/JMF y webhooks externos.',
  'setup.section.marketplace': 'Preparación para el Mercado Digital',
  'setup.section.marketplaceDesc': 'Revisar criterios de calificación, publicar capacidad en la red y comenzar a recibir pedidos.',
  'company.title': 'Perfil de la Empresa',
  'company.legalName': 'Razón Social de la Empresa',
  'company.tradingName': 'Nombre Comercial / Público',
  'company.country': 'País Principal',
  'company.city': 'Ciudad / Municipio',
  'company.address': 'Dirección Social Registrada',
  'company.postalCode': 'Código Postal',
  'company.phone': 'Teléfono Oficial',
  'company.website': 'Sitio Web de la Empresa',
  'company.contactName': 'Persona de Contacto Principal',
  'company.taxId': 'NIF / CIF / Identificador Fiscal',
  'company.registrationId': 'Número de Registro Mercantil (Opcional)',
  'company.saveBtn': 'Guardar Perfil de Empresa',
  'company.savingBtn': 'Guardando Cambios...',
  'jobs.title': 'Trabajos de Fabricación Entrantes',
  'jobs.subtitle': 'Cabina Operativa — Despacho de Producción',
  'jobs.refresh': 'Actualizar',
  'jobs.statPending': 'Pendientes',
  'jobs.statActive': 'Activos',
  'jobs.statRejected': 'Rechazados',
  'jobs.statExpired': 'Expirados',
  'jobs.thIdentity': 'Identificador de Trabajo',
  'jobs.thSpecs': 'Especificaciones y Política',
  'jobs.thCustomer': 'Cliente',
  'jobs.thStatus': 'Estado',
  'jobs.thActions': 'Acciones',
  'jobs.actionAccept': 'Aceptar',
  'jobs.actionReject': 'Rechazar',
  'jobs.actionStartProduction': 'Iniciar Producción',
  'jobs.actionComplete': 'Completar',
  'jobs.statusFinished': 'Terminado',
  'jobs.downloadBundle': 'Descargar Paquete',
  'jobs.emptyTitle': 'No se encontraron trabajos entrantes',
  'jobs.invalidPayload': 'Se recibió una respuesta de fabricación inválida del servidor',
  'jobs.errorTitle': 'Error de Canalización',
  'jobs.retry': 'Reintentar',
  'preflight.title': 'Consola Industrial de Preflight',
  'preflight.subtitle': 'Interfaz administrativa de alta densidad que gestiona operaciones reales de trabajos, lotes de matriz y telemetría forense directamente sobre la capa canónica de contrato V2.',
  'preflight.quotaUsage': 'Uso Global de Cuota',
  'preflight.allocated': 'asignado',
  'preflight.upstreamDirect': 'Contrato Directo Upstream',
  'preflight.tabJobs': 'Registro de Trabajos',
  'preflight.tabBatches': 'Lotes en Proceso',
  'preflight.tabAudit': 'Libro de Auditoría',
  'preflight.tabGovernance': 'Matriz de Gobernanza',
  'preflight.filterTenant': 'Filtrar ámbito por ID de Tenant...',
  'manufacturing.title': 'Sistema de Ejecución de Fabricación',
  'manufacturing.subtitle': 'Enrutamiento de taller industrial, catálogo de paquetes, historial de despacho y liquidación.',
  'manufacturing.tabIncoming': 'Trabajos Entrantes',
  'manufacturing.tabPackages': 'Paquetes de Fabricación',
  'manufacturing.tabHistory': 'Historial de Despacho',
  'manufacturing.tabMatching': 'Emparejamiento de Nodos',
  'manufacturing.tabBilling': 'Liquidación Financiera',
  'manufacturing.packagesCatalog': 'Catálogo de Paquetes de Fabricación',
  'manufacturing.packagesDesc': 'Capa segura de conexión que vincula documentos validados con bastidores físicos de producción.',
  'marketplace.title': 'Recepción de Pedidos del Mercado',
  'marketplace.subtitleSuperadmin': 'Recepción operativa de pedidos del mercado Budget, archivos de producción, sesiones de precios, validación de preflight y preparación de entrega.',
  'marketplace.subtitlePrinthouse': 'Pedidos asignados a su imprenta desde el mercado PrintPrice, archivos de producción, validación de preflight y preparación de entrega.',
  'marketplace.tabIntake': 'Entrada de Pedidos',
  'marketplace.tabSessions': 'Sesiones de Precios',
  'marketplace.tabReadiness': 'Preparación de Producción',
  'marketplace.tabHandoff': 'Entrega a Imprenta',
  'marketplace.tabAuctions': 'Subastas de Capacidad',
  'marketplace.tabAudit': 'Auditoría / Eventos',
  'marketplace.kpiNewOrders': 'Nuevos Pedidos',
  'marketplace.kpiFilesUploaded': 'Archivos Subidos',
  'marketplace.kpiPreflightReq': 'Preflight Requerido',
  'marketplace.kpiPaymentBlocked': 'Pago Bloqueado',
  'marketplace.kpiReadyHandoff': 'Listo para Entrega',
  'marketplace.kpiBlockedOrders': 'Pedidos Bloqueados',
  'marketplace.searchPlaceholder': 'Filtrar por Ref de Pedido, Email o ID...',
  'marketplace.thPublicRef': 'Ref. Pública',
  'marketplace.thCreated': 'Creado',
  'marketplace.thCustomer': 'Cliente / Sesión',
  'marketplace.thSpecs': 'Especificaciones',
  'marketplace.thPrinter': 'Impresor / Imprenta',
  'marketplace.thFiles': 'Archivos',
  'marketplace.thPreflight': 'Preflight',
  'marketplace.thPayment': 'Pago',
  'marketplace.thTotal': 'Total',
  'marketplace.thStatus': 'Estado Operativo',
  'marketplace.thActions': 'Acciones',
  'marketplace.viewOrder': 'Ver Pedido',
  'marketplace.emptyOrders': 'No se encontraron pedidos en el mercado',
  'dashboard.titleControlPlane': 'Plano de Control',
  'dashboard.titlePrinthouse': 'Portal de Imprenta',
  'dashboard.subtitleControlPlane': 'Inteligencia Operativa y Control de Misión',
  'dashboard.subtitlePrinthouse': 'Espacio Operativo y Despacho de Producción',
  'dashboard.kpiJobsToday': 'Trabajos Hoy',
  'dashboard.kpiActiveJobs': 'Trabajos Activos',
  'dashboard.kpiRealExtraction': 'Extracción Real',
  'dashboard.kpiCertifiable': 'Certificables',
  'dashboard.kpiRuntimeFailures': 'Fallos de Entorno',
  'dashboard.kpiArtifactStorage': 'Almacén de Artefactos',
  'dashboard.kpiOperationalNodes': 'Nodos Operativos',
  'dashboard.kpiAuditStatus': 'Estado de Auditoría',
  'dashboard.panelPreflight': 'Preflight',
  'dashboard.panelGovernance': 'Gobernanza',
  'dashboard.panelFederation': 'Topología de la Federación',
  'dashboard.liveStream': 'Flujo de Eventos Operativos Recientes',
  'dashboard.systemStatus': 'Sistema:',
  'setup.cta.configureCompany': 'Configurar perfil de empresa',
  'setup.cta.addSite': 'Añadir planta de producción',
  'setup.cta.configureMachines': 'Configurar parque de maquinaria',
  'setup.cta.configureCapabilities': 'Definir capacidades de máquina',
  'setup.cta.configureMaterials': 'Añadir materiales al catálogo',
  'setup.cta.configureCapacity': 'Configurar capacidad de producción',
  'setup.cta.configureLeadTimes': 'Establecer plazos y ANS',
  'setup.cta.configurePricing': 'Configurar tarifas industriales',
  'setup.cta.reviewMarketplace': 'Revisar preparación de mercado',
  'setup.module.resolveDependency': 'Resolver prerrequisito',
  'setup.nextStep.capacity': 'Turnos operativos, calendario de trabajo y límites de rendimiento requeridos',
  'setup.nextStep.leadTimes': 'Horas límite de recepción y acuerdos de nivel de servicio requeridos para planificación',
  'setup.card.recommendedBadge': 'Siguiente acción recomendada',
  'setup.card.blockedBadge': 'Prerrequisito obligatorio',
  'setup.summary.dimensionAccount': 'Cuenta e Identidad',
  'setup.summary.dimensionOps': 'Capacidad Operativa',
  'setup.summary.dimensionPricing': 'Precios Industriales',
  'setup.summary.dimensionMarketplace': 'Estado del Marketplace',
  'setup.summary.requirementsCount': 'requisitos verificados',
  'setup.summary.ratesConfigured': 'Tarifas y Libros Listos',
  'setup.summary.ratesPending': 'Tarifas sin Configurar',
  'dashboard.metricDegradation': 'Degradación de Telemetría de Origen:',
  'dashboard.metricDegradationDesc': 'Ciertos registros de producción están operando en estado de aislamiento fail-loud. Los KPIs correspondientes muestran N/D.',
  'dashboard.rowTotalAnalyzed': 'Total Analizados (Hoy)',
  'dashboard.rowActiveConcurrent': 'Tareas Concurrentes Activas',
  'dashboard.rowCompletedAnalyses': 'Análisis Completados',
  'dashboard.rowFailedExecutions': 'Ejecuciones Fallidas',
  'dashboard.rowRealExtraction': 'Contrato de Extracción Real',
  'dashboard.rowRuntimeEnvFailures': 'Fallos de Entorno de Ejecución',
  'dashboard.rowPartialArtifacts': 'Bloques Parciales de Artefactos',
  'dashboard.rowMeanRiskScore': 'Puntuación Media de Riesgo',
  'dashboard.rowRegistryBuffer': 'Profundidad de Búfer de Registro',
  'dashboard.rowLatestExecution': 'Última Cola de Ejecución',
  'dashboard.rowActivePolicies': 'Políticas de Enjambre Activas',
  'dashboard.rowLatestRule': 'Última Regla Activada',
  'dashboard.rowPolicyInterceptions': 'Intercepciones de Ejecución de Políticas',
  'dashboard.rowCertBlocked': 'Elementos Bloqueados por Certificación',
  'dashboard.rowPassedCertifiable': 'Volúmenes Certificables Aprobados',
  'dashboard.rowDeploymentClass': 'Clase de Contrato de Despliegue',
  'dashboard.rowAuditRegistryState': 'Estado del Registro de Auditoría',
  'dashboard.rowEstimatedValue': 'Valor Estimado Generado',
  'dashboard.rowAvoidedWaste': 'ROI en Desperdicio de Reimpresión Evitado',
  'dashboard.rowHoursSaved': 'Horas de Preimpresión Ahorradas',
  'dashboard.rowAutoFixSuccess': 'Correcciones Automáticas Exitosas',
  'dashboard.rowAutoFixFailures': 'Fallos de Intercepción AutoFix',
  'dashboard.rowQualityBenchmark': 'Índice de Calidad Derivado',
  'dashboard.rowVerifiedNodes': 'Nodos de Enjambre Verificados',
  'dashboard.rowActiveRoutes': 'Asignaciones de Ruta Activas',
  'dashboard.rowMissingGis': 'Coordenadas GIS Faltantes',
  'dashboard.rowDegradedInfra': 'Estado de Infraestructura Degradado',
  'dashboard.rowMeanUtilization': 'Utilización Media de Nodos',
  'dashboard.consensusSecure': 'CONSENSO DE ENJAMBRE: SEGURO',
  'dashboard.consensusDesc': 'Clústeres de despacho operando nativamente mediante mapas descentralizados de herencia de coordenadas de máquinas.',
  'dashboard.viewGeoMap': 'Ver Mapa Geográfico ↓',
  'dashboard.noOperationalLogs': 'No se recuperaron registros operativos en la captura activa. Sistema en espera.',
  'preflight.thJobPayload': 'Carga del Trabajo',
  'preflight.thTenantIdentity': 'Identidad del Tenant',
  'preflight.thTypePolicy': 'Tipo / Política de Ámbito',
  'preflight.thPayloadSize': 'Tamaño de Carga',
  'preflight.thStatusFidelity': 'Estado y Fidelidad',
  'preflight.thDiagnostics': 'Diagnóstico / Resultado',
  'preflight.thTimeline': 'Cronología',
  'preflight.filterPrinthouse': 'Filtrar ámbito de imprenta...',
  'preflight.resetFilters': 'Restablecer Filtros',
  'preflight.statusAll': 'Estado: Todos',
  'preflight.typeAll': 'Tipo: Todos',
  'preflight.policyAll': 'Política: Todas',
  'marketplace.drawerTitle': 'Identidad del Pedido:',
  'marketplace.prodBlockers': 'Bloqueos de Producción Detectados',
  'marketplace.btnAcknowledge': 'Aceptar Pedido para Producción',
  'marketplace.preflightGates': '1. Puertas de Preflight',
  'marketplace.runPreflight': 'Ejecutar Preflight',
  'marketplace.requirePreflight': 'Requerir Preflight',
  'marketplace.forcePass': 'Aprobación Forzada',
  'marketplace.forceFail': 'Rechazo Forzado',
  'marketplace.paymentGates': '2. Puertas de Pago',
  'marketplace.verifyApprove': 'Verificar y Aprobar',
  'marketplace.blockPayment': 'Bloquear Pago',
  'marketplace.printhouseHandoff': '3. Entrega a Imprenta',
  'marketplace.assignPh': 'Asignar Imprenta',
  'marketplace.preparePackage': 'Preparar Paquete',
  'marketplace.markReady': 'Marcar como Listo',
  'marketplace.requestAction': 'Solicitar Acción al Cliente',
  'marketplace.internalNotes': 'Notas Internas del Libro',
  'marketplace.addNote': 'Añadir Nota Interna',
  'marketplace.auditTimeline': 'Cronología Inmutable de Auditoría',
  'marketplace.selectedOffer': 'Oferta de Mercado Seleccionada',
  'marketplace.prodFiles': 'Archivos de Producción',
  'marketplace.noProdFiles': 'No se encontraron archivos de producción',
  'topbar.devPreview': 'Vista Previa de Desarrollo',
  'topbar.prodEnv': 'Entorno de Producción',
  'topbar.certified': 'Certificado v2.0.0',
  'topbar.region': 'EU-WEST-1 (Primario)',
  'topbar.settings': 'Configuración',
  'topbar.logout': 'Cerrar Sesión',
  'topbar.closeSession': '¿Cerrar Sesión?',
  'topbar.logoutConfirm': '¿Está seguro de que desea cerrar la sesión en el Plano de Control?',
  'topbar.cancel': 'Cancelar',
  'jobs.syncing': 'Sincronizando flujo de fabricación...',
  'jobs.validationSeed': 'Semilla de validación — sin paquete de producción',
  'jobs.syncingPackage': 'Sincronizando datos del paquete...',
  'dashboard.osControlCenter': 'Centro de Control del SO',
  'dashboard.printhouseHub': 'Centro de Imprenta',
  'dashboard.printhouseDesc': 'Signos vitales de producción en tiempo real, estado de trabajos y métricas operativas.',
  'dashboard.osControlDesc': 'Gobernanza global, signos vitales en tiempo real y coordinación de infraestructura.',
  'dashboard.last24Hours': 'Últimas 24 Horas',
  'dashboard.assignedJobs': 'Trabajos Asignados',
  'dashboard.globalJobs': 'Trabajos Globales',
  'dashboard.slaSuccess': 'Éxito de SLA',
  'dashboard.avgTurnaround': 'Tiempo Promedio de Entrega',
  'dashboard.meanLatency': 'Latencia Media',
  'dashboard.pendingAction': 'Acción Pendiente',
  'dashboard.queueDepth': 'Profundidad de Cola',
  'dashboard.activeGovBlocks': 'Bloques de Gobernanza Activos',
  'dashboard.exploreAll': 'Explorar Todo',
  'dashboard.noActiveGovBlocks': 'Sin bloques de gobernanza activos',
  'dashboard.workerCluster': 'Clúster de Trabajadores',
  'dashboard.efficiency': 'Eficiencia',
  'dashboard.workersActive': 'Trabajadores Activos',
  'dashboard.regionalCluster': 'Clúster Regional eu-west-1',
  'dashboard.queueStream': 'Flujo de Cola',
  'dashboard.liveBufferTrace': 'Rastreo de Búfer en Vivo',
  'dashboard.attachingStream': 'Conectando al flujo...',
  'dashboard.errorLoadingStream': 'Error al cargar el flujo',
  'dashboard.queueStatus': 'Estado de Cola',
  'dashboard.jobCount': 'Cantidad de Trabajos',
  'dashboard.description': 'Descripción',
  'dashboard.statusActiveDesc': 'Trabajos siendo procesados por trabajadores',
  'dashboard.statusWaitingDesc': 'Trabajos en cola esperando un trabajador disponible',
  'dashboard.statusDelayedDesc': 'Trabajos programados o retrasados',
  'dashboard.statusFailedDesc': 'Trabajos que encontraron errores durante la ejecución',
  'dashboard.statusCompletedDesc': 'Trabajos completados exitosamente',
  'dashboard.sourceUnavailable': 'N/D — origen no disponible',
  'dashboard.sourceUnavailableShort': 'N/D — no disponible',
  'dashboard.missionControlError': 'Error de Telemetría de Centro de Mando',
  'dashboard.liveAuditPipeline': 'Tubería de Auditoría en Vivo',
  'preflight.policiesUnavailable': 'Las políticas de preflight no están disponibles. La transformación está deshabilitada hasta que se restaure el catálogo de políticas.',
  'preflight.policiesDegraded': 'El catálogo de políticas upstream no responde. Usando contratos locales versionados de respaldo para la transformación.',
  'preflight.fixResult': 'Resultado de Corrección',
  'preflight.issues': 'Incidencias',
  'preflight.fixes': 'Correcciones',
  'preflight.batch': 'Lote',
  'preflight.untitled': 'Sin_titulo.pdf',
  'preflight.registered': 'Registrados',
  'preflight.batchId': 'ID de Lote',
  'preflight.tenantArray': 'Matriz de Inquilinos',
  'preflight.stagedJobsCount': 'Cantidad de Trabajos Preparados',
  'preflight.executionStatus': 'Estado de Ejecución',
  'preflight.timestamp': 'Marca de Tiempo',
  'preflight.auditIdTrace': 'ID de Auditoría / Traza',
  'preflight.operationAction': 'Acción Operativa',
  'preflight.resolutionStatus': 'Estado de Resolución',
  'preflight.messageTrail': 'Rastro de Mensajes',
  'preflight.loggedAt': 'Registrado En',
  'preflight.eventLedgerId': 'ID de Libro de Eventos',
  'preflight.tenantTarget': 'Inquilino Objetivo',
  'preflight.rulePolicySlug': 'Identificador de Regla/Política',
  'preflight.evaluationStatus': 'Estado de Evaluación',
  'preflight.enforcedAction': 'Acción Aplicada',
  'preflight.registeredTimestamp': 'Marca de Tiempo Registrada',
  'preflight.gatewayCriticalError': 'La integración de Gateway upstream encontró un error crítico:',
  'preflight.executeRetry': 'Ejecutar Reintento',
  'dashboard.panelFleet': 'Flota',
  'dashboard.panelStorage': 'Almacenamiento',
  'dashboard.panelIncidentBridge': 'Puente de Incidentes',
  'dashboard.panelIntelligenceLayer': 'Capa de Inteligencia',
  'dashboard.panelEconomy': 'Economía',
  'dashboard.panelHeartbeat': 'Matriz de Latidos',
  'dashboard.panelSystemRegistry': 'Registro del Sistema',
  'dashboard.panelHeatmap': 'Mapa Térmico de Fabricación',
  'dashboard.panelDispatchConsole': 'Consola de Despacho',
  'dashboard.panelRoutingSimulation': 'Simulación de Enrutamiento',
  'dashboard.panelConsole': 'Consola',
  'dashboard.panelOperationalSummary': 'Resumen Operativo',
  'dashboard.panelOperationalActivity': 'Flujo de Actividad Operativa',
  'dashboard.activeJobs': 'Trabajos Activos',
  'dashboard.failedToday': 'Fallidos (Hoy)',
  'dashboard.completedJobsToday': 'Trabajos Completados Hoy',
  'dashboard.throughput': 'Rendimiento',
  'dashboard.storageUtilized': 'Almacenamiento Utilizado',
  'dashboard.activeArtifacts': 'Artefactos Activos',
  'dashboard.artifacts': 'Artefactos',
  'dashboard.avgMargin': 'Margen Promedio',
  'dashboard.quality': 'Calidad',
  'dashboard.sectorClear': 'Sector Despejado',
  'dashboard.continuousSweep': 'Barrido Continuo',
  'dashboard.inferenceEngines': 'Motores de Inferencia',
  'dashboard.optimizationRate': 'Tasa de Optimización',
  'dashboard.telemetryInference': 'Inferencia Telemétrica',
  'dashboard.driftVariance': 'Varianza de Deriva',
  'dashboard.activeIncidents': 'Incidentes Activos',
  'dashboard.noMachinesConfigured': 'No hay máquinas configuradas',
  'dashboard.streamActive': 'Suscripción de Flujo Activa',
  'dashboard.listeningTraces': 'Esperando trazas de actividad operativa...',
  'dashboard.pauseQueue': 'Pausar Orquestación de Cola',
  'dashboard.pauseBadge': 'Parada Global de Emergencia',
  'dashboard.resumeQueue': 'Reanudar Orquestación de Cola',
  'dashboard.resumeBadge': 'Reactivar Nodos de Trabajadores',
  'preflight.industrialExecution': 'Ejecución de Preflight Industrial',
  'preflight.dropzoneTitle': 'Haga clic o arrastre el bloque PDF',
  'preflight.magicByteNotice': 'Aplica Verificación de Magic Bytes',
  'preflight.selectPdfBtn': 'Seleccionar Archivo PDF',
  'preflight.readyStatus': 'Listo',
  'preflight.tenantIsolation': 'Aislamiento de Tenant',
  'preflight.policyCatalog': 'Catálogo de Políticas',
  'preflight.policyUnavailable': 'No disponible',
  'preflight.executionMode': 'Modo de Ejecución',
  'preflight.modeAnalyze': 'Solo Analizar',
  'preflight.modeAnalyzeDesc': 'Comprueba el PDF y genera diagnósticos. No genera un PDF corregido.',
  'preflight.modeAutofix': 'Autocorrección',
  'preflight.modeAutofixDesc': 'Intenta reparar el PDF y genera un PDF corregido en caso de éxito.',
  'preflight.btnExecute': 'Ejecutar Trabajo de Preflight',
  'preflight.btnProcessing': 'Procesando',
  'preflight.btnDispatched': 'Enviado Correctamente',
  'preflight.execFailed': 'Falló la ejecución del Gateway de Preflight industrial upstream.',
  'dashboard.stateProcessing': 'Procesando',
  'dashboard.stateListening': 'Escuchando',
  'dashboard.stateStandby': 'En Espera',
  'dashboard.stateActive': 'Activo',
  'dashboard.stateOffline': 'Desconectado',
  'dashboard.stateDegraded': 'Degradado',
  'dashboard.stateSaturated': 'Saturado',
  'dashboard.stateSecure': 'Seguro',
  'dashboard.stateSynced': 'Sincronizado',
  'dashboard.stateHealthy': 'Saludable',
  'dashboard.metricLoad': 'Carga',
  'dashboard.metricRisks': 'Riesgos',
  'dashboard.metricSync': 'Sincronización',
  'dashboard.metricActive': 'Activo',
  'dashboard.queueStatusActive': 'Activo',
  'dashboard.queueStatusWaiting': 'En Espera',
  'dashboard.queueStatusDelayed': 'Demorado',
  'dashboard.queueStatusFailed': 'Fallido',
  'dashboard.queueStatusCompleted': 'Completado',
  // Tooltips & Accessibility Labels
  'topbar.toggleThemeLight': 'Cambiar a modo Claro',
  'topbar.toggleThemeDark': 'Cambiar a modo Oscuro',
  'topbar.toggleLanguage': 'Cambiar idioma (actual: {{lang}})',
  'topbar.notificationsBtn': 'Notificaciones ({{count}} no leídas)',
  'topbar.notificationsBtnZero': 'Notificaciones',
  'topbar.notificationsTitle': 'Notificaciones',
  'topbar.markAllRead': 'Marcar todo como leído',
  'topbar.newBadge': 'nueva',
  'sidebar.appSidebar': 'Barra lateral de la aplicación',
  'sidebar.closeMobile': 'Cerrar barra lateral móvil',
  'settings.appearance.themeDarkTooltip': 'Tema Oscuro Industrial para operaciones de alto contraste',
  'settings.appearance.themeLightTooltip': 'Tema Claro Corporativo para administración diurna',
  'settings.appearance.densityComfortableTooltip': 'Densidad Cómoda con espaciado y controles estándar',
  'settings.appearance.densityCompactTooltip': 'Densidad Compacta optimizada para pantallas industriales densas',
  'settings.appearance.animationsTooltip': 'Alternar microanimaciones y transiciones de la interfaz',
  'pricing.workflow.group': 'Selector de modo de tarificación',
  'pricing.workflow.assistantBtn': 'Asistente de calibración por IA',
  'pricing.workflow.manualBtn': 'Configuración manual de tarifas',
  'pricing.workflow.priceBooksBtn': 'Escalas comerciales y listas de precios para clientes',
  'pricing.hawkeye.tooltip': 'Estado canónico de tarificación de solo lectura, anclajes calibrados y cobertura de dominios.',
  'pricing.hawkeye.anchorsTooltip': 'Tarifas de anclaje representativas calibradas de la matriz canónica.',
  'pricing.hawkeye.modulesTooltip': 'Salud y completitud estructural por dominio de tarificación.',
  'pricing.hawkeye.revisionTooltip': 'Última revisión creada (no verificada por checksum en vivo)',
  'pricing.action.editMetadata': 'Editar metadatos',
  'pricing.action.cloneVersion': 'Clonar versión',
  'pricing.action.deleteDraft': 'Eliminar borrador',
  'pricing.action.calibrateQuote': 'Calibrar a partir de este presupuesto',
  'pricing.action.previousSessions': 'Sesiones calibradas anteriores',
  'pricing.action.removeEntry': 'Eliminar {{name}}',
  'pricing.action.dismissError': 'Descartar error',
  'setup.help.searchLabel': 'Buscar ajustes y documentación de ayuda',
  'setup.help.closeBtn': 'Cerrar ventana de ayuda',
  'setup.tutorial.exitBtn': 'Salir del tutorial',
  'setup.status.completed': 'Completado',
  'setup.status.inProgress': 'En progreso',
  'setup.status.needsAttention': 'Requiere atención',
  'setup.status.prerequisitesRequired': 'Prerrequisitos requeridos',
  'setup.summary.regionLabel': 'Resumen de dimensiones de preparación',
  'dashboard.orders.expectedRevenue': 'Ingresos estimados de imprenta',
  'dashboard.orders.filterAll': 'Todos los pedidos',
  'dashboard.orders.filterHighProfit': 'Alto margen',
  'dashboard.orders.filterUrgent': 'Urgente',
  'dashboard.orders.noOrders': 'No hay pedidos que coincidan con el filtro actual.',
  'pricing.calibration.currentSpec': 'Especificación actual',
  'pricing.calibration.editFullSpec': 'Editar especificación completa',
  'pricing.calibration.drawerTitle': 'Especificación actual y detalles extraídos',
  'pricing.calibration.drawerSubtitle': 'Revise los parámetros extraídos por el asistente o el PDF adjunto.',
  'pricing.calibration.noSpecsYet': 'Aún no se han introducido especificaciones.',
  'pricing.calibration.noSpecsHint': 'Suba un PDF de presupuesto o describa un trabajo para comenzar.',
  'pricing.action.calibrateQuoteBtn': 'Calibrar presupuesto',
  'pricing.action.calibratedBooks': 'Libros calibrados',
  'pricing.action.revisions': 'Revisiones',
  'pricing.action.hideAdvanced': 'Ocultar avanzados',
  'pricing.action.advancedDetails': 'Detalles avanzados',
  'pricing.dropzone.title': 'Arrastre su presupuesto PDF aquí',
  'pricing.dropzone.subtitle': 'o examine sus archivos (PDF · máx. ~10 MB)',
  'pricing.dropzone.dragOver': 'Suelte para analizar el presupuesto PDF',
  'pricing.dropzone.browse': 'Examinar archivos',
  'pricing.dropzone.compactTitle': 'Adjuntar otro presupuesto PDF',
  'pricing.dropzone.compactAction': 'Subir nuevo PDF',
  'pricing.example.prompt1': '1.000 ejemplares, 170x240 mm, 128 págs 4/4 en offset 80 g, cubierta 300 g, rústica fresada por 2.450 €',
  'pricing.example.prompt2': '500 ejemplares A4 210x297 mm, 64 págs 4/4 estucado 130 g, grapado por 1.200 €',
  'pricing.example.prompt3': 'Libro fotográfico tapa dura, 250 ejemplares, 200 págs 4/4 estucado 150 g, cosido por 4.800 €',
  'pricing.review.extractedData': 'Datos extraídos del presupuesto',
  'pricing.review.pendingConfirmation': 'Pendiente de confirmación',
  'pricing.review.selectedVariant': 'Oferta y variante seleccionada',
  'pricing.review.noVariantSelected': 'Ninguna variante seleccionada aún',
  'pricing.review.calibrationProposal': 'Propuesta de calibración',
  'pricing.review.noProposalYet': 'Aún no se ha generado una propuesta del solver',
  'pricing.variant.selectedBadge': 'Seleccionada',
  'pricing.spec.quantity': 'Cantidad:',
  'pricing.spec.copies': 'ejemplares',
  'pricing.spec.trimSize': 'Formato:',
  'pricing.spec.interiorPages': 'Páginas interiores:',
  'pricing.spec.paper': 'Papel:',
  'pricing.spec.binding': 'Encuadernación:',
  'pricing.review.manufacturingTarget': 'Objetivo de fabricación:',
  'pricing.review.transportPerKg': 'Transporte (€/kg):',
  'pricing.solver.awaitingSolver': 'Esperando solver',
  'pricing.solver.predictedPrice': 'Precio predicho:',
  'pricing.solver.residual': 'Residuo:',
  'pricing.solver.accepted': 'Aceptado',
  'pricing.wizard.step1': 'Describir trabajo',
  'pricing.wizard.step2': 'Revisar',
  'pricing.wizard.step3': 'Coste fabricación',
  'pricing.wizard.step4': 'Calibrar',
  'pricing.wizard.step5': 'Probar precios',
  'pricing.acceptance.modalTitle': 'Confirmar aceptación gobernada',
  'pricing.acceptance.modalSubtitle': 'Aplicar matriz calibrada al nodo de producción',
  'pricing.acceptance.targetNode': 'Nodo de producción objetivo:',
  'pricing.acceptance.referenceBook': 'Libro de referencia:',
  'pricing.acceptance.declaredTarget': 'Objetivo de fabricación declarado:',
  'pricing.acceptance.calibratedPrice': 'Precio predicho calibrado:',
  'pricing.acceptance.solverResidual': 'Residuo del solver:',
  'pricing.acceptance.immutableTitle': 'Creación de revisión de precios inmutable',
  'pricing.acceptance.immutableDesc': 'Al aceptar se verificará atómicamente la integridad de la base, se actualizará la tarifa de producción activa de este nodo y se registrará una revisión inmutable en el registro de auditoría.',
  'pricing.acceptance.applying': 'Aplicando revisión...',
  'pricing.acceptance.acceptBtn': 'Aceptar revisión de precios',
  'pricing.acceptance.closeModal': 'Cerrar ventana modal',
  'fileTooLargeError': 'El archivo supera el límite del servidor (10 MB). Seleccione un PDF más pequeño.',

  // Topbar and Governance Posture
  'topbar.governedPosture': 'Gobernanza Activa',
  'topbar.governedVerifying': 'Verificando...',
  'topbar.governedDegraded': 'Gobernanza Parcial',
  'topbar.governedOffline': 'Sin Telemetría',
  'topbar.governedActiveTooltip': 'Telemetría de servidor y control RBAC verificados en tiempo real.',
  'topbar.governedDegradedTooltip': 'Conectividad establecida con dependencias de servidor degradadas.',
  'topbar.governedOfflineTooltip': 'No se pudo verificar la telemetría del servidor en vivo; no se afirman garantías operativas.',
  'topbar.governedVerifyingTooltip': 'Comprobando telemetría de dependencias de servidor y control RBAC.',

  // Industrial Operations Page
  'industrial.title': 'Operaciones Industriales',
  'industrial.subtitle': 'Orquestación de alta fidelidad y gobernanza de infraestructura distribuida.',
  'industrial.operational': 'Operativo',
  'industrial.intelligence': 'Inteligencia',
  'industrial.governance': 'Gobernanza',
  'industrial.systemOperational': 'Sistema Operativo',
  'industrial.telemetryDegraded': 'Telemetría Parcial',
  'industrial.telemetryUnconfigured': 'Sin Configuración',
  'industrial.verifyingStatus': 'Verificando Estado...',
  'industrial.liveMap': 'Mapa en Vivo',
  'industrial.nodesConnected': 'Nodos Conectados',

  // Geospatial Map & Nodes
  'map.unconfiguredProvider': 'Proveedor geoespacial Carto sin clave de API configurada',
  'map.unconfiguredProviderHint': 'Para evitar la carga de teselas con errores o marcas de agua ("API KEY REQUIRED"), la infraestructura se visualiza en modo táctico estructurado con inspección directa de nodos.',
  'map.tacticalSurface': 'Superficie Táctica Geoespacial',
  'map.nodeRegistry': 'Registro Táctico de Nodos',
  'map.inspectMachine': 'Inspeccionar Máquina',
  'map.coordinatesMissing': 'Sin coordenadas asignadas',
  'map.coordinatesAssigned': 'Coordenadas asignadas',
  'map.routingDecalog': 'Decálogo de Enrutamiento',
  'map.routingExplanation': 'Historial de decisiones operativas de enrutamiento y asignación.',
  'map.collapseTelemetry': 'Colapsar Telemetría',
  'map.inspectExclusions': 'Inspeccionar Exclusiones',
  'map.nodesExcluded': 'nodos excluidos del mapa geoespacial',
  'map.nodeExcluded': 'nodo excluido del mapa geoespacial',

  // Common & Maps
  'common.cancel': 'Cancelar',
  'common.confirm': 'Confirmar',
  'common.done': 'Operación completada correctamente.',
  'setup.region': 'Región',

  // Beta Workspace & Runtime
  'beta.runtime.title': 'Consola de Entorno Beta y Pruebas de Recuperación',
  'beta.runtime.subtitle': 'Monitoreo de sesiones activas, auditoría de eventos y simulacros de recuperación ante reinicio.',
  'beta.runtime.safetyWarning': 'Entorno Beta Restringido por Invitación. Este entorno no habilita acceso público, marketplace abierto, ejecución de pagos, liquidaciones ni mutaciones de código no autorizadas.',
  'beta.runtime.drillWarning': 'Simulacro de Recuperación ante Reinicio. Verificación estricta de invariantes de persistencia y límites de acceso.',
  'beta.runtime.hardenedStatus': 'Registro de Integridad y Recuperación ante Reinicio',
  'beta.runtime.restartDrillPanel': 'Panel de Simulacros de Recuperación ante Reinicio',
  'beta.runtime.noDrillRun': 'Sin simulacro ejecutado — Inicie un simulacro para capturar hashes y verificar integridad',
  'beta.runtime.pendingSnapshot': 'Pendiente de instantánea',
  'beta.runtime.notEvaluated': 'No evaluado (ejecute comprobación)',
  'beta.runtime.createDrill': 'Crear Simulacro',
  'beta.runtime.snapshotBefore': 'Instantánea Previa',
  'beta.runtime.verifyAfter': 'Verificar Posterior',
  'beta.runtime.compareSnapshots': 'Comparar Instantáneas',
  'beta.runtime.verifyKillSwitch': 'Verificar Kill Switch',
  'beta.runtime.verifyAccess': 'Verificar Acceso',
  'beta.runtime.gateContext': 'Contexto de Compuerta Beta',
  'beta.runtime.enableGate': 'Habilitar Compuerta',
  'beta.runtime.disableGate': 'Deshabilitar Compuerta',
  'beta.runtime.checkReadiness': 'Comprobar Estado',
  'beta.runtime.killSwitchConfirmTitle': 'Confirmar Interruptor de Emergencia (Kill Switch)',
  'beta.runtime.killSwitchConfirmMsg': '¿Desea activar el interruptor de emergencia? Esta acción suspenderá de inmediato el acceso al entorno beta para la compuerta seleccionada.',
  'beta.runtime.disableGateConfirmTitle': 'Confirmar Deshabilitación de Compuerta',
  'beta.runtime.disableGateConfirmMsg': '¿Desea deshabilitar esta compuerta de acceso? Los participantes perderán el acceso a las funciones asignadas.',
  'beta.runtime.advancedJson': 'Opciones Avanzadas y Diagnóstico JSON',
  'beta.runtime.limitedBeta': 'Entorno Beta',
  'beta.runtime.recoveryRegistry': 'Registro de Integridad y Recuperación ante Reinicio',
  'beta.runtime.triggerKillSwitch': 'Activar Interruptor',
  'beta.runtime.clearKillSwitch': 'Desactivar',
  'beta.runtime.evidenceOutputs': 'Generación de Evidencias y Auditoría',
  'beta.runtime.getAuditTimeline': 'Cronología de Auditoría',
  'beta.runtime.buildEvidencePack': 'Paquete de Evidencias',
  'beta.runtime.advancedDiagnostics': 'Diagnóstico Técnico y Respuestas JSON',
  'beta.runtime.activityReview': 'Observación de Actividad del Entorno Beta',
  'beta.runtime.warningTitle': 'Aviso de Seguridad de Entorno Beta',
  'beta.runtime.safetyInvariants': 'Invariantes de Seguridad Garantizadas',

  // Beta Sessions
  'beta.sessions.title': 'Sesiones de Entorno Beta Controlado',
  'beta.sessions.subtitle': 'Gestión de límites de concurrencia, TTL y revocación de sesiones operativas.',
  'beta.sessions.warning': 'Sesiones de entorno beta estrictamente acotadas. No otorga acceso general ni permisos comerciales.',

  // Beta Health & Reviews
  'beta.health.title': 'Revisión de Actividad y Salud de Cohorte',
  'beta.health.subtitle': 'Evaluación de señales de uso, detección de anomalías y generación de recomendaciones antes de intervenir.',
  'beta.health.warning': 'Compuerta de revisión de cohorte. No altera automáticamente el acceso, alcance del marketplace ni reglas de facturación.',
  'beta.health.noReviews': 'No se han generado revisiones de actividad todavía.',
  'beta.health.actionableHint': 'Para evaluar la salud del cohorte se requiere un registro previo de observación de actividad con invariantes de seguridad preservadas.',
  'beta.health.goToActivity': 'Ir a Observación de Actividad',
  'beta.health.goToObservation': 'Ir a Observación de Actividad',
  'beta.health.noFinalizedReviews': 'No se encontraron revisiones de salud finalizadas.',
  'beta.health.createOrFinalizeHint': 'Finalice una revisión de salud en esta pestaña para poder preparar un paquete de intervención.',

  // Beta Governance & Interventions
  'beta.governance.title': 'Preparación de Intervenciones Gobernadas de Cohorte',
  'beta.governance.subtitle': 'Preparación y formalización de paquetes de intervención con trazabilidad estricta.',
  'beta.governance.warning': 'Paquete de acción propuesto solo para revisión. Esta interfaz es estrictamente para preparar paquetes de intervención gobernados. No se ejecutan mutaciones operativas ni cambios comerciales.',
  'beta.governance.noReviewsWarning': 'No se encontraron revisiones de salud previas finalizadas.',
  'beta.governance.noFinalizedReviews': 'No se encontraron revisiones de salud finalizadas.',
  'beta.governance.preparationHint': 'Para preparar una propuesta de intervención gobernada se requiere una revisión de actividad finalizada.',
  'beta.governance.goToHealthReviews': 'Ir a Revisiones de Salud de Cohorte',
  'beta.governance.approvalNotExecution': 'La aprobación no constituye ejecución inmediata',
  'beta.governance.approvalsTitle': 'Aprobaciones de Intervenciones Gobernadas',
  'beta.governance.executionsTitle': 'Ejecución Segura de Intervenciones Gobernadas',

  // Topbar Telemetry
  'topbar.telemetryHealthy': 'Telemetría Núcleo: OK',
  'topbar.telemetryDegraded': 'Telemetría Degradada',
  'topbar.telemetryOffline': 'Sin Telemetría',
  'topbar.telemetryVerifying': 'Comprobando Núcleo...',
  'topbar.telemetryVerifyingTooltip': 'Comprobando estado del proceso y dependencias en /api/system/health...',

  // Map Cartography Fallback
  'map.tileLoadFailed': 'Error al cargar teselas cartográficas (401/403/Red)',
  'map.tileLoadFailedHint': 'El proveedor cartográfico configurado no respondió satisfactoriamente. Se mantiene activo el registro táctico de nodos y la inspección de maquinaria.',
  'common.retry': 'Reintentar',

  // Workspace and Navigation Shells
  'beta.runtime.workspaceTitle': 'Entorno Beta Controlado',
  'beta.runtime.workspaceDesc': 'Supervisión de sesiones activas, registro de actividad y revisiones de salud de cohorte.',
  'beta.runtime.breadcrumb': 'Ejecución',
  'beta.runtime.tabOverview': 'Resumen',
  'beta.runtime.tabSessions': 'Sesiones',
  'beta.runtime.tabActivity': 'Actividad',
  'beta.runtime.tabHealth': 'Salud de Cohorte',

  'beta.governance.workspaceTitle': 'Gobernanza de Cohorte Beta',
  'beta.governance.workspaceDesc': 'Gobernanza de propuestas de intervención, aprobaciones, ejecuciones operativas y simulaciones.',
  'beta.governance.breadcrumb': 'Gobernanza',
  'beta.governance.tabInterventions': 'Intervenciones',
  'beta.governance.tabApprovals': 'Aprobaciones',
  'beta.governance.tabExecutions': 'Ejecuciones',
  'beta.governance.tabSimulations': 'Simulaciones',
  'beta.governance.tabSimulationReviews': 'Revisiones de Simulación',

  'beta.cohort.workspaceTitle': 'Gestión de Cohorte Beta',
  'beta.cohort.workspaceDesc': 'Gestión de activación de cohorte, emisión de invitaciones y auditoría de participantes activos.',
  'beta.cohort.breadcrumb': 'Cohortes',
  'beta.cohort.tabActivation': 'Activación',
  'beta.cohort.tabInvitations': 'Invitaciones',
  'beta.cohort.tabParticipants': 'Participantes',

  // Industrial Operations Navigation Tabs
  'industrial.tabLive': 'Bucle en Vivo',
  'industrial.tabWorkers': 'Flota',
  'industrial.tabNodes': 'Nodos',
  'industrial.tabDispatch': 'Despacho',
  'industrial.tabMetrics': 'Métricas',
  'industrial.tabEconomics': 'Economía',
  'industrial.tabTemporal': 'Temporal',
  'industrial.tabSim': 'Simulación',
  'industrial.tabPolicies': 'Políticas',
  'industrial.tabIncidents': 'Incidencias',
  'industrial.tabLifecycle': 'Ciclo de Vida',
  'industrial.tabStorage': 'Almacenamiento',
} as const;

export type TranslationKeys = keyof typeof es;
