-- migrations/015_phase76_printhouse_capabilities.sql
-- Phase 76A — Control Plane Printhouse Capability Schema

CREATE TABLE IF NOT EXISTS printhouses (
    id VARCHAR(50) PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    legal_name VARCHAR(255),
    country VARCHAR(100),
    region VARCHAR(100),
    city VARCHAR(100),
    contact_email VARCHAR(255),
    contact_phone VARCHAR(50),
    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    onboarding_status VARCHAR(50) NOT NULL DEFAULT 'NOT_STARTED',
    default_currency VARCHAR(10) DEFAULT 'EUR',
    timezone VARCHAR(50) DEFAULT 'Europe/Madrid',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS printhouse_machines (
    id VARCHAR(50) PRIMARY KEY,
    printhouse_id VARCHAR(50) NOT NULL,
    tenant_id VARCHAR(50) NOT NULL,
    machine_name VARCHAR(255) NOT NULL,
    machine_type VARCHAR(50) NOT NULL,
    manufacturer VARCHAR(255),
    model VARCHAR(255),
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    max_sheet_width_mm INT,
    max_sheet_height_mm INT,
    min_sheet_width_mm INT,
    min_sheet_height_mm INT,
    max_print_width_mm INT,
    max_print_height_mm INT,
    supported_color_modes_json TEXT,
    supported_print_methods_json TEXT,
    supported_sides_json TEXT,
    max_pages_per_job INT,
    max_file_size_mb INT,
    max_tac_percent INT,
    supports_pdfx BOOLEAN DEFAULT FALSE,
    supports_pdfa BOOLEAN DEFAULT FALSE,
    supports_variable_data BOOLEAN DEFAULT FALSE,
    supports_white_ink BOOLEAN DEFAULT FALSE,
    supports_spot_uv BOOLEAN DEFAULT FALSE,
    supports_lamination BOOLEAN DEFAULT FALSE,
    supports_hardcover BOOLEAN DEFAULT FALSE,
    supports_softcover BOOLEAN DEFAULT FALSE,
    supports_saddle_stitch BOOLEAN DEFAULT FALSE,
    supports_perfect_binding BOOLEAN DEFAULT FALSE,
    supports_case_binding BOOLEAN DEFAULT FALSE,
    metadata_json TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (printhouse_id) REFERENCES printhouses(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS printhouse_media (
    id VARCHAR(50) PRIMARY KEY,
    printhouse_id VARCHAR(50) NOT NULL,
    tenant_id VARCHAR(50) NOT NULL,
    media_name VARCHAR(255) NOT NULL,
    media_type VARCHAR(50) NOT NULL,
    gsm INT,
    thickness_microns INT,
    finish VARCHAR(50),
    color VARCHAR(50),
    sheet_width_mm INT,
    sheet_height_mm INT,
    roll_width_mm INT,
    grain_direction VARCHAR(50),
    fsc_available BOOLEAN DEFAULT FALSE,
    pefc_available BOOLEAN DEFAULT FALSE,
    recycled_content_percent INT,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    compatible_machine_ids_json TEXT,
    metadata_json TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (printhouse_id) REFERENCES printhouses(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS printhouse_policy_profiles (
    id VARCHAR(50) PRIMARY KEY,
    printhouse_id VARCHAR(50) NOT NULL,
    tenant_id VARCHAR(50) NOT NULL,
    profile_name VARCHAR(255) NOT NULL,
    profile_type VARCHAR(50) NOT NULL,
    required_pdf_standard VARCHAR(50) DEFAULT 'NONE',
    allow_degraded_analysis BOOLEAN DEFAULT TRUE,
    require_artifact_trust_production_certified BOOLEAN DEFAULT TRUE,
    require_visual_proof_approval BOOLEAN DEFAULT TRUE,
    require_human_review_for_page_marks BOOLEAN DEFAULT TRUE,
    require_human_review_for_ink_changes BOOLEAN DEFAULT TRUE,
    require_human_review_for_font_changes BOOLEAN DEFAULT TRUE,
    require_human_review_for_transparency BOOLEAN DEFAULT TRUE,
    max_tac_percent INT,
    min_bleed_mm INT,
    allow_rgb BOOLEAN DEFAULT FALSE,
    allow_spot_colors BOOLEAN DEFAULT TRUE,
    allow_transparency BOOLEAN DEFAULT TRUE,
    allow_overprint BOOLEAN DEFAULT TRUE,
    allow_annotations BOOLEAN DEFAULT TRUE,
    allow_forms BOOLEAN DEFAULT TRUE,
    allow_javascript BOOLEAN DEFAULT FALSE,
    allow_embedded_files BOOLEAN DEFAULT FALSE,
    required_output_intent VARCHAR(255),
    accepted_trim_box_policy VARCHAR(100),
    metadata_json TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (printhouse_id) REFERENCES printhouses(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS printhouse_sla_profiles (
    id VARCHAR(50) PRIMARY KEY,
    printhouse_id VARCHAR(50) NOT NULL,
    tenant_id VARCHAR(50) NOT NULL,
    profile_name VARCHAR(255) NOT NULL,
    production_days_min INT,
    production_days_max INT,
    cutoff_time_local VARCHAR(10),
    weekend_production BOOLEAN DEFAULT FALSE,
    holiday_calendar_region VARCHAR(100),
    rush_available BOOLEAN DEFAULT FALSE,
    rush_surcharge_percent INT,
    max_daily_jobs INT,
    max_daily_pages INT,
    metadata_json TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (printhouse_id) REFERENCES printhouses(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS printhouse_capability_audit (
    id INT AUTO_INCREMENT PRIMARY KEY,
    printhouse_id VARCHAR(50) NOT NULL,
    tenant_id VARCHAR(50) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    actor_user_id VARCHAR(100) NOT NULL,
    actor_role VARCHAR(100) NOT NULL,
    before_json TEXT,
    after_json TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
