-- Migration 025: Phase 85 Public Marketplace Readiness & Launch Control

CREATE TABLE IF NOT EXISTS marketplace_launch_controls (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    launch_status VARCHAR(50) NOT NULL DEFAULT 'NOT_STARTED',
    public_marketplace_launch_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    public_intake_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    public_offer_generation_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    public_customer_registration_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    public_payment_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    public_file_upload_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    public_partner_fulfillment_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    launch_scope VARCHAR(50) NOT NULL DEFAULT 'INTERNAL_ONLY',
    active_cohort_id UUID,
    readiness_snapshot_json JSONB,
    approval_snapshot_json JSONB,
    emergency_stop_snapshot_json JSONB,
    rollback_snapshot_json JSONB,
    blocking_reasons_json JSONB,
    warning_reasons_json JSONB,
    requested_by UUID,
    requested_by_role VARCHAR(50),
    requested_at TIMESTAMPTZ,
    approved_by UUID,
    approved_by_role VARCHAR(50),
    approved_at TIMESTAMPTZ,
    activated_by UUID,
    activated_by_role VARCHAR(50),
    activated_at TIMESTAMPTZ,
    paused_by UUID,
    paused_by_role VARCHAR(50),
    paused_at TIMESTAMPTZ,
    emergency_stopped_by UUID,
    emergency_stopped_by_role VARCHAR(50),
    emergency_stopped_at TIMESTAMPTZ,
    emergency_stop_reason TEXT,
    rolled_back_by UUID,
    rolled_back_by_role VARCHAR(50),
    rolled_back_at TIMESTAMPTZ,
    rollback_reason TEXT,
    metadata_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS marketplace_launch_cohorts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cohort_name VARCHAR(255) NOT NULL,
    cohort_status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    cohort_type VARCHAR(50) NOT NULL,
    allowed_tenant_ids_json JSONB,
    allowed_printhouse_ids_json JSONB,
    allowed_customer_segments_json JSONB,
    allowed_countries_json JSONB,
    allowed_order_types_json JSONB,
    max_orders_per_day INT,
    max_customers_per_day INT,
    max_file_size_mb INT,
    max_live_jobs_per_day INT,
    requires_manual_review BOOLEAN NOT NULL DEFAULT TRUE,
    requires_invite_code BOOLEAN NOT NULL DEFAULT FALSE,
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    created_by UUID,
    created_by_role VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS marketplace_launch_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    launch_control_id UUID,
    cohort_id UUID,
    event_type VARCHAR(100) NOT NULL,
    actor_user_id UUID,
    actor_role VARCHAR(50),
    message TEXT,
    before_json JSONB,
    after_json JSONB,
    metadata_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS marketplace_public_guard_decisions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    launch_control_id UUID,
    cohort_id UUID,
    tenant_id UUID,
    printhouse_id UUID,
    customer_id UUID,
    source_order_id UUID,
    action VARCHAR(100) NOT NULL,
    decision VARCHAR(50) NOT NULL,
    blocking_reasons_json JSONB,
    warning_reasons_json JSONB,
    actor_user_id UUID,
    actor_role VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
