-- Migration 025: Phase 85 Public Marketplace Readiness & Launch Control

CREATE TABLE IF NOT EXISTS marketplace_launch_controls (
    id VARCHAR(255) PRIMARY KEY,
    launch_status VARCHAR(50) NOT NULL DEFAULT 'NOT_STARTED',
    public_marketplace_launch_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    public_intake_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    public_offer_generation_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    public_customer_registration_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    public_payment_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    public_file_upload_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    public_partner_fulfillment_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    launch_scope VARCHAR(50) NOT NULL DEFAULT 'INTERNAL_ONLY',
    active_cohort_id VARCHAR(255),
    readiness_snapshot_json JSON,
    approval_snapshot_json JSON,
    emergency_stop_snapshot_json JSON,
    rollback_snapshot_json JSON,
    blocking_reasons_json JSON,
    warning_reasons_json JSON,
    requested_by VARCHAR(255),
    requested_by_role VARCHAR(50),
    requested_at TIMESTAMPTZ,
    approved_by VARCHAR(255),
    approved_by_role VARCHAR(50),
    approved_at TIMESTAMPTZ,
    activated_by VARCHAR(255),
    activated_by_role VARCHAR(50),
    activated_at TIMESTAMPTZ,
    paused_by VARCHAR(255),
    paused_by_role VARCHAR(50),
    paused_at TIMESTAMPTZ,
    emergency_stopped_by VARCHAR(255),
    emergency_stopped_by_role VARCHAR(50),
    emergency_stopped_at TIMESTAMPTZ,
    emergency_stop_reason TEXT,
    rolled_back_by VARCHAR(255),
    rolled_back_by_role VARCHAR(50),
    rolled_back_at TIMESTAMPTZ,
    rollback_reason TEXT,
    metadata_json JSON,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS marketplace_launch_cohorts (
    id VARCHAR(255) PRIMARY KEY,
    cohort_name VARCHAR(255) NOT NULL,
    cohort_status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    cohort_type VARCHAR(50) NOT NULL,
    allowed_tenant_ids_json JSON,
    allowed_printhouse_ids_json JSON,
    allowed_customer_segments_json JSON,
    allowed_countries_json JSON,
    allowed_order_types_json JSON,
    max_orders_per_day INT,
    max_customers_per_day INT,
    max_file_size_mb INT,
    max_live_jobs_per_day INT,
    requires_manual_review BOOLEAN NOT NULL DEFAULT TRUE,
    requires_invite_code BOOLEAN NOT NULL DEFAULT FALSE,
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    created_by VARCHAR(255),
    created_by_role VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS marketplace_launch_events (
    id VARCHAR(255) PRIMARY KEY,
    launch_control_id VARCHAR(255),
    cohort_id VARCHAR(255),
    event_type VARCHAR(100) NOT NULL,
    actor_user_id VARCHAR(255),
    actor_role VARCHAR(50),
    message TEXT,
    before_json JSON,
    after_json JSON,
    metadata_json JSON,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS marketplace_public_guard_decisions (
    id VARCHAR(255) PRIMARY KEY,
    launch_control_id VARCHAR(255),
    cohort_id VARCHAR(255),
    tenant_id VARCHAR(255),
    printhouse_id VARCHAR(255),
    customer_id VARCHAR(255),
    source_order_id VARCHAR(255),
    action VARCHAR(100) NOT NULL,
    decision VARCHAR(50) NOT NULL,
    blocking_reasons_json JSON,
    warning_reasons_json JSON,
    actor_user_id VARCHAR(255),
    actor_role VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
