-- migrations/038_phase98_financial_operations_partner_sandbox.sql

CREATE TABLE IF NOT EXISTS financial_operations_partner_sandboxes (
    id VARCHAR(255) PRIMARY KEY,
    sandbox_id VARCHAR(255) NOT NULL,
    tenant_id VARCHAR(255) NOT NULL,
    partner_id VARCHAR(255),
    partner_type VARCHAR(50) NOT NULL,
    sandbox_name VARCHAR(255) NOT NULL,
    sandbox_status VARCHAR(50) NOT NULL,
    sandbox_scope VARCHAR(50) NOT NULL,
    allowed_operation_types_json JSON,
    blocked_operation_types_json JSON,
    max_requests_per_day INT,
    max_orders INT,
    max_invoices INT,
    max_total_amount DECIMAL(15, 2),
    currency VARCHAR(10),
    requires_manual_approval BOOLEAN DEFAULT TRUE,
    sandbox_only BOOLEAN DEFAULT TRUE,
    mock_provider_enabled BOOLEAN DEFAULT TRUE,
    external_execution_enabled BOOLEAN DEFAULT FALSE,
    full_public_enabled BOOLEAN DEFAULT FALSE,
    evidence_json JSON,
    metadata_json JSON,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    activated_at TIMESTAMP,
    activated_by VARCHAR(255),
    suspended_at TIMESTAMP,
    suspended_by VARCHAR(255),
    revoked_at TIMESTAMP,
    revoked_by VARCHAR(255),
    closed_at TIMESTAMP,
    closed_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_partner_sandbox_sessions (
    id VARCHAR(255) PRIMARY KEY,
    sandbox_session_id VARCHAR(255) NOT NULL,
    sandbox_id VARCHAR(255) NOT NULL,
    tenant_id VARCHAR(255) NOT NULL,
    partner_id VARCHAR(255),
    pilot_program_id VARCHAR(255),
    release_gate_id VARCHAR(255),
    readiness_run_id VARCHAR(255),
    session_status VARCHAR(50) NOT NULL,
    access_mode VARCHAR(50) NOT NULL,
    expires_at TIMESTAMP,
    allowed_operations_json JSON,
    rate_limit_snapshot_json JSON,
    evidence_json JSON,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    revoked_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_partner_sandbox_runs (
    id VARCHAR(255) PRIMARY KEY,
    sandbox_run_id VARCHAR(255) NOT NULL,
    sandbox_session_id VARCHAR(255) NOT NULL,
    sandbox_id VARCHAR(255) NOT NULL,
    tenant_id VARCHAR(255) NOT NULL,
    partner_id VARCHAR(255),
    pilot_run_id VARCHAR(255),
    order_id VARCHAR(255),
    invoice_id VARCHAR(255),
    operation_type VARCHAR(100) NOT NULL,
    run_status VARCHAR(50) NOT NULL,
    execution_mode VARCHAR(50) NOT NULL,
    mock_provider_name VARCHAR(100),
    amount DECIMAL(15, 2),
    currency VARCHAR(10),
    request_payload_json JSON,
    response_payload_json JSON,
    blockers_json JSON,
    warnings_json JSON,
    evidence_json JSON,
    source_snapshot_json JSON,
    result_snapshot_json JSON,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    completed_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_partner_sandbox_findings (
    id VARCHAR(255) PRIMARY KEY,
    sandbox_run_id VARCHAR(255) NOT NULL,
    finding_code VARCHAR(100) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    category VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    recommended_action TEXT,
    evidence_json JSON,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    resolved_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_partner_sandbox_audit_events (
    id VARCHAR(255) PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    actor_id VARCHAR(255),
    actor_type VARCHAR(50) NOT NULL,
    sandbox_id VARCHAR(255),
    sandbox_session_id VARCHAR(255),
    sandbox_run_id VARCHAR(255),
    pilot_program_id VARCHAR(255),
    pilot_run_id VARCHAR(255),
    release_gate_id VARCHAR(255),
    readiness_run_id VARCHAR(255),
    tenant_id VARCHAR(255),
    partner_id VARCHAR(255),
    order_id VARCHAR(255),
    invoice_id VARCHAR(255),
    payload_json JSON,
    created_at TIMESTAMP NOT NULL
);
