-- migrations/043_phase103_provider_credential_vault_readiness.sql

CREATE TABLE IF NOT EXISTS financial_operations_provider_credential_vaults (
    id VARCHAR(255) PRIMARY KEY,
    credential_vault_id VARCHAR(255) NOT NULL,
    tenant_id VARCHAR(255),
    provider_contract_id VARCHAR(255),
    provider_sla_id VARCHAR(255),
    provider_sandbox_id VARCHAR(255),
    provider_key VARCHAR(100) NOT NULL,
    provider_type VARCHAR(100) NOT NULL,
    provider_name VARCHAR(255) NOT NULL,
    vault_status VARCHAR(50) NOT NULL,
    vault_scope VARCHAR(255),
    credential_mode VARCHAR(50) NOT NULL,
    credential_reference VARCHAR(255),
    credential_reference_hash VARCHAR(255),
    secret_material_present BOOLEAN DEFAULT FALSE,
    live_credentials_present BOOLEAN DEFAULT FALSE,
    sandbox_credentials_present BOOLEAN DEFAULT FALSE,
    mock_secret_enabled BOOLEAN DEFAULT TRUE,
    stubbed_secret_enabled BOOLEAN DEFAULT TRUE,
    redaction_required BOOLEAN DEFAULT TRUE,
    rotation_required BOOLEAN DEFAULT TRUE,
    live_provider_connectivity_enabled BOOLEAN DEFAULT FALSE,
    full_public_enabled BOOLEAN DEFAULT FALSE,
    evidence_json JSON,
    metadata_json JSON,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    activated_at TIMESTAMP,
    activated_by VARCHAR(255),
    suspended_at TIMESTAMP,
    suspended_by VARCHAR(255),
    revoked_at TIMESTAMP,
    revoked_by VARCHAR(255),
    closed_at TIMESTAMP,
    closed_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_provider_credential_checks (
    id VARCHAR(255) PRIMARY KEY,
    credential_check_id VARCHAR(255) NOT NULL,
    credential_vault_id VARCHAR(255) NOT NULL,
    tenant_id VARCHAR(255),
    provider_key VARCHAR(100) NOT NULL,
    provider_type VARCHAR(100) NOT NULL,
    check_status VARCHAR(50) NOT NULL,
    check_type VARCHAR(100) NOT NULL,
    credential_mode VARCHAR(50) NOT NULL,
    blockers_json JSON,
    warnings_json JSON,
    evidence_json JSON,
    result_snapshot_json JSON,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    completed_at TIMESTAMP,
    completed_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_provider_credential_rotation_reviews (
    id VARCHAR(255) PRIMARY KEY,
    rotation_review_id VARCHAR(255) NOT NULL,
    credential_vault_id VARCHAR(255) NOT NULL,
    tenant_id VARCHAR(255),
    provider_key VARCHAR(100) NOT NULL,
    provider_type VARCHAR(100) NOT NULL,
    rotation_status VARCHAR(50) NOT NULL,
    rotation_policy_json JSON,
    next_rotation_due_at TIMESTAMP,
    last_rotation_reviewed_at TIMESTAMP,
    evidence_json JSON,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    approved_at TIMESTAMP,
    approved_by VARCHAR(255),
    revoked_at TIMESTAMP,
    revoked_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_provider_credential_findings (
    id VARCHAR(255) PRIMARY KEY,
    credential_vault_id VARCHAR(255) NOT NULL,
    credential_check_id VARCHAR(255),
    rotation_review_id VARCHAR(255),
    finding_code VARCHAR(100) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    category VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    recommended_action TEXT,
    evidence_json JSON,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    resolved_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_provider_credential_audit_events (
    id VARCHAR(255) PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    actor_id VARCHAR(255),
    actor_type VARCHAR(50) NOT NULL,
    credential_vault_id VARCHAR(255),
    credential_check_id VARCHAR(255),
    rotation_review_id VARCHAR(255),
    provider_contract_id VARCHAR(255),
    provider_sla_id VARCHAR(255),
    provider_sandbox_id VARCHAR(255),
    tenant_id VARCHAR(255),
    provider_key VARCHAR(100),
    provider_type VARCHAR(100),
    payload_json JSON,
    created_at TIMESTAMP NOT NULL
);
