-- migrations/044_phase104_provider_webhook_sandbox_readiness.sql

CREATE TABLE IF NOT EXISTS financial_operations_provider_webhook_sandboxes (
    id VARCHAR(255) PRIMARY KEY,
    webhook_sandbox_id VARCHAR(255) NOT NULL,
    tenant_id VARCHAR(255),
    provider_sandbox_id VARCHAR(255),
    credential_vault_id VARCHAR(255),
    provider_contract_id VARCHAR(255),
    provider_sla_id VARCHAR(255),
    provider_key VARCHAR(100) NOT NULL,
    provider_type VARCHAR(100) NOT NULL,
    provider_name VARCHAR(255) NOT NULL,
    webhook_status VARCHAR(50) NOT NULL,
    webhook_scope VARCHAR(255),
    webhook_mode VARCHAR(50) NOT NULL,
    endpoint_mode VARCHAR(50) NOT NULL,
    endpoint_reference VARCHAR(255),
    endpoint_reference_hash VARCHAR(255),
    live_endpoint_enabled BOOLEAN DEFAULT FALSE,
    sandbox_endpoint_enabled BOOLEAN DEFAULT TRUE,
    mock_webhook_enabled BOOLEAN DEFAULT TRUE,
    stubbed_webhook_enabled BOOLEAN DEFAULT TRUE,
    live_signing_secret_present BOOLEAN DEFAULT FALSE,
    sandbox_signing_secret_present BOOLEAN DEFAULT FALSE,
    signature_validation_mode VARCHAR(50),
    redaction_required BOOLEAN DEFAULT TRUE,
    replay_protection_required BOOLEAN DEFAULT TRUE,
    idempotency_required BOOLEAN DEFAULT TRUE,
    live_provider_connectivity_enabled BOOLEAN DEFAULT FALSE,
    full_public_enabled BOOLEAN DEFAULT FALSE,
    evidence_json JSONB,
    metadata_json JSONB,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    activated_at TIMESTAMP,
    activated_by VARCHAR(255),
    suspended_at TIMESTAMP,
    suspended_by VARCHAR(255),
    revoked_at TIMESTAMP,
    revoked_by VARCHAR(255),
    closed_at TIMESTAMP,
    closed_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_provider_webhook_event_tests (
    id VARCHAR(255) PRIMARY KEY,
    webhook_event_test_id VARCHAR(255) NOT NULL,
    webhook_sandbox_id VARCHAR(255) NOT NULL,
    tenant_id VARCHAR(255),
    provider_key VARCHAR(100) NOT NULL,
    provider_type VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    event_status VARCHAR(50) NOT NULL,
    webhook_mode VARCHAR(50) NOT NULL,
    request_payload_json JSONB,
    signature_payload_json JSONB,
    response_payload_json JSONB,
    blockers_json JSONB,
    warnings_json JSONB,
    evidence_json JSONB,
    result_snapshot_json JSONB,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    completed_at TIMESTAMP,
    completed_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_provider_webhook_replay_reviews (
    id VARCHAR(255) PRIMARY KEY,
    replay_review_id VARCHAR(255) NOT NULL,
    webhook_sandbox_id VARCHAR(255) NOT NULL,
    tenant_id VARCHAR(255),
    provider_key VARCHAR(100) NOT NULL,
    provider_type VARCHAR(100) NOT NULL,
    replay_status VARCHAR(50) NOT NULL,
    idempotency_key VARCHAR(255),
    replay_window_seconds INT,
    duplicate_detection_status VARCHAR(50),
    evidence_json JSONB,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    approved_at TIMESTAMP,
    approved_by VARCHAR(255),
    revoked_at TIMESTAMP,
    revoked_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_provider_webhook_findings (
    id VARCHAR(255) PRIMARY KEY,
    webhook_sandbox_id VARCHAR(255) NOT NULL,
    webhook_event_test_id VARCHAR(255),
    replay_review_id VARCHAR(255),
    finding_code VARCHAR(100) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    category VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    recommended_action TEXT,
    evidence_json JSONB,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    resolved_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_provider_webhook_audit_events (
    id VARCHAR(255) PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    actor_id VARCHAR(255),
    actor_type VARCHAR(50) NOT NULL,
    webhook_sandbox_id VARCHAR(255),
    webhook_event_test_id VARCHAR(255),
    replay_review_id VARCHAR(255),
    credential_vault_id VARCHAR(255),
    provider_sandbox_id VARCHAR(255),
    provider_contract_id VARCHAR(255),
    provider_sla_id VARCHAR(255),
    tenant_id VARCHAR(255),
    provider_key VARCHAR(100),
    provider_type VARCHAR(100),
    payload_json JSONB,
    created_at TIMESTAMP NOT NULL
);
