-- migrations/046_phase106_provider_failure_retry_readiness.sql

CREATE TABLE IF NOT EXISTS financial_operations_provider_failure_retry_runs (
    id VARCHAR(255) PRIMARY KEY,
    failure_retry_run_id VARCHAR(255) NOT NULL,
    tenant_id VARCHAR(255),
    provider_key VARCHAR(100) NOT NULL,
    provider_type VARCHAR(100) NOT NULL,
    provider_name VARCHAR(255) NOT NULL,
    event_reconciliation_run_id VARCHAR(255),
    webhook_sandbox_id VARCHAR(255),
    provider_sandbox_id VARCHAR(255),
    credential_vault_id VARCHAR(255),
    readiness_run_id VARCHAR(255),
    retry_status VARCHAR(50) NOT NULL,
    retry_scope VARCHAR(255),
    failure_mode VARCHAR(50) NOT NULL,
    retry_mode VARCHAR(50) NOT NULL,
    retry_policy_json JSONB,
    max_attempts INT DEFAULT 0,
    attempted_count INT DEFAULT 0,
    simulated_success_count INT DEFAULT 0,
    simulated_failure_count INT DEFAULT 0,
    circuit_breaker_status VARCHAR(50),
    dead_letter_status VARCHAR(50),
    blockers_json JSONB,
    warnings_json JSONB,
    evidence_json JSONB,
    source_snapshot_json JSONB,
    result_snapshot_json JSONB,
    metadata_json JSONB,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    completed_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_provider_failure_retry_attempts (
    id VARCHAR(255) PRIMARY KEY,
    retry_attempt_id VARCHAR(255) NOT NULL,
    failure_retry_run_id VARCHAR(255) NOT NULL,
    tenant_id VARCHAR(255),
    provider_key VARCHAR(100) NOT NULL,
    provider_type VARCHAR(100) NOT NULL,
    operation_type VARCHAR(100) NOT NULL,
    attempt_number INT NOT NULL,
    attempt_status VARCHAR(50) NOT NULL,
    failure_code VARCHAR(100),
    failure_category VARCHAR(100),
    retry_delay_ms INT,
    backoff_strategy VARCHAR(50),
    circuit_breaker_state VARCHAR(50),
    request_payload_json JSONB,
    response_payload_json JSONB,
    redacted_payload_json JSONB,
    evidence_json JSONB,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS financial_operations_provider_circuit_breaker_reviews (
    id VARCHAR(255) PRIMARY KEY,
    circuit_breaker_review_id VARCHAR(255) NOT NULL,
    failure_retry_run_id VARCHAR(255) NOT NULL,
    tenant_id VARCHAR(255),
    provider_key VARCHAR(100) NOT NULL,
    provider_type VARCHAR(100) NOT NULL,
    circuit_breaker_status VARCHAR(50) NOT NULL,
    threshold_policy_json JSONB,
    open_condition_json JSONB,
    half_open_condition_json JSONB,
    close_condition_json JSONB,
    evidence_json JSONB,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    approved_at TIMESTAMP,
    approved_by VARCHAR(255),
    revoked_at TIMESTAMP,
    revoked_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_provider_failure_retry_findings (
    id VARCHAR(255) PRIMARY KEY,
    failure_retry_run_id VARCHAR(255) NOT NULL,
    retry_attempt_id VARCHAR(255),
    circuit_breaker_review_id VARCHAR(255),
    finding_code VARCHAR(100) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    category VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    recommended_action TEXT,
    evidence_json JSONB,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    resolved_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_provider_failure_retry_audit_events (
    id VARCHAR(255) PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    actor_id VARCHAR(255),
    actor_type VARCHAR(50) NOT NULL,
    failure_retry_run_id VARCHAR(255),
    retry_attempt_id VARCHAR(255),
    circuit_breaker_review_id VARCHAR(255),
    event_reconciliation_run_id VARCHAR(255),
    webhook_sandbox_id VARCHAR(255),
    provider_sandbox_id VARCHAR(255),
    credential_vault_id VARCHAR(255),
    tenant_id VARCHAR(255),
    provider_key VARCHAR(100),
    provider_type VARCHAR(100),
    payload_json JSONB,
    created_at TIMESTAMP NOT NULL
);
