-- migrations/047_phase107_provider_settlement_file_readiness.sql

CREATE TABLE IF NOT EXISTS financial_operations_provider_settlement_file_runs (
    id VARCHAR(255) PRIMARY KEY,
    settlement_file_run_id VARCHAR(255) NOT NULL,
    tenant_id VARCHAR(255),
    provider_key VARCHAR(100) NOT NULL,
    provider_type VARCHAR(100) NOT NULL,
    provider_name VARCHAR(255) NOT NULL,
    settlement_status VARCHAR(50) NOT NULL,
    settlement_scope VARCHAR(255),
    file_mode VARCHAR(50) NOT NULL,
    file_format VARCHAR(50) NOT NULL,
    file_name VARCHAR(255),
    file_reference VARCHAR(255),
    file_reference_hash VARCHAR(255),
    source_row_count INT DEFAULT 0,
    parsed_row_count INT DEFAULT 0,
    matched_row_count INT DEFAULT 0,
    unmatched_row_count INT DEFAULT 0,
    duplicate_row_count INT DEFAULT 0,
    mismatched_row_count INT DEFAULT 0,
    total_gross_amount DECIMAL(19,4),
    total_fee_amount DECIMAL(19,4),
    total_net_amount DECIMAL(19,4),
    currency VARCHAR(10),
    blockers_json JSON,
    warnings_json JSON,
    evidence_json JSON,
    source_snapshot_json JSON,
    result_snapshot_json JSON,
    metadata_json JSON,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    completed_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_provider_settlement_file_rows (
    id VARCHAR(255) PRIMARY KEY,
    settlement_row_id VARCHAR(255) NOT NULL,
    settlement_file_run_id VARCHAR(255) NOT NULL,
    tenant_id VARCHAR(255),
    provider_key VARCHAR(100) NOT NULL,
    provider_type VARCHAR(100) NOT NULL,
    `row_number` INT NOT NULL,
    row_status VARCHAR(50) NOT NULL,
    transaction_reference VARCHAR(255),
    provider_transaction_id VARCHAR(255),
    internal_reference_id VARCHAR(255),
    internal_reference_type VARCHAR(50),
    settlement_date TIMESTAMP,
    gross_amount DECIMAL(19,4),
    fee_amount DECIMAL(19,4),
    net_amount DECIMAL(19,4),
    currency VARCHAR(10),
    row_payload_json JSON,
    normalized_row_json JSON,
    redacted_payload_json JSON,
    evidence_json JSON,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS financial_operations_provider_settlement_matches (
    id VARCHAR(255) PRIMARY KEY,
    settlement_match_id VARCHAR(255) NOT NULL,
    settlement_file_run_id VARCHAR(255) NOT NULL,
    settlement_row_id VARCHAR(255) NOT NULL,
    internal_reference_id VARCHAR(255),
    internal_reference_type VARCHAR(50),
    match_status VARCHAR(50) NOT NULL,
    match_confidence VARCHAR(50),
    match_reason TEXT,
    gross_amount_match_status VARCHAR(50),
    fee_amount_match_status VARCHAR(50),
    net_amount_match_status VARCHAR(50),
    currency_match_status VARCHAR(50),
    settlement_date_match_status VARCHAR(50),
    evidence_json JSON,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    resolved_at TIMESTAMP,
    resolved_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_provider_settlement_findings (
    id VARCHAR(255) PRIMARY KEY,
    settlement_file_run_id VARCHAR(255) NOT NULL,
    settlement_row_id VARCHAR(255),
    settlement_match_id VARCHAR(255),
    finding_code VARCHAR(100) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    category VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    recommended_action TEXT,
    evidence_json JSON,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    resolved_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_provider_settlement_audit_events (
    id VARCHAR(255) PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    actor_id VARCHAR(255),
    actor_type VARCHAR(50) NOT NULL,
    settlement_file_run_id VARCHAR(255),
    settlement_row_id VARCHAR(255),
    settlement_match_id VARCHAR(255),
    tenant_id VARCHAR(255),
    provider_key VARCHAR(100),
    provider_type VARCHAR(100),
    payload_json JSON,
    created_at TIMESTAMP NOT NULL
);
