-- migrations/053_phase113_financial_operations_production_activation_gate.sql

CREATE TABLE IF NOT EXISTS financial_operations_production_activation_gates (
    id VARCHAR(255) PRIMARY KEY,
    production_activation_gate_id VARCHAR(255) NOT NULL,
    tenant_id VARCHAR(255),
    activation_gate_name VARCHAR(255) NOT NULL,
    activation_gate_status VARCHAR(50) NOT NULL,
    activation_gate_scope VARCHAR(255),
    activation_gate_mode VARCHAR(50),
    final_release_candidate_id VARCHAR(255),
    pre_production_runbook_id VARCHAR(255),
    go_live_simulation_id VARCHAR(255),
    activation_review_id VARCHAR(255),
    readiness_run_id VARCHAR(255),
    approval_status VARCHAR(50),
    activation_eligibility_status VARCHAR(50),
    production_activation_enabled BOOLEAN DEFAULT FALSE,
    activation_execution_enabled BOOLEAN DEFAULT FALSE,
    full_public_enabled BOOLEAN DEFAULT FALSE,
    live_provider_connectivity_enabled BOOLEAN DEFAULT FALSE,
    live_credentials_enabled BOOLEAN DEFAULT FALSE,
    payment_execution_enabled BOOLEAN DEFAULT FALSE,
    refund_execution_enabled BOOLEAN DEFAULT FALSE,
    payout_execution_enabled BOOLEAN DEFAULT FALSE,
    external_invoice_submission_enabled BOOLEAN DEFAULT FALSE,
    tax_filing_enabled BOOLEAN DEFAULT FALSE,
    vat_return_submission_enabled BOOLEAN DEFAULT FALSE,
    external_report_submission_enabled BOOLEAN DEFAULT FALSE,
    live_personal_data_export_enabled BOOLEAN DEFAULT FALSE,
    source_record_mutation_enabled BOOLEAN DEFAULT FALSE,
    blockers_json JSON,
    warnings_json JSON,
    evidence_json JSON,
    source_snapshot_json JSON,
    result_snapshot_json JSON,
    metadata_json JSON,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    completed_by VARCHAR(255),
    approved_at TIMESTAMP,
    approved_by VARCHAR(255),
    revoked_at TIMESTAMP,
    revoked_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_production_activation_gate_checks (
    id VARCHAR(255) PRIMARY KEY,
    activation_gate_check_id VARCHAR(255) NOT NULL,
    production_activation_gate_id VARCHAR(255) NOT NULL,
    check_key VARCHAR(100) NOT NULL,
    check_label VARCHAR(255) NOT NULL,
    check_status VARCHAR(50) NOT NULL,
    check_order INT,
    category VARCHAR(100),
    required_for_activation_gate BOOLEAN DEFAULT TRUE,
    blockers_json JSON,
    warnings_json JSON,
    evidence_json JSON,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    completed_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_production_activation_gate_approvals (
    id VARCHAR(255) PRIMARY KEY,
    activation_gate_approval_id VARCHAR(255) NOT NULL,
    production_activation_gate_id VARCHAR(255) NOT NULL,
    approval_role VARCHAR(100) NOT NULL,
    approval_status VARCHAR(50) NOT NULL,
    approver_reference VARCHAR(255),
    approver_reference_hash VARCHAR(255),
    approval_notes_json JSON,
    evidence_json JSON,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    approved_at TIMESTAMP,
    approved_by VARCHAR(255),
    rejected_at TIMESTAMP,
    rejected_by VARCHAR(255),
    revoked_at TIMESTAMP,
    revoked_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_production_activation_gate_findings (
    id VARCHAR(255) PRIMARY KEY,
    production_activation_gate_id VARCHAR(255),
    activation_gate_check_id VARCHAR(255),
    activation_gate_approval_id VARCHAR(255),
    finding_code VARCHAR(100) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    category VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    recommended_action TEXT,
    evidence_json JSON,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    resolved_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS financial_operations_production_activation_gate_audit_events (
    id VARCHAR(255) PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    actor_id VARCHAR(255),
    actor_type VARCHAR(50) NOT NULL,
    production_activation_gate_id VARCHAR(255),
    activation_gate_check_id VARCHAR(255),
    activation_gate_approval_id VARCHAR(255),
    tenant_id VARCHAR(255),
    payload_json JSON,
    created_at TIMESTAMP NOT NULL
);
