-- Migration 077: Phase 130 Controlled Beta Cohort Runtime Observation & Operational Monitoring

CREATE TABLE controlled_beta_runtime_observation_sessions (
  observation_id VARCHAR(128) PRIMARY KEY,
  activation_id VARCHAR(128) NOT NULL,
  gate_id VARCHAR(128) NOT NULL,
  cohort_id VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  participant_id VARCHAR(128) NOT NULL,
  session_id VARCHAR(128) NOT NULL,
  observation_status VARCHAR(64) NOT NULL,
  observation_severity VARCHAR(64) NOT NULL,
  observation_source VARCHAR(64) NOT NULL,
  runtime_truth_status VARCHAR(64) NOT NULL,
  persistence_status VARCHAR(64) NOT NULL,
  verified_from_db TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase129 TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase128_1 TINYINT(1) NOT NULL DEFAULT 0,
  evidence_integrity_hash VARCHAR(256),
  
  full_public_enabled TINYINT(1) NOT NULL DEFAULT 0,
  open_marketplace_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payment_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  refund_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payout_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  provider_external_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_tax_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_accounting_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  source_mutation_enabled TINYINT(1) NOT NULL DEFAULT 0,
  
  invite_only TINYINT(1) NOT NULL DEFAULT 1,
  cohort_scoped TINYINT(1) NOT NULL DEFAULT 1,
  tenant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  participant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  kill_switch_ready TINYINT(1) NOT NULL DEFAULT 1,
  
  observed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  INDEX idx_cb_obs_sess_act (activation_id),
  INDEX idx_cb_obs_sess_gate (gate_id),
  INDEX idx_cb_obs_sess_cohort (cohort_id),
  INDEX idx_cb_obs_sess_tenant (tenant_id),
  INDEX idx_cb_obs_sess_part (participant_id),
  INDEX idx_cb_obs_sess_sess (session_id),
  INDEX idx_cb_obs_sess_status (observation_status),
  INDEX idx_cb_obs_sess_sev (observation_severity),
  INDEX idx_cb_obs_sess_obs_at (observed_at),
  INDEX idx_cb_obs_sess_creat (created_at),
  INDEX idx_cb_obs_sess_hash (evidence_integrity_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE controlled_beta_runtime_observation_events (
  observation_id VARCHAR(128) PRIMARY KEY,
  activation_id VARCHAR(128) NOT NULL,
  gate_id VARCHAR(128) NOT NULL,
  cohort_id VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  participant_id VARCHAR(128) NOT NULL,
  session_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  observation_status VARCHAR(64) NOT NULL,
  observation_severity VARCHAR(64) NOT NULL,
  observation_source VARCHAR(64) NOT NULL,
  runtime_truth_status VARCHAR(64) NOT NULL,
  persistence_status VARCHAR(64) NOT NULL,
  verified_from_db TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase129 TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase128_1 TINYINT(1) NOT NULL DEFAULT 0,
  evidence_integrity_hash VARCHAR(256),
  
  full_public_enabled TINYINT(1) NOT NULL DEFAULT 0,
  open_marketplace_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payment_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  refund_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payout_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  provider_external_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_tax_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_accounting_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  source_mutation_enabled TINYINT(1) NOT NULL DEFAULT 0,
  
  invite_only TINYINT(1) NOT NULL DEFAULT 1,
  cohort_scoped TINYINT(1) NOT NULL DEFAULT 1,
  tenant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  participant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  kill_switch_ready TINYINT(1) NOT NULL DEFAULT 1,
  
  observed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  INDEX idx_cb_obs_ev_act (activation_id),
  INDEX idx_cb_obs_ev_gate (gate_id),
  INDEX idx_cb_obs_ev_cohort (cohort_id),
  INDEX idx_cb_obs_ev_tenant (tenant_id),
  INDEX idx_cb_obs_ev_part (participant_id),
  INDEX idx_cb_obs_ev_sess (session_id),
  INDEX idx_cb_obs_ev_type (event_type),
  INDEX idx_cb_obs_ev_status (observation_status),
  INDEX idx_cb_obs_ev_sev (observation_severity),
  INDEX idx_cb_obs_ev_obs_at (observed_at),
  INDEX idx_cb_obs_ev_creat (created_at),
  INDEX idx_cb_obs_ev_hash (evidence_integrity_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE controlled_beta_runtime_health_snapshots (
  observation_id VARCHAR(128) PRIMARY KEY,
  activation_id VARCHAR(128) NOT NULL,
  gate_id VARCHAR(128) NOT NULL,
  cohort_id VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  participant_id VARCHAR(128) NOT NULL,
  session_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  observation_status VARCHAR(64) NOT NULL,
  observation_severity VARCHAR(64) NOT NULL,
  observation_source VARCHAR(64) NOT NULL,
  runtime_truth_status VARCHAR(64) NOT NULL,
  persistence_status VARCHAR(64) NOT NULL,
  verified_from_db TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase129 TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase128_1 TINYINT(1) NOT NULL DEFAULT 0,
  evidence_integrity_hash VARCHAR(256),
  
  full_public_enabled TINYINT(1) NOT NULL DEFAULT 0,
  open_marketplace_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payment_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  refund_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payout_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  provider_external_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_tax_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_accounting_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  source_mutation_enabled TINYINT(1) NOT NULL DEFAULT 0,
  
  invite_only TINYINT(1) NOT NULL DEFAULT 1,
  cohort_scoped TINYINT(1) NOT NULL DEFAULT 1,
  tenant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  participant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  kill_switch_ready TINYINT(1) NOT NULL DEFAULT 1,
  
  observed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  INDEX idx_cb_obs_hlth_act (activation_id),
  INDEX idx_cb_obs_hlth_gate (gate_id),
  INDEX idx_cb_obs_hlth_cohort (cohort_id),
  INDEX idx_cb_obs_hlth_tenant (tenant_id),
  INDEX idx_cb_obs_hlth_part (participant_id),
  INDEX idx_cb_obs_hlth_sess (session_id),
  INDEX idx_cb_obs_hlth_type (event_type),
  INDEX idx_cb_obs_hlth_status (observation_status),
  INDEX idx_cb_obs_hlth_sev (observation_severity),
  INDEX idx_cb_obs_hlth_obs_at (observed_at),
  INDEX idx_cb_obs_hlth_creat (created_at),
  INDEX idx_cb_obs_hlth_hash (evidence_integrity_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE controlled_beta_runtime_participant_activity (
  observation_id VARCHAR(128) PRIMARY KEY,
  activation_id VARCHAR(128) NOT NULL,
  gate_id VARCHAR(128) NOT NULL,
  cohort_id VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  participant_id VARCHAR(128) NOT NULL,
  session_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  observation_status VARCHAR(64) NOT NULL,
  observation_severity VARCHAR(64) NOT NULL,
  observation_source VARCHAR(64) NOT NULL,
  runtime_truth_status VARCHAR(64) NOT NULL,
  persistence_status VARCHAR(64) NOT NULL,
  verified_from_db TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase129 TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase128_1 TINYINT(1) NOT NULL DEFAULT 0,
  evidence_integrity_hash VARCHAR(256),
  
  full_public_enabled TINYINT(1) NOT NULL DEFAULT 0,
  open_marketplace_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payment_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  refund_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payout_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  provider_external_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_tax_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_accounting_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  source_mutation_enabled TINYINT(1) NOT NULL DEFAULT 0,
  
  invite_only TINYINT(1) NOT NULL DEFAULT 1,
  cohort_scoped TINYINT(1) NOT NULL DEFAULT 1,
  tenant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  participant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  kill_switch_ready TINYINT(1) NOT NULL DEFAULT 1,
  
  observed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  INDEX idx_cb_obs_pa_act (activation_id),
  INDEX idx_cb_obs_pa_gate (gate_id),
  INDEX idx_cb_obs_pa_cohort (cohort_id),
  INDEX idx_cb_obs_pa_tenant (tenant_id),
  INDEX idx_cb_obs_pa_part (participant_id),
  INDEX idx_cb_obs_pa_sess (session_id),
  INDEX idx_cb_obs_pa_type (event_type),
  INDEX idx_cb_obs_pa_status (observation_status),
  INDEX idx_cb_obs_pa_sev (observation_severity),
  INDEX idx_cb_obs_pa_obs_at (observed_at),
  INDEX idx_cb_obs_pa_creat (created_at),
  INDEX idx_cb_obs_pa_hash (evidence_integrity_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE controlled_beta_runtime_access_observations (
  observation_id VARCHAR(128) PRIMARY KEY,
  activation_id VARCHAR(128) NOT NULL,
  gate_id VARCHAR(128) NOT NULL,
  cohort_id VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  participant_id VARCHAR(128) NOT NULL,
  session_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  observation_status VARCHAR(64) NOT NULL,
  observation_severity VARCHAR(64) NOT NULL,
  observation_source VARCHAR(64) NOT NULL,
  runtime_truth_status VARCHAR(64) NOT NULL,
  persistence_status VARCHAR(64) NOT NULL,
  verified_from_db TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase129 TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase128_1 TINYINT(1) NOT NULL DEFAULT 0,
  evidence_integrity_hash VARCHAR(256),
  
  full_public_enabled TINYINT(1) NOT NULL DEFAULT 0,
  open_marketplace_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payment_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  refund_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payout_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  provider_external_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_tax_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_accounting_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  source_mutation_enabled TINYINT(1) NOT NULL DEFAULT 0,
  
  invite_only TINYINT(1) NOT NULL DEFAULT 1,
  cohort_scoped TINYINT(1) NOT NULL DEFAULT 1,
  tenant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  participant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  kill_switch_ready TINYINT(1) NOT NULL DEFAULT 1,
  
  observed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  INDEX idx_cb_obs_ao_act (activation_id),
  INDEX idx_cb_obs_ao_gate (gate_id),
  INDEX idx_cb_obs_ao_cohort (cohort_id),
  INDEX idx_cb_obs_ao_tenant (tenant_id),
  INDEX idx_cb_obs_ao_part (participant_id),
  INDEX idx_cb_obs_ao_sess (session_id),
  INDEX idx_cb_obs_ao_type (event_type),
  INDEX idx_cb_obs_ao_status (observation_status),
  INDEX idx_cb_obs_ao_sev (observation_severity),
  INDEX idx_cb_obs_ao_obs_at (observed_at),
  INDEX idx_cb_obs_ao_creat (created_at),
  INDEX idx_cb_obs_ao_hash (evidence_integrity_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE controlled_beta_runtime_guardrail_observations (
  observation_id VARCHAR(128) PRIMARY KEY,
  activation_id VARCHAR(128) NOT NULL,
  gate_id VARCHAR(128) NOT NULL,
  cohort_id VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  participant_id VARCHAR(128) NOT NULL,
  session_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  observation_status VARCHAR(64) NOT NULL,
  observation_severity VARCHAR(64) NOT NULL,
  observation_source VARCHAR(64) NOT NULL,
  runtime_truth_status VARCHAR(64) NOT NULL,
  persistence_status VARCHAR(64) NOT NULL,
  verified_from_db TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase129 TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase128_1 TINYINT(1) NOT NULL DEFAULT 0,
  evidence_integrity_hash VARCHAR(256),
  
  full_public_enabled TINYINT(1) NOT NULL DEFAULT 0,
  open_marketplace_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payment_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  refund_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payout_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  provider_external_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_tax_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_accounting_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  source_mutation_enabled TINYINT(1) NOT NULL DEFAULT 0,
  
  invite_only TINYINT(1) NOT NULL DEFAULT 1,
  cohort_scoped TINYINT(1) NOT NULL DEFAULT 1,
  tenant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  participant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  kill_switch_ready TINYINT(1) NOT NULL DEFAULT 1,
  
  observed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  INDEX idx_cb_obs_go_act (activation_id),
  INDEX idx_cb_obs_go_gate (gate_id),
  INDEX idx_cb_obs_go_cohort (cohort_id),
  INDEX idx_cb_obs_go_tenant (tenant_id),
  INDEX idx_cb_obs_go_part (participant_id),
  INDEX idx_cb_obs_go_sess (session_id),
  INDEX idx_cb_obs_go_type (event_type),
  INDEX idx_cb_obs_go_status (observation_status),
  INDEX idx_cb_obs_go_sev (observation_severity),
  INDEX idx_cb_obs_go_obs_at (observed_at),
  INDEX idx_cb_obs_go_creat (created_at),
  INDEX idx_cb_obs_go_hash (evidence_integrity_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE controlled_beta_runtime_incident_observations (
  observation_id VARCHAR(128) PRIMARY KEY,
  activation_id VARCHAR(128) NOT NULL,
  gate_id VARCHAR(128) NOT NULL,
  cohort_id VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  participant_id VARCHAR(128) NOT NULL,
  session_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  observation_status VARCHAR(64) NOT NULL,
  observation_severity VARCHAR(64) NOT NULL,
  observation_source VARCHAR(64) NOT NULL,
  runtime_truth_status VARCHAR(64) NOT NULL,
  persistence_status VARCHAR(64) NOT NULL,
  verified_from_db TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase129 TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase128_1 TINYINT(1) NOT NULL DEFAULT 0,
  evidence_integrity_hash VARCHAR(256),
  
  full_public_enabled TINYINT(1) NOT NULL DEFAULT 0,
  open_marketplace_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payment_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  refund_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payout_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  provider_external_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_tax_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_accounting_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  source_mutation_enabled TINYINT(1) NOT NULL DEFAULT 0,
  
  invite_only TINYINT(1) NOT NULL DEFAULT 1,
  cohort_scoped TINYINT(1) NOT NULL DEFAULT 1,
  tenant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  participant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  kill_switch_ready TINYINT(1) NOT NULL DEFAULT 1,
  
  observed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  INDEX idx_cb_obs_io_act (activation_id),
  INDEX idx_cb_obs_io_gate (gate_id),
  INDEX idx_cb_obs_io_cohort (cohort_id),
  INDEX idx_cb_obs_io_tenant (tenant_id),
  INDEX idx_cb_obs_io_part (participant_id),
  INDEX idx_cb_obs_io_sess (session_id),
  INDEX idx_cb_obs_io_type (event_type),
  INDEX idx_cb_obs_io_status (observation_status),
  INDEX idx_cb_obs_io_sev (observation_severity),
  INDEX idx_cb_obs_io_obs_at (observed_at),
  INDEX idx_cb_obs_io_creat (created_at),
  INDEX idx_cb_obs_io_hash (evidence_integrity_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE controlled_beta_runtime_support_observations (
  observation_id VARCHAR(128) PRIMARY KEY,
  activation_id VARCHAR(128) NOT NULL,
  gate_id VARCHAR(128) NOT NULL,
  cohort_id VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  participant_id VARCHAR(128) NOT NULL,
  session_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  observation_status VARCHAR(64) NOT NULL,
  observation_severity VARCHAR(64) NOT NULL,
  observation_source VARCHAR(64) NOT NULL,
  runtime_truth_status VARCHAR(64) NOT NULL,
  persistence_status VARCHAR(64) NOT NULL,
  verified_from_db TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase129 TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase128_1 TINYINT(1) NOT NULL DEFAULT 0,
  evidence_integrity_hash VARCHAR(256),
  
  full_public_enabled TINYINT(1) NOT NULL DEFAULT 0,
  open_marketplace_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payment_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  refund_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payout_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  provider_external_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_tax_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_accounting_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  source_mutation_enabled TINYINT(1) NOT NULL DEFAULT 0,
  
  invite_only TINYINT(1) NOT NULL DEFAULT 1,
  cohort_scoped TINYINT(1) NOT NULL DEFAULT 1,
  tenant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  participant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  kill_switch_ready TINYINT(1) NOT NULL DEFAULT 1,
  
  observed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  INDEX idx_cb_obs_so_act (activation_id),
  INDEX idx_cb_obs_so_gate (gate_id),
  INDEX idx_cb_obs_so_cohort (cohort_id),
  INDEX idx_cb_obs_so_tenant (tenant_id),
  INDEX idx_cb_obs_so_part (participant_id),
  INDEX idx_cb_obs_so_sess (session_id),
  INDEX idx_cb_obs_so_type (event_type),
  INDEX idx_cb_obs_so_status (observation_status),
  INDEX idx_cb_obs_so_sev (observation_severity),
  INDEX idx_cb_obs_so_obs_at (observed_at),
  INDEX idx_cb_obs_so_creat (created_at),
  INDEX idx_cb_obs_so_hash (evidence_integrity_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE controlled_beta_runtime_kill_switch_observations (
  observation_id VARCHAR(128) PRIMARY KEY,
  activation_id VARCHAR(128) NOT NULL,
  gate_id VARCHAR(128) NOT NULL,
  cohort_id VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  participant_id VARCHAR(128) NOT NULL,
  session_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  observation_status VARCHAR(64) NOT NULL,
  observation_severity VARCHAR(64) NOT NULL,
  observation_source VARCHAR(64) NOT NULL,
  runtime_truth_status VARCHAR(64) NOT NULL,
  persistence_status VARCHAR(64) NOT NULL,
  verified_from_db TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase129 TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase128_1 TINYINT(1) NOT NULL DEFAULT 0,
  evidence_integrity_hash VARCHAR(256),
  
  full_public_enabled TINYINT(1) NOT NULL DEFAULT 0,
  open_marketplace_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payment_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  refund_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payout_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  provider_external_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_tax_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_accounting_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  source_mutation_enabled TINYINT(1) NOT NULL DEFAULT 0,
  
  invite_only TINYINT(1) NOT NULL DEFAULT 1,
  cohort_scoped TINYINT(1) NOT NULL DEFAULT 1,
  tenant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  participant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  kill_switch_ready TINYINT(1) NOT NULL DEFAULT 1,
  
  observed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  INDEX idx_cb_obs_ko_act (activation_id),
  INDEX idx_cb_obs_ko_gate (gate_id),
  INDEX idx_cb_obs_ko_cohort (cohort_id),
  INDEX idx_cb_obs_ko_tenant (tenant_id),
  INDEX idx_cb_obs_ko_part (participant_id),
  INDEX idx_cb_obs_ko_sess (session_id),
  INDEX idx_cb_obs_ko_type (event_type),
  INDEX idx_cb_obs_ko_status (observation_status),
  INDEX idx_cb_obs_ko_sev (observation_severity),
  INDEX idx_cb_obs_ko_obs_at (observed_at),
  INDEX idx_cb_obs_ko_creat (created_at),
  INDEX idx_cb_obs_ko_hash (evidence_integrity_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE controlled_beta_runtime_sla_observations (
  observation_id VARCHAR(128) PRIMARY KEY,
  activation_id VARCHAR(128) NOT NULL,
  gate_id VARCHAR(128) NOT NULL,
  cohort_id VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  participant_id VARCHAR(128) NOT NULL,
  session_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  observation_status VARCHAR(64) NOT NULL,
  observation_severity VARCHAR(64) NOT NULL,
  observation_source VARCHAR(64) NOT NULL,
  runtime_truth_status VARCHAR(64) NOT NULL,
  persistence_status VARCHAR(64) NOT NULL,
  verified_from_db TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase129 TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase128_1 TINYINT(1) NOT NULL DEFAULT 0,
  evidence_integrity_hash VARCHAR(256),
  
  full_public_enabled TINYINT(1) NOT NULL DEFAULT 0,
  open_marketplace_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payment_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  refund_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payout_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  provider_external_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_tax_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_accounting_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  source_mutation_enabled TINYINT(1) NOT NULL DEFAULT 0,
  
  invite_only TINYINT(1) NOT NULL DEFAULT 1,
  cohort_scoped TINYINT(1) NOT NULL DEFAULT 1,
  tenant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  participant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  kill_switch_ready TINYINT(1) NOT NULL DEFAULT 1,
  
  observed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  INDEX idx_cb_obs_sla_act (activation_id),
  INDEX idx_cb_obs_sla_gate (gate_id),
  INDEX idx_cb_obs_sla_cohort (cohort_id),
  INDEX idx_cb_obs_sla_tenant (tenant_id),
  INDEX idx_cb_obs_sla_part (participant_id),
  INDEX idx_cb_obs_sla_sess (session_id),
  INDEX idx_cb_obs_sla_type (event_type),
  INDEX idx_cb_obs_sla_status (observation_status),
  INDEX idx_cb_obs_sla_sev (observation_severity),
  INDEX idx_cb_obs_sla_obs_at (observed_at),
  INDEX idx_cb_obs_sla_creat (created_at),
  INDEX idx_cb_obs_sla_hash (evidence_integrity_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE controlled_beta_runtime_risk_scores (
  observation_id VARCHAR(128) PRIMARY KEY,
  activation_id VARCHAR(128) NOT NULL,
  gate_id VARCHAR(128) NOT NULL,
  cohort_id VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  participant_id VARCHAR(128) NOT NULL,
  session_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  observation_status VARCHAR(64) NOT NULL,
  observation_severity VARCHAR(64) NOT NULL,
  observation_source VARCHAR(64) NOT NULL,
  runtime_truth_status VARCHAR(64) NOT NULL,
  persistence_status VARCHAR(64) NOT NULL,
  verified_from_db TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase129 TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase128_1 TINYINT(1) NOT NULL DEFAULT 0,
  evidence_integrity_hash VARCHAR(256),
  
  full_public_enabled TINYINT(1) NOT NULL DEFAULT 0,
  open_marketplace_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payment_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  refund_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payout_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  provider_external_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_tax_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_accounting_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  source_mutation_enabled TINYINT(1) NOT NULL DEFAULT 0,
  
  invite_only TINYINT(1) NOT NULL DEFAULT 1,
  cohort_scoped TINYINT(1) NOT NULL DEFAULT 1,
  tenant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  participant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  kill_switch_ready TINYINT(1) NOT NULL DEFAULT 1,
  
  observed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  INDEX idx_cb_obs_rs_act (activation_id),
  INDEX idx_cb_obs_rs_gate (gate_id),
  INDEX idx_cb_obs_rs_cohort (cohort_id),
  INDEX idx_cb_obs_rs_tenant (tenant_id),
  INDEX idx_cb_obs_rs_part (participant_id),
  INDEX idx_cb_obs_rs_sess (session_id),
  INDEX idx_cb_obs_rs_type (event_type),
  INDEX idx_cb_obs_rs_status (observation_status),
  INDEX idx_cb_obs_rs_sev (observation_severity),
  INDEX idx_cb_obs_rs_obs_at (observed_at),
  INDEX idx_cb_obs_rs_creat (created_at),
  INDEX idx_cb_obs_rs_hash (evidence_integrity_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE controlled_beta_runtime_monitoring_findings (
  observation_id VARCHAR(128) PRIMARY KEY,
  activation_id VARCHAR(128) NOT NULL,
  gate_id VARCHAR(128) NOT NULL,
  cohort_id VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  participant_id VARCHAR(128) NOT NULL,
  session_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  observation_status VARCHAR(64) NOT NULL,
  observation_severity VARCHAR(64) NOT NULL,
  observation_source VARCHAR(64) NOT NULL,
  runtime_truth_status VARCHAR(64) NOT NULL,
  persistence_status VARCHAR(64) NOT NULL,
  verified_from_db TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase129 TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase128_1 TINYINT(1) NOT NULL DEFAULT 0,
  evidence_integrity_hash VARCHAR(256),
  
  full_public_enabled TINYINT(1) NOT NULL DEFAULT 0,
  open_marketplace_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payment_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  refund_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payout_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  provider_external_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_tax_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_accounting_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  source_mutation_enabled TINYINT(1) NOT NULL DEFAULT 0,
  
  invite_only TINYINT(1) NOT NULL DEFAULT 1,
  cohort_scoped TINYINT(1) NOT NULL DEFAULT 1,
  tenant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  participant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  kill_switch_ready TINYINT(1) NOT NULL DEFAULT 1,
  
  observed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  INDEX idx_cb_obs_mf_act (activation_id),
  INDEX idx_cb_obs_mf_gate (gate_id),
  INDEX idx_cb_obs_mf_cohort (cohort_id),
  INDEX idx_cb_obs_mf_tenant (tenant_id),
  INDEX idx_cb_obs_mf_part (participant_id),
  INDEX idx_cb_obs_mf_sess (session_id),
  INDEX idx_cb_obs_mf_type (event_type),
  INDEX idx_cb_obs_mf_status (observation_status),
  INDEX idx_cb_obs_mf_sev (observation_severity),
  INDEX idx_cb_obs_mf_obs_at (observed_at),
  INDEX idx_cb_obs_mf_creat (created_at),
  INDEX idx_cb_obs_mf_hash (evidence_integrity_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE controlled_beta_runtime_monitoring_evidence_packs (
  observation_id VARCHAR(128) PRIMARY KEY,
  activation_id VARCHAR(128) NOT NULL,
  gate_id VARCHAR(128) NOT NULL,
  cohort_id VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  participant_id VARCHAR(128) NOT NULL,
  session_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  observation_status VARCHAR(64) NOT NULL,
  observation_severity VARCHAR(64) NOT NULL,
  observation_source VARCHAR(64) NOT NULL,
  runtime_truth_status VARCHAR(64) NOT NULL,
  persistence_status VARCHAR(64) NOT NULL,
  verified_from_db TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase129 TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase128_1 TINYINT(1) NOT NULL DEFAULT 0,
  evidence_integrity_hash VARCHAR(256),
  
  full_public_enabled TINYINT(1) NOT NULL DEFAULT 0,
  open_marketplace_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payment_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  refund_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payout_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  provider_external_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_tax_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_accounting_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  source_mutation_enabled TINYINT(1) NOT NULL DEFAULT 0,
  
  invite_only TINYINT(1) NOT NULL DEFAULT 1,
  cohort_scoped TINYINT(1) NOT NULL DEFAULT 1,
  tenant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  participant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  kill_switch_ready TINYINT(1) NOT NULL DEFAULT 1,
  
  observed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  INDEX idx_cb_obs_mep_act (activation_id),
  INDEX idx_cb_obs_mep_gate (gate_id),
  INDEX idx_cb_obs_mep_cohort (cohort_id),
  INDEX idx_cb_obs_mep_tenant (tenant_id),
  INDEX idx_cb_obs_mep_part (participant_id),
  INDEX idx_cb_obs_mep_sess (session_id),
  INDEX idx_cb_obs_mep_type (event_type),
  INDEX idx_cb_obs_mep_status (observation_status),
  INDEX idx_cb_obs_mep_sev (observation_severity),
  INDEX idx_cb_obs_mep_obs_at (observed_at),
  INDEX idx_cb_obs_mep_creat (created_at),
  INDEX idx_cb_obs_mep_hash (evidence_integrity_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE controlled_beta_runtime_monitoring_audits (
  observation_id VARCHAR(128) PRIMARY KEY,
  activation_id VARCHAR(128) NOT NULL,
  gate_id VARCHAR(128) NOT NULL,
  cohort_id VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  participant_id VARCHAR(128) NOT NULL,
  session_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  observation_status VARCHAR(64) NOT NULL,
  observation_severity VARCHAR(64) NOT NULL,
  observation_source VARCHAR(64) NOT NULL,
  runtime_truth_status VARCHAR(64) NOT NULL,
  persistence_status VARCHAR(64) NOT NULL,
  verified_from_db TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase129 TINYINT(1) NOT NULL DEFAULT 0,
  verified_from_phase128_1 TINYINT(1) NOT NULL DEFAULT 0,
  evidence_integrity_hash VARCHAR(256),
  
  full_public_enabled TINYINT(1) NOT NULL DEFAULT 0,
  open_marketplace_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payment_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  refund_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  payout_execution_enabled TINYINT(1) NOT NULL DEFAULT 0,
  provider_external_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_tax_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  external_accounting_submission_enabled TINYINT(1) NOT NULL DEFAULT 0,
  source_mutation_enabled TINYINT(1) NOT NULL DEFAULT 0,
  
  invite_only TINYINT(1) NOT NULL DEFAULT 1,
  cohort_scoped TINYINT(1) NOT NULL DEFAULT 1,
  tenant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  participant_scoped TINYINT(1) NOT NULL DEFAULT 1,
  kill_switch_ready TINYINT(1) NOT NULL DEFAULT 1,
  
  observed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  INDEX idx_cb_obs_ma_act (activation_id),
  INDEX idx_cb_obs_ma_gate (gate_id),
  INDEX idx_cb_obs_ma_cohort (cohort_id),
  INDEX idx_cb_obs_ma_tenant (tenant_id),
  INDEX idx_cb_obs_ma_part (participant_id),
  INDEX idx_cb_obs_ma_sess (session_id),
  INDEX idx_cb_obs_ma_type (event_type),
  INDEX idx_cb_obs_ma_status (observation_status),
  INDEX idx_cb_obs_ma_sev (observation_severity),
  INDEX idx_cb_obs_ma_obs_at (observed_at),
  INDEX idx_cb_obs_ma_creat (created_at),
  INDEX idx_cb_obs_ma_hash (evidence_integrity_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
