-- Migration: 111_phase160_controlled_high_risk_cohort_intervention_activation_token_issuance_gate
-- Up

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_issuance (
  activation_token_issuance_id VARCHAR(64) NOT NULL PRIMARY KEY,
  source_activation_token_preflight_id VARCHAR(64) NOT NULL,
  source_activation_token_staging_id VARCHAR(64) NOT NULL,
  source_activation_token_final_apv_id VARCHAR(64) NOT NULL,
  source_activation_token_env_id VARCHAR(64) NOT NULL,
  source_activation_handoff_id VARCHAR(64) NOT NULL,
  source_activation_decision_id VARCHAR(64) NOT NULL,
  source_activation_lock_id VARCHAR(64) NOT NULL,
  source_activation_auth_id VARCHAR(64) NOT NULL,
  source_activation_readiness_id VARCHAR(64) NOT NULL,
  source_plan_id VARCHAR(64) NOT NULL,
  source_dispatcher_id VARCHAR(64) NOT NULL,
  source_envelope_id VARCHAR(64) NOT NULL,
  source_auth_id VARCHAR(64) NOT NULL,
  source_readiness_id VARCHAR(64) NOT NULL,
  source_approval_id VARCHAR(64) NOT NULL,
  source_prep_id VARCHAR(64) NOT NULL,
  source_review_id VARCHAR(64) NULL,
  source_simulation_id VARCHAR(64) NULL,
  source_execution_id VARCHAR(64) NULL,
  cohort_id VARCHAR(128) NULL,
  tenant_id VARCHAR(128) NULL,
  simulation_type VARCHAR(64) NULL,
  activation_token_issuance_status VARCHAR(64) NOT NULL DEFAULT 'DRAFT',
  activation_token_issuance_result VARCHAR(128) NULL,
  risk_level VARCHAR(32) NULL,
  confidence_level VARCHAR(32) NULL,
  projected_impact_score DECIMAL(5,2) NULL,
  rollback_feasibility_score DECIMAL(5,2) NULL,
  evidence_completeness_score DECIMAL(5,2) NULL,
  guardrail_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  write_scope_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  canary_envelope_json JSON NULL,
  token_issuance_summary_json JSON NULL,
  impact_review_json JSON NULL,
  rollback_review_json JSON NULL,
  guardrail_review_json JSON NULL,
  token_issuance_rules_json JSON NULL,
  token_issuance_blockers_json JSON NULL,
  non_execution_attestation_json JSON NULL,
  write_scope_attestation_json JSON NULL,
  non_redeemable_token_record_json JSON NULL,
  source_activation_token_preflight_hash VARCHAR(256) NULL,
  source_activation_token_staging_hash VARCHAR(256) NULL,
  source_token_material_hash VARCHAR(256) NULL,
  source_freeze_package_hash VARCHAR(256) NULL,
  activation_token_issuance_hash VARCHAR(256) NULL,
  token_issuance_evidence_pack_hash VARCHAR(256) NULL,
  evidence_pack_hash VARCHAR(256) NULL,
  lineage_hash_chain_json JSON NULL,
  issuance_signatures_json JSON NULL,
  issuance_metadata_json JSON NULL,
  execution_capability_status VARCHAR(64) NOT NULL DEFAULT 'EXECUTION_NOT_ENABLED',
  activation_execution_status VARCHAR(128) NOT NULL DEFAULT 'TOKEN_ISSUANCE_FINALIZED_NOT_REDEEMABLE_NOT_EXECUTED',
  package_freeze_status VARCHAR(64) NOT NULL DEFAULT 'FROZEN_IMMUTABLE',
  plan_executable_status VARCHAR(64) NOT NULL DEFAULT 'NOT_EXECUTABLE',
  job_creation_status VARCHAR(64) NOT NULL DEFAULT 'NO_REAL_JOB_CREATED',
  queue_dispatch_status VARCHAR(64) NOT NULL DEFAULT 'NO_QUEUE_DISPATCHED',
  runtime_mutation_status VARCHAR(64) NOT NULL DEFAULT 'ZERO_RUNTIME_MUTATION_CONFIRMED',
  approved_by VARCHAR(128) NULL,
  approved_at DATETIME NULL,
  rejected_by VARCHAR(128) NULL,
  rejected_at DATETIME NULL,
  finalized_by VARCHAR(128) NULL,
  finalized_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_issuance_rules (
  rule_id VARCHAR(64) NOT NULL PRIMARY KEY,
  activation_token_issuance_id VARCHAR(64) NOT NULL,
  check_type VARCHAR(128) NOT NULL,
  severity VARCHAR(32) NOT NULL DEFAULT 'INFO',
  description TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_issuance_rules_issuance_id (activation_token_issuance_id)
);

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_issuance_evidence (
  evidence_id VARCHAR(64) NOT NULL PRIMARY KEY,
  activation_token_issuance_id VARCHAR(64) NOT NULL,
  evidence_schema_version VARCHAR(16) NOT NULL DEFAULT '160.0',
  evidence_pack_hash VARCHAR(256) NULL,
  evidence_payload_json JSON NULL,
  lineage_hash_chain_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_issuance_evidence_issuance_id (activation_token_issuance_id)
);

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_issuance_audits (
  audit_id VARCHAR(64) NOT NULL PRIMARY KEY,
  activation_token_issuance_id VARCHAR(64) NOT NULL,
  action VARCHAR(128) NOT NULL,
  actor_id VARCHAR(128) NULL,
  metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_issuance_audits_issuance_id (activation_token_issuance_id)
);
