-- Migration 116: Phase 165 - Controlled High-Risk Cohort Intervention Activation Token Redemption Lock / Pre-Redemption Freeze Gate

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_redempt_lock (
  activation_token_redemption_lock_id VARCHAR(64) PRIMARY KEY,
  source_activation_token_redemption_final_apv_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_env_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_auth_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_readiness_id VARCHAR(64) NOT NULL,
  source_activation_token_issuance_id VARCHAR(64) NOT NULL,
  source_activation_token_preflight_id VARCHAR(64) NOT NULL,
  source_activation_token_staging_id VARCHAR(64) NOT NULL,
  source_activation_token_final_apv_id VARCHAR(64) NOT NULL,
  source_activation_token_env_id VARCHAR(64) NOT NULL,
  source_activation_handoff_id VARCHAR(64) NOT NULL,
  source_activation_decision_id VARCHAR(64) NOT NULL,
  source_activation_lock_id VARCHAR(64) NOT NULL,
  source_activation_auth_id VARCHAR(64) NOT NULL,
  source_activation_readiness_id VARCHAR(64) NOT NULL,
  source_plan_id VARCHAR(64) NOT NULL,
  source_dispatcher_id VARCHAR(64) NOT NULL,
  source_envelope_id VARCHAR(64) NOT NULL,
  source_auth_id VARCHAR(64) NOT NULL,
  source_readiness_id VARCHAR(64) NOT NULL,
  source_approval_id VARCHAR(64) NOT NULL,
  source_prep_id VARCHAR(64) NOT NULL,
  source_review_id VARCHAR(64),
  source_simulation_id VARCHAR(64),
  source_execution_id VARCHAR(64),
  cohort_id VARCHAR(64),
  tenant_id VARCHAR(64),
  simulation_type VARCHAR(64),
  activation_token_redemption_lock_status VARCHAR(64) NOT NULL,
  activation_token_redemption_lock_result VARCHAR(64) NOT NULL,
  risk_level VARCHAR(32) NOT NULL,
  confidence_level VARCHAR(32) NOT NULL,
  projected_impact_score DECIMAL(5,2) NOT NULL,
  rollback_feasibility_score DECIMAL(5,2) NOT NULL,
  evidence_completeness_score DECIMAL(5,2) NOT NULL,
  guardrail_status VARCHAR(32) NOT NULL,
  write_scope_status VARCHAR(32) NOT NULL,
  canary_envelope_json TEXT NOT NULL,
  token_redemption_lock_summary_json TEXT NOT NULL,
  impact_review_json TEXT NOT NULL,
  rollback_review_json TEXT NOT NULL,
  guardrail_review_json TEXT NOT NULL,
  token_redemption_lock_rules_json TEXT NOT NULL,
  token_redemption_lock_blockers_json TEXT NOT NULL,
  non_execution_attestation_json TEXT NOT NULL,
  write_scope_attestation_json TEXT NOT NULL,
  non_redeemable_token_record_json TEXT NOT NULL,
  source_activation_token_redemption_final_approval_hash VARCHAR(64) NOT NULL,
  source_activation_token_redemption_envelope_hash VARCHAR(64) NOT NULL,
  source_activation_token_redemption_authorization_hash VARCHAR(64) NOT NULL,
  source_activation_token_redemption_readiness_hash VARCHAR(64) NOT NULL,
  source_activation_token_issuance_hash VARCHAR(64) NOT NULL,
  source_activation_token_preflight_hash VARCHAR(64) NOT NULL,
  source_activation_token_staging_hash VARCHAR(64) NOT NULL,
  source_token_material_hash VARCHAR(64) NOT NULL,
  source_freeze_package_hash VARCHAR(64) NOT NULL,
  activation_token_redemption_lock_hash VARCHAR(64) NOT NULL,
  execution_capability_status VARCHAR(64) NOT NULL,
  token_status VARCHAR(64) NOT NULL,
  token_redemption_lock_status_val VARCHAR(64) NOT NULL,
  token_redemption_status VARCHAR(64) NOT NULL,
  token_redeemable_status VARCHAR(64) NOT NULL,
  activation_execution_status VARCHAR(64) NOT NULL,
  redemption_package_freeze_status VARCHAR(64) NOT NULL,
  package_freeze_status VARCHAR(64) NOT NULL,
  plan_executable_status VARCHAR(64) NOT NULL,
  job_creation_status VARCHAR(64) NOT NULL,
  queue_dispatch_status VARCHAR(64) NOT NULL,
  runtime_mutation_status VARCHAR(64) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(128) NOT NULL,
  updated_by VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_redempt_lock_rules (
  rule_id VARCHAR(64) PRIMARY KEY,
  activation_token_redemption_lock_id VARCHAR(64) NOT NULL,
  check_type VARCHAR(128) NOT NULL,
  severity VARCHAR(32) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_redempt_lock_ev (
  evidence_id VARCHAR(64) PRIMARY KEY,
  activation_token_redemption_lock_id VARCHAR(64) NOT NULL,
  evidence_schema_version VARCHAR(16) NOT NULL,
  evidence_pack_hash VARCHAR(64) NOT NULL,
  evidence_payload_json TEXT NOT NULL,
  lineage_hash_chain_json TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_redempt_lock_audits (
  audit_id VARCHAR(64) PRIMARY KEY,
  activation_token_redemption_lock_id VARCHAR(64) NOT NULL,
  action_type VARCHAR(128) NOT NULL,
  actor_id VARCHAR(128) NOT NULL,
  details_json TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
