-- Migration 119: Phase 167 - Controlled High-Risk Cohort Intervention Activation Token Redemption Unlock Approval Gate

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_redempt_unlock_apv (
  activation_token_redemption_unlock_approval_id VARCHAR(64) PRIMARY KEY,
  source_activation_token_redemption_unlock_eligibility_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_lock_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_final_apv_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_envelope_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_auth_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_readiness_id VARCHAR(64) NOT NULL,
  source_activation_token_issuance_id VARCHAR(64) NOT NULL,
  source_activation_token_staging_id VARCHAR(64) NOT NULL,
  source_activation_token_preflight_id VARCHAR(64) NOT NULL,
  source_plan_id VARCHAR(64) NOT NULL,
  source_dispatcher_id VARCHAR(64) NOT NULL,
  source_envelope_id VARCHAR(64) NOT NULL,
  source_auth_id VARCHAR(64) NOT NULL,
  source_readiness_id VARCHAR(64) NOT NULL,
  source_approval_id VARCHAR(64) NOT NULL,
  source_prep_id VARCHAR(64) NOT NULL,
  source_review_id VARCHAR(64),
  source_simulation_id VARCHAR(64),
  source_execution_id VARCHAR(64),
  cohort_id VARCHAR(64),
  tenant_id VARCHAR(64),
  simulation_type VARCHAR(64),
  unlock_approval_status VARCHAR(64) NOT NULL,
  unlock_approval_result VARCHAR(64) NOT NULL,
  unlock_eligibility_status VARCHAR(64) NOT NULL,
  token_redemption_lock_status VARCHAR(64) NOT NULL,
  token_redemption_status VARCHAR(64) NOT NULL,
  token_unlock_status VARCHAR(64) NOT NULL,
  token_redeemable_status VARCHAR(64) NOT NULL,
  risk_level VARCHAR(32) NOT NULL,
  confidence_level VARCHAR(32) NOT NULL,
  projected_impact_score DECIMAL(5,2) NOT NULL,
  rollback_feasibility_score DECIMAL(5,2) NOT NULL,
  evidence_completeness_score DECIMAL(5,2) NOT NULL,
  guardrail_status VARCHAR(32) NOT NULL,
  write_scope_status VARCHAR(32) NOT NULL,
  canary_envelope_json LONGTEXT NOT NULL,
  unlock_approval_summary_json LONGTEXT NOT NULL,
  impact_review_json LONGTEXT NOT NULL,
  rollback_review_json LONGTEXT NOT NULL,
  guardrail_review_json LONGTEXT NOT NULL,
  unlock_approval_rules_json LONGTEXT NOT NULL,
  unlock_approval_blockers_json LONGTEXT NOT NULL,
  non_execution_attestation_json LONGTEXT NOT NULL,
  write_scope_attestation_json LONGTEXT NOT NULL,
  source_unlock_eligibility_hash VARCHAR(64) NOT NULL,
  source_redemption_lock_hash VARCHAR(64) NOT NULL,
  source_redemption_package_freeze_hash VARCHAR(64) NOT NULL,
  source_token_material_hash VARCHAR(64) NOT NULL,
  unlock_approval_hash VARCHAR(64) NOT NULL,
  unlock_approval_evidence_pack_hash VARCHAR(64) NOT NULL,
  evidence_pack_hash VARCHAR(64) NOT NULL,
  lineage_hash_chain_json LONGTEXT NOT NULL,
  security_signature_json LONGTEXT NOT NULL,
  approval_rationale_json LONGTEXT NOT NULL,
  execution_capability_status VARCHAR(64) NOT NULL,
  activation_execution_status VARCHAR(64) NOT NULL,
  package_freeze_status VARCHAR(64) NOT NULL,
  redemption_package_freeze_status VARCHAR(64) NOT NULL,
  plan_executable_status VARCHAR(64) NOT NULL,
  job_creation_status VARCHAR(64) NOT NULL,
  queue_dispatch_status VARCHAR(64) NOT NULL,
  runtime_mutation_status VARCHAR(64) NOT NULL,
  approved_by VARCHAR(128),
  approved_at TIMESTAMP NULL DEFAULT NULL,
  rejected_by VARCHAR(128),
  rejected_at TIMESTAMP NULL DEFAULT NULL,
  finalized_by VARCHAR(128),
  finalized_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(128) NOT NULL,
  updated_by VARCHAR(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_redempt_unlock_apv_rl (
  rule_id VARCHAR(64) PRIMARY KEY,
  activation_token_redemption_unlock_approval_id VARCHAR(64) NOT NULL,
  check_type VARCHAR(128) NOT NULL,
  severity VARCHAR(32) NOT NULL,
  description TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_unlock_apv_rl_parent (activation_token_redemption_unlock_approval_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_redempt_unlock_apv_ev (
  evidence_id VARCHAR(64) PRIMARY KEY,
  activation_token_redemption_unlock_approval_id VARCHAR(64) NOT NULL,
  evidence_schema_version VARCHAR(16) NOT NULL,
  evidence_pack_hash VARCHAR(64) NOT NULL,
  evidence_payload_json LONGTEXT NOT NULL,
  lineage_hash_chain_json LONGTEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_unlock_apv_ev_parent (activation_token_redemption_unlock_approval_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_redempt_unlock_apv_aud (
  audit_id VARCHAR(64) PRIMARY KEY,
  activation_token_redemption_unlock_approval_id VARCHAR(64) NOT NULL,
  action_type VARCHAR(128) NOT NULL,
  actor_id VARCHAR(128) NOT NULL,
  details_json LONGTEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_unlock_apv_aud_parent (activation_token_redemption_unlock_approval_id),
  INDEX idx_unlock_apv_aud_action (action_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
