-- Migration 125: Phase 173 - Controlled High-Risk Cohort Intervention Activation Token Redemption Unlock Final Human Authorization Seal Gate

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_redempt_unlock_fhas (
  act_token_redempt_unlock_final_human_authorization_seal_id VARCHAR(64) PRIMARY KEY,
  source_act_token_redempt_unlock_dual_control_authorization_id VARCHAR(64) NOT NULL,
  source_act_token_redempt_unlock_operator_attestation_id VARCHAR(64) NOT NULL,
  source_act_token_redempt_unlock_pre_execution_freeze_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_unlock_seal_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_unlock_final_review_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_unlock_approval_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_unlock_eligibility_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_lock_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_final_apv_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_envelope_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_auth_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_readiness_id VARCHAR(64) NOT NULL,
  source_activation_token_issuance_id VARCHAR(64) NOT NULL,
  source_activation_token_staging_id VARCHAR(64) NOT NULL,
  source_activation_token_preflight_id VARCHAR(64) NOT NULL,
  source_plan_id VARCHAR(64) NOT NULL,
  source_dispatcher_id VARCHAR(64) NOT NULL,
  source_envelope_id VARCHAR(64) NOT NULL,
  source_auth_id VARCHAR(64) NOT NULL,
  source_readiness_id VARCHAR(64) NOT NULL,
  source_approval_id VARCHAR(64) NOT NULL,
  source_prep_id VARCHAR(64) NOT NULL,
  source_review_id VARCHAR(64),
  source_simulation_id VARCHAR(64),
  source_execution_id VARCHAR(64),
  cohort_id VARCHAR(64),
  tenant_id VARCHAR(64),
  simulation_type VARCHAR(64),
  unlock_final_human_authorization_seal_status VARCHAR(64) NOT NULL,
  unlock_final_human_authorization_seal_result VARCHAR(64) NOT NULL,
  unlock_final_human_authorization_seal_mode VARCHAR(64) NOT NULL,
  unlock_dual_control_authorization_status VARCHAR(64) NOT NULL,
  unlock_operator_attestation_status VARCHAR(64) NOT NULL,
  unlock_pre_execution_freeze_status VARCHAR(64) NOT NULL,
  unlock_seal_status VARCHAR(64) NOT NULL,
  unlock_final_review_status VARCHAR(64) NOT NULL,
  unlock_approval_status VARCHAR(64) NOT NULL,
  unlock_eligibility_status VARCHAR(64) NOT NULL,
  token_redemption_lock_status VARCHAR(64) NOT NULL,
  token_redemption_status VARCHAR(64) NOT NULL,
  token_unlock_status VARCHAR(64) NOT NULL,
  token_redeemable_status VARCHAR(64) NOT NULL,
  risk_level VARCHAR(32) NOT NULL,
  confidence_level VARCHAR(32) NOT NULL,
  projected_impact_score DECIMAL(5,2) NOT NULL,
  rollback_feasibility_score DECIMAL(5,2) NOT NULL,
  evidence_completeness_score DECIMAL(5,2) NOT NULL,
  guardrail_status VARCHAR(32) NOT NULL,
  write_scope_status VARCHAR(32) NOT NULL,
  canary_envelope_json LONGTEXT NOT NULL,
  unlock_final_human_authorization_seal_summary_json LONGTEXT NOT NULL,
  impact_review_json LONGTEXT NOT NULL,
  rollback_review_json LONGTEXT NOT NULL,
  guardrail_review_json LONGTEXT NOT NULL,
  unlock_final_human_authorization_seal_rules_json LONGTEXT NOT NULL,
  unlock_final_human_authorization_seal_blockers_json LONGTEXT NOT NULL,
  non_execution_attestation_json LONGTEXT NOT NULL,
  write_scope_attestation_json LONGTEXT NOT NULL,
  source_unlock_dual_control_authorization_hash VARCHAR(64) NOT NULL,
  source_unlock_operator_attestation_hash VARCHAR(64) NOT NULL,
  source_unlock_pre_execution_freeze_hash VARCHAR(64) NOT NULL,
  source_unlock_seal_hash VARCHAR(64) NOT NULL,
  source_unlock_final_review_hash VARCHAR(64) NOT NULL,
  source_unlock_approval_hash VARCHAR(64) NOT NULL,
  source_unlock_eligibility_hash VARCHAR(64) NOT NULL,
  source_redemption_lock_hash VARCHAR(64) NOT NULL,
  source_redemption_final_approval_hash VARCHAR(64) NOT NULL,
  source_redemption_package_freeze_hash VARCHAR(64) NOT NULL,
  source_token_material_hash VARCHAR(64) NOT NULL,
  unlock_final_human_authorization_seal_hash VARCHAR(64) NOT NULL,
  unlock_final_human_authorization_seal_evidence_pack_hash VARCHAR(64) NOT NULL,
  evidence_pack_hash VARCHAR(64) NOT NULL,
  lineage_hash_chain_json LONGTEXT NOT NULL,
  security_signature_json LONGTEXT NOT NULL,
  attestation_rationale_json LONGTEXT NOT NULL,
  execution_capability_status VARCHAR(64) NOT NULL,
  activation_execution_status VARCHAR(64) NOT NULL,
  package_freeze_status VARCHAR(64) NOT NULL,
  redemption_package_freeze_status VARCHAR(64) NOT NULL,
  plan_executable_status VARCHAR(64) NOT NULL,
  job_creation_status VARCHAR(64) NOT NULL,
  queue_dispatch_status VARCHAR(64) NOT NULL,
  runtime_mutation_status VARCHAR(64) NOT NULL,
  primary_authorizer_id VARCHAR(128) NOT NULL,
  secondary_authorizer_id VARCHAR(128) NOT NULL,
  final_human_authorizer_id VARCHAR(128),
  final_human_authorizer_role VARCHAR(64),
  final_human_authorized_at TIMESTAMP NULL DEFAULT NULL,
  final_human_authorization_seal_reason TEXT,
  final_human_authorization_seal_attestation_json LONGTEXT,
  dual_control_authorizer_separation_snapshot_json LONGTEXT,
  approved_by VARCHAR(128),
  approved_at TIMESTAMP NULL DEFAULT NULL,
  rejected_by VARCHAR(128),
  rejected_at TIMESTAMP NULL DEFAULT NULL,
  finalized_by VARCHAR(128),
  finalized_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(128) NOT NULL,
  updated_by VARCHAR(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_redempt_unlock_fhas_rl (
  rule_id VARCHAR(64) PRIMARY KEY,
  act_token_redempt_unlock_final_human_authorization_seal_id VARCHAR(64) NOT NULL,
  check_type VARCHAR(128) NOT NULL,
  severity VARCHAR(32) NOT NULL,
  description TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_unlock_fhas_rl_parent (act_token_redempt_unlock_final_human_authorization_seal_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_redempt_unlock_fhas_ev (
  evidence_id VARCHAR(64) PRIMARY KEY,
  act_token_redempt_unlock_final_human_authorization_seal_id VARCHAR(64) NOT NULL,
  evidence_schema_version VARCHAR(16) NOT NULL,
  evidence_pack_hash VARCHAR(64) NOT NULL,
  evidence_payload_json LONGTEXT NOT NULL,
  lineage_hash_chain_json LONGTEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_unlock_fhas_ev_parent (act_token_redempt_unlock_final_human_authorization_seal_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_redempt_unlock_fhas_aud (
  audit_id VARCHAR(64) PRIMARY KEY,
  act_token_redempt_unlock_final_human_authorization_seal_id VARCHAR(64) NOT NULL,
  action_type VARCHAR(128) NOT NULL,
  actor_id VARCHAR(128) NOT NULL,
  details_json LONGTEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_unlock_fhas_aud_parent (act_token_redempt_unlock_final_human_authorization_seal_id),
  INDEX idx_unlock_fhas_aud_action (action_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
