-- Migration 134: Phase 180 - Controlled High-Risk Cohort Intervention Activation Token Redemption Unlock Governance Readiness Closure Gate

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_redempt_unlock_grc (
  act_token_redempt_unlock_governance_readiness_closure_id VARCHAR(64) PRIMARY KEY,
  source_unlock_fnees_id VARCHAR(64) NOT NULL,
  source_act_token_redempt_unlock_kill_switch_dry_run_id VARCHAR(64) NOT NULL,
  source_act_token_redempt_unlock_emergency_rollback_authority_id VARCHAR(64) NOT NULL,
  source_act_token_redempt_unlock_legal_policy_hold_id VARCHAR(64) NOT NULL,
  source_act_token_redempt_unlock_risk_officer_countersign_id VARCHAR(64) NOT NULL,
  source_act_token_redempt_unlock_compliance_witness_id VARCHAR(64) NOT NULL,
  source_act_token_redempt_unlock_final_human_auth_seal_id VARCHAR(64) NOT NULL,
  source_act_token_redempt_unlock_dual_control_authorization_id VARCHAR(64) NOT NULL,
  source_act_token_redempt_unlock_operator_attestation_id VARCHAR(64) NOT NULL,
  source_act_token_redempt_unlock_pre_execution_freeze_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_unlock_seal_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_unlock_final_review_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_unlock_approval_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_unlock_eligibility_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_lock_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_final_apv_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_envelope_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_auth_id VARCHAR(64) NOT NULL,
  source_activation_token_redemption_readiness_id VARCHAR(64) NOT NULL,
  source_activation_token_issuance_id VARCHAR(64) NOT NULL,
  source_activation_token_staging_id VARCHAR(64) NOT NULL,
  source_activation_token_preflight_id VARCHAR(64) NOT NULL,
  source_plan_id VARCHAR(64) NOT NULL,
  source_dispatcher_id VARCHAR(64) NOT NULL,
  source_envelope_id VARCHAR(64) NOT NULL,
  source_auth_id VARCHAR(64) NOT NULL,
  source_readiness_id VARCHAR(64) NOT NULL,
  source_approval_id VARCHAR(64) NOT NULL,
  source_prep_id VARCHAR(64) NOT NULL,
  cohort_id VARCHAR(64) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  simulation_type VARCHAR(64) NOT NULL,
  unlock_governance_readiness_closure_status VARCHAR(191) NOT NULL,
  unlock_governance_readiness_closure_result VARCHAR(191) NOT NULL,
  unlock_governance_readiness_closure_mode VARCHAR(191) NOT NULL,
  unlock_final_non_execution_evidence_seal_status VARCHAR(191) NOT NULL,
  unlock_kill_switch_dry_run_status VARCHAR(191) NOT NULL,
  unlock_emergency_rollback_authority_status VARCHAR(191) NOT NULL,
  unlock_legal_policy_hold_status VARCHAR(191) NOT NULL,
  unlock_risk_officer_countersign_status VARCHAR(191) NOT NULL,
  unlock_compliance_witness_status VARCHAR(191) NOT NULL,
  unlock_final_human_authorization_seal_status VARCHAR(191) NOT NULL,
  unlock_dual_control_authorization_status VARCHAR(191) NOT NULL,
  unlock_operator_attestation_status VARCHAR(191) NOT NULL,
  unlock_pre_execution_freeze_status VARCHAR(191) NOT NULL,
  unlock_seal_status VARCHAR(191) NOT NULL,
  unlock_final_review_status VARCHAR(191) NOT NULL,
  unlock_approval_status VARCHAR(191) NOT NULL,
  unlock_eligibility_status VARCHAR(191) NOT NULL,
  token_redemption_lock_status VARCHAR(191) NOT NULL,
  token_redemption_status VARCHAR(191) NOT NULL,
  token_unlock_status VARCHAR(191) NOT NULL,
  token_redeemable_status VARCHAR(191) NOT NULL,
  risk_level VARCHAR(64) NOT NULL,
  confidence_level VARCHAR(64) NOT NULL,
  projected_impact_score DECIMAL(5,2) NOT NULL,
  rollback_feasibility_score DECIMAL(5,2) NOT NULL,
  evidence_completeness_score DECIMAL(5,2) NOT NULL,
  guardrail_status VARCHAR(191) NOT NULL,
  write_scope_status VARCHAR(191) NOT NULL,
  canary_envelope_json LONGTEXT NOT NULL,
  governance_readiness_closure_summary_json LONGTEXT NOT NULL,
  impact_review_json LONGTEXT NOT NULL,
  rollback_review_json LONGTEXT NOT NULL,
  guardrail_review_json LONGTEXT NOT NULL,
  governance_readiness_closure_rules_json LONGTEXT NOT NULL,
  governance_readiness_closure_blockers_json LONGTEXT NOT NULL,
  non_execution_attestation_json LONGTEXT NOT NULL,
  write_scope_attestation_json LONGTEXT NOT NULL,
  source_unlock_final_non_execution_evidence_seal_hash VARCHAR(191) NOT NULL,
  source_unlock_kill_switch_dry_run_hash VARCHAR(191) NOT NULL,
  source_unlock_emergency_rollback_authority_hash VARCHAR(191) NOT NULL,
  source_unlock_legal_policy_hold_hash VARCHAR(191) NOT NULL,
  source_unlock_risk_officer_countersign_hash VARCHAR(191) NOT NULL,
  source_unlock_compliance_witness_hash VARCHAR(191) NOT NULL,
  source_unlock_final_human_authorization_seal_hash VARCHAR(191) NOT NULL,
  source_unlock_dual_control_authorization_hash VARCHAR(191) NOT NULL,
  source_unlock_operator_attestation_hash VARCHAR(191) NOT NULL,
  source_unlock_pre_execution_freeze_hash VARCHAR(191) NOT NULL,
  source_unlock_seal_hash VARCHAR(191) NOT NULL,
  source_unlock_final_review_hash VARCHAR(191) NOT NULL,
  source_unlock_approval_hash VARCHAR(191) NOT NULL,
  source_unlock_eligibility_hash VARCHAR(191) NOT NULL,
  source_redemption_lock_hash VARCHAR(191) NOT NULL,
  source_redemption_final_approval_hash VARCHAR(191) NOT NULL,
  source_redemption_package_freeze_hash VARCHAR(191) NOT NULL,
  source_token_material_hash VARCHAR(191) NOT NULL,
  unlock_governance_readiness_closure_hash VARCHAR(191) NOT NULL,
  unlock_governance_readiness_closure_evidence_pack_hash VARCHAR(191) NOT NULL,
  evidence_pack_hash VARCHAR(191) NOT NULL,
  lineage_hash_chain_json LONGTEXT NOT NULL,
  security_signature_json LONGTEXT NOT NULL,
  attestation_rationale_json LONGTEXT NOT NULL,
  execution_capability_status VARCHAR(191) NOT NULL,
  activation_execution_status VARCHAR(191) NOT NULL,
  package_freeze_status VARCHAR(191) NOT NULL,
  redemption_package_freeze_status VARCHAR(191) NOT NULL,
  plan_executable_status VARCHAR(191) NOT NULL,
  job_creation_status VARCHAR(191) NOT NULL,
  queue_dispatch_status VARCHAR(191) NOT NULL,
  runtime_mutation_status VARCHAR(191) NOT NULL,
  primary_authorizer_id VARCHAR(64) NOT NULL,
  secondary_authorizer_id VARCHAR(64) NOT NULL,
  final_human_authorizer_id VARCHAR(64) NOT NULL,
  compliance_witness_id VARCHAR(64) NOT NULL,
  risk_officer_id VARCHAR(64) NOT NULL,
  legal_policy_officer_id VARCHAR(64) NOT NULL,
  rollback_officer_id VARCHAR(64) NOT NULL,
  kill_switch_verification_officer_id VARCHAR(64) NOT NULL,
  evidence_seal_officer_id VARCHAR(64) NOT NULL,
  governance_closure_officer_id VARCHAR(64) DEFAULT NULL,
  governance_closure_officer_role VARCHAR(64) DEFAULT NULL,
  governance_closure_confirmed_at DATETIME DEFAULT NULL,
  governance_closure_reason TEXT DEFAULT NULL,
  governance_readiness_closure_snapshot_json LONGTEXT DEFAULT NULL,
  full_chain_non_execution_snapshot_json LONGTEXT DEFAULT NULL,
  prior_authorizer_separation_snapshot_json LONGTEXT DEFAULT NULL,
  created_by VARCHAR(64) NOT NULL,
  updated_by VARCHAR(64) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_unlock_grc_source_fnees (source_unlock_fnees_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_redempt_unlock_grc_rl (
  rule_log_id VARCHAR(64) PRIMARY KEY,
  act_token_redempt_unlock_governance_readiness_closure_id VARCHAR(64) NOT NULL,
  rule_code VARCHAR(191) NOT NULL,
  rule_description TEXT NOT NULL,
  evaluation_status VARCHAR(191) NOT NULL,
  evaluation_message TEXT,
  severity VARCHAR(64) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  KEY idx_unlock_grc_rl_parent (act_token_redempt_unlock_governance_readiness_closure_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_redempt_unlock_grc_ev (
  evidence_id VARCHAR(64) PRIMARY KEY,
  act_token_redempt_unlock_governance_readiness_closure_id VARCHAR(64) NOT NULL,
  evidence_pack_hash VARCHAR(191) NOT NULL,
  evidence_pack_json LONGTEXT NOT NULL,
  created_by VARCHAR(64) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_unlock_grc_ev_parent (act_token_redempt_unlock_governance_readiness_closure_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cb_cohort_intervention_activation_token_redempt_unlock_grc_aud (
  audit_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  act_token_redempt_unlock_governance_readiness_closure_id VARCHAR(64) NOT NULL,
  action VARCHAR(191) NOT NULL,
  actor VARCHAR(64) NOT NULL,
  details TEXT,
  ip_address VARCHAR(45) DEFAULT NULL,
  user_agent VARCHAR(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  KEY idx_unlock_grc_aud_parent (act_token_redempt_unlock_governance_readiness_closure_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
