export interface TokenRedemptionUnlockOperatorAttestation {
  activation_token_redemption_unlock_operator_attestation_id: string;
  source_activation_token_redemption_unlock_pre_execution_freeze_id: string;
  source_activation_token_redemption_unlock_seal_id: string;
  source_activation_token_redemption_unlock_final_review_id: string;
  source_activation_token_redemption_unlock_approval_id: string;
  source_activation_token_redemption_unlock_eligibility_id: string;
  source_activation_token_redemption_lock_id: string;
  source_activation_token_redemption_final_apv_id: string;
  source_activation_token_redemption_envelope_id: string;
  source_activation_token_redemption_auth_id: string;
  source_activation_token_redemption_readiness_id: string;
  source_activation_token_issuance_id: string;
  source_activation_token_staging_id: string;
  source_activation_token_preflight_id: string;
  source_plan_id: string;
  source_dispatcher_id: string;
  source_envelope_id: string;
  source_auth_id: string;
  source_readiness_id: string;
  source_approval_id: string;
  source_prep_id: string;
  source_review_id: string | null;
  source_simulation_id: string | null;
  source_execution_id: string | null;
  cohort_id: string | null;
  tenant_id: string | null;
  simulation_type: string | null;
  unlock_operator_attestation_status: 'DRAFT' | 'EVALUATED' | 'APPROVED' | 'REJECTED' | 'FINALIZED' | 'BLOCKED';
  unlock_operator_attestation_result: 'PENDING' | 'OPERATOR_ATTESTED_NOT_UNLOCKED' | 'OPERATOR_ATTESTATION_FAILED' | 'OPERATOR_ATTESTATION_BLOCKED_BY_PRE_EXECUTION_FREEZE' | 'OPERATOR_ATTESTATION_BLOCKED_BY_GUARDRAIL';
  unlock_operator_attestation_mode: string;
  unlock_pre_execution_freeze_status: string;
  unlock_seal_status: string;
  unlock_final_review_status: string;
  unlock_approval_status: string;
  unlock_eligibility_status: string;
  token_redemption_lock_status: string;
  token_redemption_status: string;
  token_unlock_status: string;
  token_redeemable_status: string;
  risk_level: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  confidence_level: 'LOW' | 'MEDIUM' | 'HIGH';
  projected_impact_score: number;
  rollback_feasibility_score: number;
  evidence_completeness_score: number;
  guardrail_status: 'PENDING' | 'PASS' | 'FAIL';
  write_scope_status: 'PENDING' | 'PASS' | 'FAIL';
  canary_envelope_json: any;
  unlock_operator_attestation_summary_json: any;
  impact_review_json: any;
  rollback_review_json: any;
  guardrail_review_json: any;
  unlock_operator_attestation_rules_json: any;
  unlock_operator_attestation_blockers_json: any;
  non_execution_attestation_json: any;
  write_scope_attestation_json: any;
  source_unlock_pre_execution_freeze_hash: string;
  source_unlock_seal_hash: string;
  source_unlock_final_review_hash: string;
  source_unlock_approval_hash: string;
  source_unlock_eligibility_hash: string;
  source_redemption_lock_hash: string;
  source_redemption_final_approval_hash: string;
  source_redemption_package_freeze_hash: string;
  source_token_material_hash: string;
  unlock_operator_attestation_hash: string;
  unlock_operator_attestation_evidence_pack_hash: string;
  evidence_pack_hash: string;
  lineage_hash_chain_json: any;
  security_signature_json: any;
  attestation_rationale_json: any;
  execution_capability_status: string;
  activation_execution_status: string;
  package_freeze_status: string;
  redemption_package_freeze_status: string;
  plan_executable_status: string;
  job_creation_status: string;
  queue_dispatch_status: string;
  runtime_mutation_status: string;
  approved_by?: string;
  approved_at?: string;
  rejected_by?: string;
  rejected_at?: string;
  finalized_by?: string;
  finalized_at?: string;
  created_at: string;
  updated_at: string;
  created_by: string;
  updated_by: string;
}

export interface UnlockOperatorAttestationRule {
  rule_id: string;
  activation_token_redemption_unlock_operator_attestation_id: string;
  check_type: string;
  severity: 'INFO' | 'WARNING' | 'CRITICAL';
  description: string;
  created_at: string;
}
