/**
 * src/api/services/phase194ErrorTaxonomy.js
 *
 * Phase 194H — Machine-Readable Error Taxonomy & Domain Exceptions
 *
 * Standardizes domain errors across PDF upload, extraction, target formation,
 * calibration, curve governance, acceptance, and Jev advisory provider.
 */

const ERROR_CODES = Object.freeze({
  // Upload & PDF Extraction
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  PDF_MALFORMED: 'PDF_MALFORMED',
  PDF_ENCRYPTED: 'PDF_ENCRYPTED',
  TEXT_EXTRACTION_FAILED: 'TEXT_EXTRACTION_FAILED',
  OCR_REQUIRED: 'OCR_REQUIRED',
  LANGUAGE_UNCERTAIN: 'LANGUAGE_UNCERTAIN',
  QUOTE_STRUCTURE_UNRECOGNIZED: 'QUOTE_STRUCTURE_UNRECOGNIZED',
  NUMERIC_AMBIGUITY: 'NUMERIC_AMBIGUITY',

  // Target Formation & Evidence Validation
  UNREVIEWED_EVIDENCE_NOT_ELIGIBLE: 'UNREVIEWED_EVIDENCE_NOT_ELIGIBLE',
  MIXED_BOOKSPEC_TARGETS: 'MIXED_BOOKSPEC_TARGETS',
  DUPLICATE_TARGET_QUANTITY: 'DUPLICATE_TARGET_QUANTITY',
  INVALID_TARGET_BASIS: 'INVALID_TARGET_BASIS',
  INCONSISTENT_EVIDENCE_REQUIRES_OPERATOR_REVIEW: 'INCONSISTENT_EVIDENCE_REQUIRES_OPERATOR_REVIEW',

  // Calibration & Curve Governance
  UNDERDETERMINED_MODEL: 'UNDERDETERMINED_MODEL',
  STALE_CALIBRATION_BASELINE: 'STALE_CALIBRATION_BASELINE',
  GOVERNANCE_CURVE_REQUIRES_REVIEW: 'GOVERNANCE_CURVE_REQUIRES_REVIEW',
  GOVERNANCE_CURVE_REJECTED: 'GOVERNANCE_CURVE_REJECTED',
  CALIBRATION_ACCEPTANCE_TOLERANCE_EXCEEDED: 'CALIBRATION_ACCEPTANCE_TOLERANCE_EXCEEDED',

  // Tenant Isolation & Access Control
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  QUOTE_EVIDENCE_NOT_FOUND: 'QUOTE_EVIDENCE_NOT_FOUND',

  // Jev Provider
  JEV_TIMEOUT: 'JEV_TIMEOUT',
  JEV_UNAVAILABLE: 'JEV_UNAVAILABLE',
  JEV_AUTH_ERROR: 'JEV_AUTH_ERROR',
  JEV_INVALID_RESPONSE: 'JEV_INVALID_RESPONSE',

  // Feature Flags & Operational Control
  FEATURE_DISABLED_BY_OPERATOR: 'FEATURE_DISABLED_BY_OPERATOR'
});

const DEFAULT_STATUS_CODES = Object.freeze({
  [ERROR_CODES.INVALID_FILE_TYPE]: 400,
  [ERROR_CODES.FILE_TOO_LARGE]: 413,
  [ERROR_CODES.PDF_MALFORMED]: 422,
  [ERROR_CODES.PDF_ENCRYPTED]: 422,
  [ERROR_CODES.TEXT_EXTRACTION_FAILED]: 422,
  [ERROR_CODES.OCR_REQUIRED]: 422,
  [ERROR_CODES.LANGUAGE_UNCERTAIN]: 422,
  [ERROR_CODES.QUOTE_STRUCTURE_UNRECOGNIZED]: 422,
  [ERROR_CODES.NUMERIC_AMBIGUITY]: 422,

  [ERROR_CODES.UNREVIEWED_EVIDENCE_NOT_ELIGIBLE]: 422,
  [ERROR_CODES.MIXED_BOOKSPEC_TARGETS]: 422,
  [ERROR_CODES.DUPLICATE_TARGET_QUANTITY]: 422,
  [ERROR_CODES.INVALID_TARGET_BASIS]: 422,
  [ERROR_CODES.INCONSISTENT_EVIDENCE_REQUIRES_OPERATOR_REVIEW]: 422,

  [ERROR_CODES.UNDERDETERMINED_MODEL]: 422,
  [ERROR_CODES.STALE_CALIBRATION_BASELINE]: 409,
  [ERROR_CODES.GOVERNANCE_CURVE_REQUIRES_REVIEW]: 422,
  [ERROR_CODES.GOVERNANCE_CURVE_REJECTED]: 422,
  [ERROR_CODES.CALIBRATION_ACCEPTANCE_TOLERANCE_EXCEEDED]: 422,

  [ERROR_CODES.TENANT_MISMATCH]: 403,
  [ERROR_CODES.QUOTE_EVIDENCE_NOT_FOUND]: 404,

  [ERROR_CODES.JEV_TIMEOUT]: 504,
  [ERROR_CODES.JEV_UNAVAILABLE]: 503,
  [ERROR_CODES.JEV_AUTH_ERROR]: 502,
  [ERROR_CODES.JEV_INVALID_RESPONSE]: 502,

  [ERROR_CODES.FEATURE_DISABLED_BY_OPERATOR]: 403
});

function createPhase194Error(code, message, customStatusCode = null, details = null) {
  const err = new Error(message || `Phase 194 Domain Error: ${code}`);
  err.code = code;
  err.statusCode = customStatusCode || DEFAULT_STATUS_CODES[code] || 500;
  if (details) err.details = details;
  return err;
}

module.exports = {
  ERROR_CODES,
  DEFAULT_STATUS_CODES,
  createPhase194Error
};
